Cindx#	system.for - Multi-user game to program ships, ports, equipment to take over a galaxy
C@HDR@	$Id$
C@HDR@
C@HDR@	Copyright (c) 1982-2026 Christopher Caldwell (Christopher.M.Caldwell0@gmail.com)
C@HDR@
C@HDR@	Permission is hereby granted, free of charge, to any person
C@HDR@	obtaining a copy of this software and associated documentation
C@HDR@	files (the "Software"), to deal in the Software without
C@HDR@	restriction, including without limitation the rights to use,
C@HDR@	copy, modify, merge, publish, distribute, sublicense, and/or
C@HDR@	sell copies of the Software, and to permit persons to whom
C@HDR@	the Software is furnished to do so, subject to the following
C@HDR@	conditions:
C@HDR@	
C@HDR@	The above copyright notice and this permission notice shall be
C@HDR@	included in all copies or substantial portions of the Software.
C@HDR@	
C@HDR@	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
C@HDR@	KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
C@HDR@	WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
C@HDR@	AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
C@HDR@	HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
C@HDR@	WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
C@HDR@	FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
C@HDR@	OTHER DEALINGS IN THE SOFTWARE.
C
Chist#	2026-02-17 - Christopher.M.Caldwell0@gmail.com - Created
C------------------------------------------------------------------------
Cdoc#	system.for - Multi-user game to program ships, ports, equipment to take over a galaxy
Cdoc#	Made with Roger Long's inspiration and Robert Kenney's HIPAK.MAC.
Cdoc#	More of a programmer's game than a war game.
C------------------------------------------------------------------------
	SUBROUTINE BUGMSG( MSGARA, COM, MSGLEN )

	IMPLICIT INTEGER ( A - Z )

	INTEGER MSGARA( 16 )
	INTEGER COM( 80 )

	CALL SELECT( 0 )
	CALL STRING('^M^JFATAL ERROR: ^E')
	CALL STRING( MSGARA )
	IF( MSGLEN .LE. 0 ) GOTO 200
	CALL STRING('  FOUND IN LINE:^M^J^E')
	CALL STRING( COM, 1, MSGLEN )
	GOTO 300
200	IF( MSGLEN .EQ. 0 ) GOTO 300
	CALL STRING(' = ^E')
	CALL NUMBER( COM(1) )
300	CALL GRAFON
	CALL CURSOR( 1, 1 )
	CALL CURBUF
	CALL NAP( 3000, 0 )
	CALL EXPROG
	END

	FUNCTION FIRSTC( SIXB )
	IMPLICIT INTEGER ( A - Z )
	CALL CONVRT( SIXB, 1, 6, AC, 0 )
	FIRSTC = AC - 32
	RETURN 
	END
	SUBROUTINE INITDB( COM, P, LPRIVD )

	IMPLICIT INTEGER ( A - Z )

	INTEGER COM( 80 ), FILESP( 13 ), F(5), T(5), P(20)
	LOGICAL STALON, LPRIVD, ERROR, IEOF

	COMMON/FILCOM/FILESP

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

C***	DEFINE ARRAY NAMES
	DATA
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL
     &	    /1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
     &	    18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
     &	    33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45/

	DATA STALON/.FALSE./

	CALL ENABLE
	IF(ISERCH(P,ISXBIT('EMPIRE'),20).NE.0.AND.LPRIVD) GOTO 45
	IF( JOB(-1) .EQ. 0 ) GOTO 50	! NON TOPS10 DO NOT HAVE UPD FILES
	CALL OFILE( 2, FILESP, "400000000014 )
	IF(ERROR(0))CALL BUGMSG('INIT: UPD OPEN FAILURE.^E',0,0)
	FILESP(5) = ISXBIT('UPD')
	CALL RFILE( 2, FILESP )
	IF( ERROR(0) ) GOTO 50

C***	UPDATE FILE EXISTS - READ IT INTO HISEGMENT

	CALL HIPROT( 0 )
	BEGBLK = NHIBLK(0)
	CALL FILGET( 2, TOPLOC, IEOF )
	CALL CCORE( 0, TOPLOC )			! READ LENGTH, INC CORE
	IF(ERROR(0)) CALL BUGMSG('INIT: CANNOT ALLOCATE CORE.^E',0,0)
	CALL D( BEGBLK+3, TOPLOC )
	DO 40 I = 1, 490
	    CALL FILGET( 2, BEGADR, IEOF )
	    CALL D( BEGBLK+I+3, BEGADR )
40	CONTINUE
41	CONTINUE
	CALL FILGET( 2, IVAL, IEOF )
	IF( IEOF ) GOTO 42
	CALL D( BEGADR, IVAL )
	BEGADR = BEGADR + 1
	GOTO 41

42	J = 1
	CALL PUTVAL( USEFUL, 7, 0 )
43	CALL GETVAL( PROGS, J, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 800
	CALL PUTVAL( NCSTRU, J, 63 )
	J = J + 1
	GOTO 43

C***	NOT READING UPD FILE - GET DATA FILE.

45	STALON = .TRUE.

50	CALL OFILE( 2, FILESP, "400000000000 )
	IF( ERROR(0) ) CALL BUGMSG('INIT: DAT OPEN FAILURE.^E',0,0)
	FILESP(5) = ISXBIT('DAT')
	CALL RFILE( 2, FILESP )
	IF(ERROR(0))CALL BUGMSG('INIT: LOOKUP FAILURE.^E',0,0)
	CALL SKPCOM( COM, LEN )
	CALL GETNUM(COM, LEN, NUMSTR,10, NPL,10, MAXUNI,10,
     &	     NPROGS,10, MAXPRG,10, MAXMEM,10, MAXPLA,10 )
	IF(NUMSTR.LE.0)CALL BUGMSG('INIT: NUMSTR<=0.^E',COM,LEN)
	IF(NPL.LT.NUMSTR)CALL BUGMSG('INIT: NPL<NUMSTR.^E',COM,LEN)
	IF(MAXUNI.LE.0)CALL BUGMSG('INIT: MAXUNI<=0.^E',COM,LEN)
	IF(NPROGS.LE.0)CALL BUGMSG('INIT: NPROGS<=0.^E',COM,LEN)
	IF(MAXPRG.LE.0)CALL BUGMSG('INIT: MAXPRG<=0.^E',COM,LEN)
	IF(MAXMEM.LT.MAXPRG)CALL BUGMSG('INIT: MAXMEM<MAXPRG.^E',COM,LEN)
	IF(MAXPLA.LE.0)CALL BUGMSG('INIT: MAXPLA<=0.^E',COM,LEN)

C**********************************************************************

	CALL INIT( NAME, 36, NUMSTR, 2 )	! INIT STAR NAME ARRAY
	CALL INIT( DEST, 12, NUMSTR, 5 )	! POSSIBLE DESTINATIONS
						! FOR HYPER JUMP
	CALL INIT( TIME, 7, NUMSTR, 7 )		! TIME REQUIRED TO JUMP
						! TO EACH PLACE
	CALL INIT( WPLACE, 12, NUMSTR )		! STAR POINTERS
	CALL INIT( RESTRN, 5, NPL, 2 )		! INIT RESOURCE ARRAY
						! 1: ORE/TURN
						! 2: FOOD/TURN
	CALL INIT( WSTAR, 7, NPL )		! WHAT STAR AM I
	CALL INIT( WPLAN, 4, NPL )		! WHAT PLANET AM I
	CALL INIT( WMOON, 4, NPL )		! WHAT MOON AM I
	CALL INIT( PTYPE, 2, NPL )		! PLANET TYPE:
						! 1: HABITABLE
						! 2: ORDINARY
						! 3: GASSEOUS
	CALL INIT( POP, 18, NPL )		! POPULATION
	CALL INIT( POPORG, 6, NPL )		! POPULATION ALLEGIANCE
	CALL INIT( HUNGER, 18, NPL )		! POPULATION HUNGER
	CALL INIT( OPRIND, 9, NPL )		! POPULATION OPRESSION
	CALL INIT( PLCORG, 6, NPL, 2 )		! PLACE CONTROLLED BY
	CALL INIT( NUAPLC, 12, NPL, 2 )		! NUM UNITS AT PLACE
	CALL INIT( ORG, 6, MAXUNI )		! ORIGIN OF SHIP
	CALL INIT( RES, 6, MAXUNI, 4 )		! INIT UNIT RESOURCE:
						! 1: ORE
						! 2: FOOD
						! 3: LUXURY
						! 4: MEN
	CALL INIT( TYPE, 3, MAXUNI )		! UNIT TYPE:
						! 1: SPACESHIP
						! 2: HYPERSHIP
						! 3: GROUND UNIT
						! 4: ORE PROCESSOR
						! 5: FOOD PROCESSOR
						! 6: LUXURY PROCESSOR
						! 7: PORT
	CALL INIT( SHIPTR, 12, MAXUNI )		! WHERE IS UNIT?
	CALL INIT( ORBIT, 2, MAXUNI )		! IN WHAT ORBIT?
						! 1: GROUND
						! 2: LOW ORBIT
						! 3: HIGH ORBIT
	CALL INIT( HMFLAG, 2, MAXUNI )		! 0: NORMAL SPACE
						! 1: HYPER SPACE
						! 2: MOVING
	CALL INIT( WPROGR, 9, MAXUNI )		! WHICH PROG RUNNING
	CALL INIT( PC, 6, MAXUNI )		! WHERE IS IT IN PROG?
	CALL INIT( ONERPC, 6, MAXUNI )		! GO WHERE ON ERROR
	CALL INIT( TMTONX, 18, MAXUNI )		! TIME TO NEXT INSTR.
	CALL INIT( PRDTIM, 18, MAXUNI )		! TIME TO NEXT PROD.
	CALL INIT( POWER, 7, MAXUNI )		! UNIT'S TOT. POWER
	CALL INIT( POWDST, 7, MAXUNI, 3, 2 )	! 1: ENGINE/MAX
						! 2: SHIELD/MAX
						! 3: BEAM/MAX
	CALL INIT( PROGS, 18, NPROGS )		! LIST OF PLAYERS
	CALL INIT( PRGJOB, 7, NPROGS )		! PLAYER'S JOBS (OR 0)
	CALL INIT( NOFUNI, 12, NPROGS )		! NUM UNITS FOR PLAYERS
	CALL INIT( EMPCOD, 3, NPROGS )		! WHAT KIND OF MESSAGE:
						! 1: ERROR
						! 2: INFORM
						! 3: BATTLE
						! 4: REVOLT
	CALL INIT( EMPDST, 12, NPROGS )		! WHICH UNIT'S ERROR
						! WHICH UNIT'S INFORM
						! WHERE IS BATTLE
						! WHERE IS REVOLT
C	CALL INIT( EMPINF, 18, NPROGS )		! INFORM MESSAGE CODE
	CALL INIT( EMPINF, 36, NPROGS )		! INFORM MESSAGE CODE
	CALL INIT( EMPC, 6, NPROGS )		! PC OF INFORM
						! PC OF ERROR
						! ORBIT OF BATTLE
						! 0
	CALL INIT( NCSTRU, 6, NPROGS )		! NUMBER OF TOTAL
						! CLICKS SINCE THIS
						! PROG LOOPED.
	CALL INIT( NVERB, 4, MAXMEM )		! UNIT'S ACTION
	CALL INIT( NCODE, 4, MAXMEM )		! UNIT'S CODE
C	CALL INIT( NDEST, 18, MAXMEM )		! UNIT'S NOUN (DEST)
	CALL INIT( NDEST, 36, MAXMEM )		! UNIT'S NOUN (DEST)
	CALL INIT( STRADR, 12, MAXPRG )		! WHERE PROG BEGINS
	CALL INIT( LENPRG, 6, MAXPRG )		! LENGTH OF PROG
	CALL INIT( NUMUSR, 12, MAXPRG )		! #USERS USING PROG
	CALL INIT( MESTRN, 7, 72 )		! MESSAGE ARRAY
	CALL INIT( PTIME, 36, 3 )		! 1: STARTING DATE
						! 2: STARTING TIME
						! 3: CLICKS ELAPSED
	CALL INIT( USEFUL, 18, 17 )		! MISCELANIOUS INFO:
						! 1: NUMSTR
						! 2: NUMPLA
						! 3: NUMOON
						! 4: LASPLC
						! 5: LUNIT
						! 6: NPROGS
						! 7: WHOINL
						! 8: LPROGR
						! 9: LMEM
						! 10: WHOTO
						! 11: WHOFRM
						! 12: MAXUNI
						! 13: MAXPRG
						! 14: MAXMEM
						! 15: MAXPLA
						! 16: STAND ALONE
						! 17: PRESERVE

C**********************************************************************

	LASPLC = NUMSTR
	DO 700 K = 1, NUMSTR
	    STAR = K
	    CALL SKPCOM( COM, LEN )
	    DO 100 I = 1, 12
		IF( ICON(COM(I)) .LE. 32 ) GOTO 110
100	    CONTINUE
	    I = 13
110	    IF(LEN.LE.I)CALL BUGMSG('INIT: ISOLATED STAR.^E',COM,LEN)
	    F( 2 ) = 0
	    CALL CONVRT( COM, I-1, 1, F, 6 )
	    CALL PUTVAL( NAME, STAR, 1, F(1) )
	    CALL PUTVAL( NAME, STAR, 2, F(2) )
	    CALL PUTVAL( WSTAR, STAR, STAR )
	    CALL GETNUM( COM(I), LEN-I+1, F(1),10,T(1),10,
     &		F(2),10,T(2),10, F(3),10,T(3),10, F(4),10,T(4),10,
     &		F(5),10,T(5),10 )
	    DO 200 I = 1, 5
		CALL PUTVAL( DEST, STAR, I+0, F(I) )
		CALL PUTVAL( TIME, STAR, I+0, T(I) )
200	    CONTINUE
300	    PLANUM = 0
400	    CALL SKPCOM( COM, LEN )
	    IF( COM(1) .EQ. '*' ) GOTO 700
	    ITYPE = 0
	    IF( COM(1) .EQ. 'H' ) ITYPE = 1
	    IF( COM(1) .EQ. 'O' ) ITYPE = 2
	    IF( COM(1) .EQ. 'G' ) ITYPE = 3
	    IF(ITYPE.EQ.0)CALL BUGMSG('INIT: BAD PLANET.^E',COM,LEN)
	    PLANUM = PLANUM + 1
	    NUMPLA = NUMPLA + 1
	    LASPLC = LASPLC + 1
	    IF(LASPLC.GT.NPL)CALL BUGMSG('INIT: LASPLC>NPL.^E',COM,LEN)
	    IF( PLANUM .EQ. 1 ) CALL PUTVAL( WPLACE, STAR, LASPLC )
	    CALL GETNUM( COM, LEN, P(1),10,F(1),10,T(1),10,
     &		P(2),10,F(2),10,T(2),10, P(3),10,F(3),10,T(3),10,
     &		P(4),10,F(4),10,T(4),10, P(5),10,F(5),10,T(5),10 )
	    CALL PUTVAL( WSTAR, LASPLC, STAR )
	    CALL PUTVAL( WPLAN, LASPLC, PLANUM )
	    CALL PUTVAL( PTYPE, LASPLC, ITYPE )
	    CALL PUTVAL( POP, LASPLC, P(1) )
	    CALL PUTVAL( RESTRN, LASPLC, 1, T(1) )
	    CALL PUTVAL( RESTRN, LASPLC, 2, F(1) )

500	    MOONUM = 0
600	    TEMP = MOONUM*12 + 13
	    IF( TEMP .GT. LEN ) GOTO 400
	    TEMP = COM( TEMP )
	    ITYPE = 0
	    IF( TEMP .EQ. 'H' ) ITYPE = 1
	    IF( TEMP .EQ. 'O' ) ITYPE = 2
	    IF( TEMP .EQ. 'G' ) ITYPE = 3
	    IF(ITYPE.EQ.0)CALL BUGMSG('INIT: BAD MOON.^E',COM,LEN)
	    MOONUM = MOONUM + 1
	    LASPLC = LASPLC + 1
	    NUMOON = NUMOON + 1
	    IF(LASPLC.GT.NPL)CALL BUGMSG('INIT: LASPLC>NPL.^E',COM,LEN)
	    CALL PUTVAL( WSTAR, LASPLC, STAR )
	    CALL PUTVAL( WPLAN, LASPLC, PLANUM )
	    CALL PUTVAL( WMOON, LASPLC, MOONUM )
	    CALL PUTVAL( PTYPE, LASPLC, ITYPE )
	    CALL PUTVAL( POP, LASPLC, P(MOONUM+1) )
	    CALL PUTVAL( RESTRN, LASPLC, 1, T(MOONUM+1) )
	    CALL PUTVAL( RESTRN, LASPLC, 2, F(MOONUM+1) )
	    GOTO 600
700	CONTINUE
	CALL MCALL1( "14, IVAL, I )		! GET STARTING DATE
	CALL PUTVAL( PTIME, 1, IVAL )
	CALL MCALL1( "23, IVAL, I )		! AND TIME
	CALL PUTVAL( PTIME, 2, IVAL )
	CALL PUTVAL( USEFUL, 1, NUMSTR )
	CALL PUTVAL( USEFUL, 2, NUMPLA )
	CALL PUTVAL( USEFUL, 3, NUMOON )
	CALL PUTVAL( USEFUL, 4, LASPLC )
	CALL PUTVAL( USEFUL, 6, NPROGS )
	CALL PUTVAL( USEFUL, 12, MAXUNI )
	CALL PUTVAL( USEFUL, 13, MAXPRG )
	CALL PUTVAL( USEFUL, 14, MAXMEM )
	CALL PUTVAL( USEFUL, 15, MAXPLA )
	IF( .NOT. STALON ) GOTO 800
	CALL PUTVAL( USEFUL, 16, 1 )
	CALL PUTVAL( USEFUL, 17, 1 )
800	CALL CLOSE( 2 )
	CALL UNLOCK
	RETURN
	END
	SUBROUTINE SKPCOM( COM, LEN )

	INTEGER COM( 80 )
	LOGICAL IEOF

100	CALL GETSTR( COM, 80, LEN, 2, IEOF )
	IF(IEOF)CALL BUGMSG('INIT: PREMATURE END OF FILE.^E',0,0)
	IF( LEN .EQ. 0 ) GOTO 100
	IF( COM(1) .EQ. ';' ) GOTO 100
C	CALL ALLCAP( COM, LEN )
	RETURN
	END
	SUBROUTINE EXUNIT

	IMPLICIT INTEGER ( A - Z )

	INTEGER TEAM( 2, 50 ), NUMOP(2)
	LOGICAL LMOVE

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

C***	GO INCREMENT ALL PLAYERS TO FIND WHO IS NOT PLAYING

	CALL GETVAL( USEFUL, 5, LUNIT )
	DO 10 I = 1, NPROGS
	    CALL GETVAL( NCSTRU, I+0, IVAL )
	    IF( IVAL .LT. 63 ) CALL ADDVAL( -1, 1 )
	    IF( IVAL .GE. 63 ) CALL PUTVAL( PRGJOB, PLAYER, 0 )
10	CONTINUE
	CALL PUTVAL( NCSTRU, PLAYER, 0 )
	CALL PUTVAL( PRGJOB, PLAYER, JOB(0) )

	CALL GETVAL( USEFUL, 7, WHOINL )
	IF( WHOINL .EQ. 0 ) GOTO 20
	CALL GETVAL( NCSTRU, WHOINL, IVAL )
	IF( IVAL .LT. 63 ) RETURN
	CALL PUTVAL( USEFUL, 7, PLAYER )
	CALL MESSAG('Player #^E')
	CALL NUMBER( WHOINL, -2 )
	CALL STRING(' stuck in EXUNIT loop.  Clearing.^G^E')
	GOTO 30

20	CALL ENABLE
	CALL PUTVAL( -1, PLAYER )

30	ACPLAR = PLAYER
	CALL ADDVAL( PTIME, 3, 1 )		! INCREMENT TIME
	CALL GETVAL( -1, IVAL )			! SAVE WORLD EVERY
	IF(MOD(IVAL,1000).EQ.0) CALL SAVESG	! 1000 CYCLES

C***	LOOP THROUGH THE SYSTEM FOR BATTLES

	DO 60 I = 1, LASPLC
	    LOC = I
	    CALL GETVAL( POP, LOC, J )
	    IF( J .EQ. 0 ) GOTO 34
	    CALL GETVAL( HUNGER, LOC, HUNGFC )
	    HUNGFC = HUNGFC + J
	    CALL GETVAL( RESTRN, LOC, 2, IVAL )
	    HUNGFC = MIN0( MAX0( 0, HUNGFC - 1000*IVAL ), 2^18-1 )
	    CALL PUTVAL( HUNGER, LOC, HUNGFC )
	    IF( HUNGFC .GT. 100000 ) CALL PUTVAL( POP, LOC, 99*J/100 )
	    CALL GETVAL( OPRIND, LOC, IVAL )
	    CALL PUTVAL( -1, 0 )
	    IF(IRAN(50)+50.GE.SQRT(FLOAT(J))*HUNGFC/(1000*(IVAL+1)))
     &		GOTO 34
	    CALL GETVAL( PLCORG, LOC, 1, K )
	    IF( K .EQ. 0 ) GOTO 34
	    CALL PUTVAL( EMPCOD, K, 4 )
	    CALL PUTVAL( EMPDST, K, LOC )
	    DO 33 I1 = 1, LUNIT
		J = I1
		CALL GETVAL( ORG, J, IVAL )
		IF( IVAL .NE. K ) GOTO 33
		CALL GETVAL( SHIPTR, J, IVAL )
		IF( IVAL .NE. LOC ) GOTO 33
		CALL GETVAL( ORBIT, J, IVAL )
		IF( IVAL .NE. 1 ) GOTO 33
		CALL DELUNT( J )
33	    CONTINUE
34	    CONTINUE
	    DO 60 I1 = 1, 2
		LEVEL = I1
		CALL GETVAL( PLCORG, LOC, LEVEL, DORG )
		IF( DORG .EQ. 0 ) GOTO 61
		NUMOP(1) = 0
		NUMOP(2) = 0
		DO 40 J = 1, LUNIT
		    ENUM = J
		    CALL GETVAL( ORG, ENUM, TORG )
		    IF( TORG .EQ. 0 ) GOTO 40
		    CALL GETVAL( HMFLAG, ENUM, IVAL )
		    IF( IVAL .NE. 0 ) GOTO 40
		    CALL GETVAL( SHIPTR, ENUM, IVAL )
		    IF( IVAL .NE. LOC ) GOTO 40
		    CALL GETVAL( ORBIT, ENUM, IVAL )
		    IF( IVAL/3 + 1 .NE. LEVEL ) GOTO 40
		    IF( TORG .NE. DORG ) GOTO 35

		    IF( NUMOP(1) .GE. 50 ) GOTO 40
		    NUMOP(1) = NUMOP(1) + 1
		    TEAM(1,NUMOP(1)) = ENUM
		    GOTO 40

35		    CALL PUTVAL( EMPCOD, TORG, 3 )
		    CALL PUTVAL( EMPDST, TORG, LOC )
		    CALL PUTVAL( EMPINF, TORG, LEVEL )
		    IF( NUMOP(2) .GE. 50 ) GOTO 40
		    NUMOP(2) = NUMOP(2) + 1
		    TEAM(2,NUMOP(2)) = ENUM
40		CONTINUE

45		IF( NUMOP(2) .EQ. 0 ) GOTO 61
		CALL PUTVAL( EMPCOD, DORG, 3 )
		CALL PUTVAL( EMPDST, DORG, LOC )
		CALL PUTVAL( EMPINF, DORG, LEVEL )
		DO 60 J = 1, 2
		    DO 60 K = 1, NUMOP(J)
			ACT = TEAM(J,K)
			CALL GETVAL( TMTONX, ACT, IVAL )
			IF( IVAL .NE. 0 ) GOTO 60
			CALL GETVAL( POWDST, ACT, 3, 1, CURBEM )
			IF( CURBEM .EQ. 0 ) GOTO 60
			IF( K .LE. NUMOP(3-J) ) GOTO 54
			CALL GETVAL( PC, ACT, IVAL )
			IF( IVAL .NE. 0 ) GOTO 60
			PAS = TEAM(3-J,IRAN(NUMOP(3-J)))
			GOTO 56

54			PAS = TEAM( 3-J, K )

56			CALL GETVAL( ORG, PAS, IVAL )
			IF( IVAL .EQ. 0 ) GOTO 60
			CALL GETVAL( POWDST, PAS, 2, CURSHD )
			CHANCE=40*ALOG10(10.0*CURBEM/(CURSHD+0.001))+10
			IF( IRAN(100) .LT. CHANCE ) CALL DELUNT( PAS )
60	CONTINUE
61	CONTINUE

C***	LOOP THROUGH ALL UNITS AND EXECUTE THEIR PROGRAMS

	DO 100 I = 1, LUNIT
	    UNUM = I
	    CALL GETVAL( ORG, UNUM, PLAYER )
	    IF( PLAYER .EQ. 0 ) GOTO 100
	    CALL GETVAL( TYPE, UNUM, STYPE )
	    CALL GETVAL( SHIPTR, UNUM, LOC )
	    IF( STYPE .LT. 4 .OR. STYPE .EQ. 7 ) GOTO 65
	    CALL GETVAL( PRDTIM, UNUM, IVAL )
	    IF( IVAL .GT. 1 ) CALL ADDVAL( -1, -1 )
	    IF( IVAL .NE. 1 ) GOTO 65
	    IF( STYPE .EQ. 6 ) GOTO 62
	    CALL GETVAL( RES, UNUM, STYPE-3, IVAL )
	    IF( IVAL .GE. 63 ) GOTO 65
	    CALL ADDVAL( -1, 1 )
	    CALL GETVAL( RESTRN, LOC, STYPE-3, NPROD )
	    IF(IRAN(500).EQ.1.AND.NPROD.GT.0) CALL ADDVAL( -1, -1 )
	    IF(NPROD.GT.0) CALL PUTVAL( PRDTIM, UNUM, 793/NPROD )
	    IF(NPROD.EQ.0) CALL PUTVAL( PRDTIM, UNUM, 0 )
	    GOTO 65

62	    CALL GETVAL( RES, UNUM, 1, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 65
	    CALL GETVAL( RES, UNUM, 2, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 65
	    CALL GETVAL( RES, UNUM, 3, IVAL )
	    IF( IVAL .GE. 63 ) GOTO 65
	    CALL ADDVAL( -1, 1 )
	    CALL ADDVAL( RES, UNUM, 1, -1 )
	    CALL ADDVAL( RES, UNUM, 2, -1 )
	    CALL PUTVAL( PRDTIM, UNUM, 53 )

65	    IF( STYPE .EQ. 3 ) CALL ADDVAL( OPRIND, LOC, 1 )
	    CALL GETVAL( TMTONX, UNUM, IVAL )
	    IF( IVAL .LE. 2 ) CALL PUTVAL( HMFLAG, UNUM, 0 )
	    IF( IVAL .EQ. 0 ) GOTO 70
	    CALL ADDVAL( TMTONX, UNUM, -1 )
	    GOTO 100

70	    CALL GETVAL( WPROGR, UNUM, WP )
	    IF( WP .EQ. 0 ) GOTO 100
	    CALL GETVAL( LENPRG, WP, LEN )
	    CALL GETVAL( PC, UNUM, IPC )
	    IF( IPC .LE. 0 .OR. IPC .GT. LEN ) GOTO 75
	    CALL GETVAL( STRADR, WP, ADDR )
	    ADDR = ADDR + IPC - 1
	    CALL GETVAL( NVERB, ADDR, NV )
	    IF( NV .NE. 0 ) GOTO 80
75	    CALL PUTVAL( PC, UNUM, 0 )
	    GOTO 100

80	    CALL GETVAL( NCODE, ADDR, NC )
	    CALL GETVAL( NDEST, ADDR, ND )
	    CALL EXINS( UNUM, NV, NC, ND, LMOVE )
	    IF( .NOT. LMOVE ) GOTO 90

85	    IF( NV .NE. 9 ) CALL ADDVAL( PC, UNUM, 1 )
	    GOTO 100

90	    CALL GETVAL( ONERPC, UNUM, IVAL )
	    IF( IVAL .EQ. 63 ) GOTO 85
	    CALL PUTVAL( PC, UNUM, IVAL )
	    IF( IVAL .NE. 0 .OR. PLAYER .EQ. 0 ) GOTO 100
	    CALL PUTVAL( EMPCOD, PLAYER, 1 )
	    CALL PUTVAL( EMPDST, PLAYER, UNUM )
	    CALL PUTVAL( EMPC, PLAYER, IPC )
100	CONTINUE

	CALL PUTVAL( USEFUL, 7, 0 )
	CALL CTRAP
	    CALL CEASE
	PLAYER = ACPLAR
	RETURN
	END
	SUBROUTINE EXINS( SHIP, IVERB, ICODE, IDEST, LMOVE )

	IMPLICIT INTEGER ( A - Z )

	INTEGER MAXRES(7,4), TIMCRE(7), OREQIR(7), MENREQ(7), TYPSHD(7)
	LOGICAL LMOVE

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	DATA TYPSHD/12,10,7,3,3,2,15/
	DATA TIMCRE/213,402,150,204,201,203,803/
	DATA OREQIR/3,5,1,0,1,1,7/, MENREQ/1,1,3,0,0,0,5/
	DATA ((MAXRES(I,J),J=1,4),I=1,7)/15,10,4,3, 32,21,9,8,
     &0,0,0,0, 63,0,1,1, 0,63,1,1, 63,63,63,1, 63,63,63,63/

	LMOVE = .TRUE.
	CALL GETVAL( SHIPTR, SHIP, LOC )
	CALL GETVAL( ORBIT, SHIP, ORB )
	CALL GETVAL( TYPE, SHIP, STYPE )
	GOTO( 10, 10, 100, 300, 600, 700, 800, 850, 900, 910, 2100,
     &	     2100, 2100, 2100, 950 ) IVERB

C***	MOVE & JUMP

10	CALL GETVAL( POWDST, SHIP, 1, 1, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 2200
	CALL LEGTIM( LOC, ORB, IDEST, ICODE, LMOVE, MTIME )
	IF( .NOT. LMOVE ) RETURN
	CALL GETVAL( PTYPE, LOC, IVAL )
	IF( STYPE.GT.2 .OR. (IVERB.EQ.2 .AND.
     & ((ORB.NE.ICODE .AND. LOC.GT.NUMSTR) .OR. STYPE .NE. 2)) .OR.
     &	(ICODE.EQ.1 .AND. (LOC.LE.NUMSTR .OR. IVAL.EQ.3) ) ) GOTO 2200
	LEVEL = ORB/3 + 1
	CALL PUTVAL( SHIPTR, SHIP, IDEST )
	CALL PUTVAL( ORBIT, SHIP, ICODE )
	IF( LOC .EQ. IDEST .AND. LEVEL .EQ. ICODE/3 + 1 ) GOTO 30
	CALL GETVAL( PLCORG, LOC, LEVEL, IVAL )
	IF( IVAL .NE. PLAYER ) GOTO 20
	CALL ADDVAL( NUAPLC, LOC, LEVEL, -1 )
	CALL GETVAL( -1, IVAL )
	IF( IVAL .GT. 0 ) GOTO 20
	NEWORG = 0
	NUMSHP = 0
	DO 15 I = 1, LUNIT
	    J = I
	    CALL GETVAL( SHIPTR, J, IVAL )
	    IF( IVAL .NE. LOC ) GOTO 15
	    CALL GETVAL( ORBIT, J, IVAL )
	    IF( IVAL/3+1 .NE. LEVEL ) GOTO 15
	    CALL GETVAL( ORG, J, K )
	    IF( K.EQ.0 .OR. (NEWORG.NE.0 .AND. NEWORG.NE.K) ) GOTO 15
	    NEWORG = K
	    NUMSHP = NUMSHP + 1
15	CONTINUE
	CALL PUTVAL( PLCORG, LOC, LEVEL, NEWORG )
	CALL PUTVAL( NUAPLC, LOC, LEVEL, NUMSHP )

20	CALL GETVAL( PLCORG, IDEST, ICODE/3+1, IVAL )
	IF( IVAL .NE. 0 .AND. IVAL .NE. PLAYER ) GOTO 30
	CALL PUTVAL( -1, PLAYER )
	CALL ADDVAL( NUAPLC, IDEST, ICODE/3+1, 1 )
30	IF( IVERB .NE. 2 ) GOTO 35
	MTIME = MTIME / 764529
	CALL PUTVAL( HMFLAG, SHIP, 1 )
	GOTO 2000

35	CALL PUTVAL( HMFLAG, SHIP, 2 )
	CALL GETVAL( POWDST, SHIP, 1, 1, IVAL )
	MTIME = MTIME / IVAL
	GOTO 2000

C***	CREATE

100	IF( ORB .NE. 1 ) GOTO 2200
	IF(STYPE.EQ.1.AND.(ICODE.LT.3.OR.ICODE.GT.6)) GOTO 2200
	IF(STYPE.EQ.2.AND.ICODE.LE.3) GOTO 2200
	IF(STYPE.GT.2.AND.STYPE.LT.7) GOTO 2200
	IF(STYPE.EQ.7.AND.ICODE.GT.3) GOTO 2200
	IF( ICODE .NE. 4 .AND. ICODE .NE. 5 ) GOTO 105
	CALL GETVAL( RESTRN, LOC, ICODE-3, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 2200
105	CALL GETVAL( RES, SHIP, 1, IVAL )
	IF( OREQIR(ICODE) .GT. IVAL ) GOTO 2200
	CALL GETVAL( RES, SHIP, 4, IVAL )
	IF( MENREQ(ICODE) .GT. IVAL ) GOTO 2200
	IF( IDEST .EQ. 0 ) GOTO 107
	IF( IDEST .GT. LUNIT ) GOTO 2200
	CALL GETVAL( ORG, IDEST, IVAL )
	IF( IVAL .NE. PLAYER ) GOTO 2200
	CALL GETVAL( WPROGR, IDEST, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 2200
107	CALL ADDUNT( LOC, ICODE, I, LMOVE )
	IF( .NOT. LMOVE ) GOTO 2200
	CALL ADDVAL( RES, SHIP, 1, -OREQIR(ICODE) )
	CALL ADDVAL( RES, SHIP, 4, -MENREQ(ICODE) )
	MTIME = TIMCRE(ICODE)
	CALL PUTVAL( TMTONX, I, MTIME )
	IF( IDEST .EQ. 0 ) GOTO 2000
	CALL ADDVAL( NUMUSR, IVAL, 1 )
	CALL PUTVAL( WPROGR, I, IVAL )
	CALL PUTVAL( PC, I, 1 )
	GOTO 2000

C***	LOAD ON/FROM

300	ITYPE = MOD( IDEST/(2^15), 4 ) + 1
	IFT = IDEST/(2^17)
	IFROM = SHIP
	ITO = MOD( IDEST, 2^15 )
	IF( ITO .EQ. 0 ) GOTO 350
	IF( ITO .LE. 0 .OR. ITO .GT. LUNIT ) GOTO 2200
	CALL GETVAL( ORG, ITO, IVAL )
	IF( IVAL .NE. PLAYER ) GOTO 2200
	CALL GETVAL( SHIPTR, ITO, IVAL )
	IF( IVAL .NE. LOC ) GOTO 2200
	CALL GETVAL( ORBIT, ITO, IVAL )
	IF( IVAL .NE. ORB ) GOTO 2200

	IF( IFT .EQ. 0 ) GOTO 305
	IFROM = ITO
	ITO = SHIP

305	CALL GETVAL( RES, IFROM, ITYPE, IVAL )
	IF( IVAL .LT. ICODE ) GOTO 2200
	CALL GETVAL( TYPE, ITO, STYPE )
	CALL GETVAL( RES, ITO, ITYPE, IVAL )
	IF( MAXRES( STYPE, ITYPE ) - IVAL .LT. ICODE ) GOTO 2200
	CALL ADDVAL( -1, ICODE )
	CALL ADDVAL( RES, IFROM, ITYPE, -ICODE )
	MTIME = ORB*IVERB*ICODE
	GOTO 2000

C***	LOAD MEN

350	IF( ITYPE .NE. 4 ) GOTO 2200
	CALL GETVAL( RES, SHIP, 4, IVAL )
	IF( MAXRES( STYPE, ITYPE ) - IVAL .LT. ICODE ) GOTO 2200
	IF( ORB .NE. 1 ) GOTO 2200
	CALL GETVAL( POP, LOC, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 2200
	CALL ADDVAL( RES, SHIP, 4, ICODE )
	MTIME = ICODE*7
	GOTO 2000

C***	TACTIC

600	IVAL = IDEST
	J = 0
	DO 605 I = 1, 3
	    J = J + MOD( IVAL, 32 )
	    IVAL = IVAL / 32
605	CONTINUE
	CALL GETVAL( POWER, SHIP, IVAL )
	IF( IVAL .LT. J ) GOTO 2200
	IVAL = IDEST
	DO 610 I = 3, 1, -1
	    CALL GETVAL( POWDST, SHIP, I+0, 2, J )
	    CALL PUTVAL( POWDST, SHIP, I+0, 1, MIN0(MOD(IVAL,32),J) )
	    IVAL = IVAL / 32
610	CONTINUE
	GOTO 2100

C***	INFORM

700	CALL PUTVAL( EMPCOD, PLAYER, 2 )
	CALL PUTVAL( EMPC, PLAYER, ICODE )
	CALL PUTVAL( EMPDST, PLAYER, SHIP )
	CALL PUTVAL( EMPINF, PLAYER, IDEST )
	GOTO 2100

C***	SKIP

800	CALL GETVAL( RES, SHIP, ICODE, NRES )
	CMP = IDEST/(2^15)
	NCOMP = MOD( IDEST, 2^15 )
	GOTO( 810, 812, 814, 816, 818, 820 ) CMP

810	IF( NRES .LT. NCOMP ) GOTO 830
	GOTO 2100
812	IF( NRES .LE. NCOMP ) GOTO 830
	GOTO 2100
814	IF( NRES .EQ. NCOMP ) GOTO 830
	GOTO 2100
816	IF( NRES .NE. NCOMP ) GOTO 830
	GOTO 2100
818	IF( NRES .GT. NCOMP ) GOTO 830
	GOTO 2100
820	IF( NRES .GE. NCOMP ) GOTO 830
	GOTO 2100

830	CALL ADDVAL( PC, SHIP, 1 )
	GOTO 2100

C***	ERROR

850	CALL PUTVAL( ONERPC, SHIP, IDEST )
	GOTO 2100

C***	GOTO

900	CALL PUTVAL( PC, SHIP, IDEST )
	GOTO 2100

C***	BUILD COMMAND

910	CALL GETVAL( RES, SHIP, 3, IVAL )
	IF( IVAL .LT. IDEST ) GOTO 2200
	IF( ICODE .LT. 4 ) CALL GETVAL( POWDST, SHIP, ICODE, 2, IVAL )
	IF( ICODE .EQ. 4 ) CALL GETVAL( POWER, SHIP, IVAL )
	IF( IVAL+IDEST .GT. 31 ) GOTO 2200
	CALL ADDVAL( -1, IDEST )
	CALL ADDVAL( RES, SHIP, 3, -IDEST )
	MTIME = 37*IDEST*ICODE
	GOTO 2000

C***	NO ARGUMENT COMMANDS

950	GOTO( 960, 970, 975, 990 ) ICODE

C***	RANDOM JUMP

960	IF( ORB .EQ. 3 ) GOTO 962
	IVERB = 2
	IF( LOC .GT. NUMSTR ) IVERB = 1
	ICODE = ORB + 1
	IDEST = LOC
	GOTO 10

962	IVERB = 2
	ICODE = 3
	IF( LOC .GT. NUMSTR ) GOTO 966
964	I = IRAN( 5 )
	CALL GETVAL( DEST, LOC, I, IDEST )
	IF( IDEST .EQ. 0 ) GOTO 964
	GOTO 10

966	CALL GETVAL( WSTAR, LOC, S )
	CALL GETVAL( WPLAN, LOC, P )
	CALL GETVAL( WMOON, LOC, M )
	IDEST = LOC
968	IDEST = IDEST - 1
	CALL GETVAL( WSTAR, IDEST, IVAL )
	IF( IVAL .NE. S ) GOTO 968
	CALL GETVAL( WPLAN, IDEST, IVAL )
	IF( IVAL .NE. 0 .AND. IVAL .NE. P ) GOTO 968
	CALL GETVAL( WMOON, IDEST, IVAL )
	IF( IVAL .NE. 0 ) GOTO 968
	GOTO 10

C***	PRODUCE

970	IF( STYPE .LT. 4 .OR. STYPE .EQ. 7 ) GOTO 2200
	CALL GETVAL( PRDTIM, SHIP, IVAL )
	IF( IVAL .NE. 0 ) GOTO 2200
	CALL PUTVAL( -1, 793 )
	GOTO 2100

C***	CEASE PRODUCTION

975	CALL GETVAL( PRDTIM, SHIP, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 2200
	CALL PUTVAL( -1, 0 )
	GOTO 2100

C***	SELF DESTRUCT

990	CALL DELUNT( SHIP )
	GOTO 2100

2000	CONTINUE
	CALL PUTVAL( TMTONX, SHIP, MTIME )
2100	RETURN

2200	LMOVE = .FALSE.
	RETURN
	END
	SUBROUTINE LEGTIM( CL, CO, NL, NO, LMOVE, MTIME )

	IMPLICIT INTEGER ( A - Z )
	LOGICAL LMOVE

	INTEGER PAR( 19 ), PN( 6 )

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	LMOVE = .FALSE.
	MTIME = 0
	CALL GETVAL( WSTAR, CL, CURS )
	CALL GETVAL( WPLAN, CL, CURP )
	CALL GETVAL( WMOON, CL, CURM )
	CALL GETVAL( WSTAR, NL, NEWS )
	CALL GETVAL( WPLAN, NL, NEWP )
	CALL GETVAL( WMOON, NL, NEWM )
	IF( CO .NE. NO ) GOTO 100
	IF( NO .NE. 3 ) RETURN
	IF(NEWS.NE.CURS.AND.(NEWP.NE.CURP.OR.NEWM.NE.CURM)) RETURN
	IF(NEWP.NE.CURP.AND.NEWM.NE.CURM) RETURN
	IF( NEWS .EQ. CURS ) GOTO 200
	DO 50 I = 1, 5
	    CALL GETVAL( DEST, CURS, I+0, IVAL )
	    IF( IVAL .NE. NEWS ) GOTO 50
	    CALL GETVAL( TIME, CURS, I+0, MTIME )
	    MTIME = MTIME*764529
	    GOTO 200
50	CONTINUE
	RETURN

100	IF(NEWS.NE.CURS .OR. NEWP.NE.CURP .OR. NEWM.NE.CURM .OR.
     &	    IABS(NO-CO).GT.1) RETURN
	OPTR = 0
	IF( NEWM .EQ. 0 ) OPTR = 1
	IF( NEWP .EQ. 0 ) OPTR = 2
	IF( NO+CO .GT. 3 ) OPTR = OPTR + 1
	MTIME = MTIME + 13^OPTR

200	IF( NEWP .NE. CURP ) MTIME = MTIME + (NEWP + CURP)*3167
	IF( NEWM .NE. CURM ) MTIME = MTIME + (NEWM + CURM)*98
	LMOVE = .TRUE.
	RETURN
	END
	SUBROUTINE ADDUNT( LOC, STYPE, SHPNUM, LMOVE )

	IMPLICIT INTEGER ( A - Z )

	INTEGER TYPOWR(7), MAXPOW(7,3)
	LOGICAL LMOVE

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	DATA TYPOWR/7,4,2,1,1,1,7/
	DATA ((MAXPOW(I,J),I=1,7),J=1,3)/
     & 7,4,2,1,1,1,7,	12,10,7,3,3,2,15,	5,4,2,1,1,0,7/

	LMOVE = .FALSE.
	CALL GETVAL( USEFUL, 5, LUNIT )
	IF( LUNIT .GE. MAXUNI ) RETURN
	CALL GETVAL( NOFUNI, PLAYER, IVAL )
	IF( IVAL .GE. MAXPLA ) RETURN
	CALL ADDVAL( -1, 1 )
	IF( LUNIT .LE. 1 ) GOTO 101
	DO 100 SHPNUM = 1, LUNIT-1
	    CALL GETVAL( ORG, SHPNUM+0, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 200
100	CONTINUE
101	CONTINUE
	LUNIT = LUNIT + 1
	CALL PUTVAL( USEFUL, 5, LUNIT )
	SHPNUM = LUNIT
200	CALL PUTVAL( ORG, SHPNUM, PLAYER )
	DO 300 I = 1, 4
	    CALL PUTVAL( RES, SHPNUM, I+0, 0 )
300	CONTINUE
	CALL PUTVAL( TYPE, SHPNUM, STYPE )
	CALL PUTVAL( SHIPTR, SHPNUM, LOC )
	CALL PUTVAL( ORBIT, SHPNUM, 1 )
	CALL PUTVAL( HMFLAG, SHPNUM, 0 )
	CALL PUTVAL( WPROGR, SHPNUM, 0 )
	CALL PUTVAL( PC, SHPNUM, 0 )
	CALL PUTVAL( ONERPC, SHPNUM, 0 )
	CALL PUTVAL( TMTONX, SHPNUM, 0 )
	CALL PUTVAL( PRDTIM, SHPNUM, 0 )
	CALL PUTVAL( POWER, SHPNUM, TYPOWR(STYPE) )
	DO 400 I = 1, 3
	    CALL PUTVAL( POWDST, SHPNUM, I+0, 2, MAXPOW(STYPE,I) )
	    CALL PUTVAL( POWDST, SHPNUM, I+0, 1, 0 )
400	CONTINUE
	CALL GETVAL( PLCORG, LOC, 1, IVAL )
	IF( IVAL .EQ. 0 ) CALL PUTVAL( -1, PLAYER )
	IF(IVAL.EQ.PLAYER.OR.IVAL.EQ.0) CALL ADDVAL(NUAPLC,LOC,1,1)
	LMOVE = .TRUE.
	RETURN
	END
	SUBROUTINE DELUNT( SHPNUM )

	IMPLICIT INTEGER ( A - Z )

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	CALL GETVAL( USEFUL, 5, LUNIT )
	CALL GETVAL( ORG, SHPNUM, DPLAYR )
	CALL PUTVAL( -1, 0 )
	CALL ADDVAL( NOFUNI, DPLAYR, -1 )
	CALL GETVAL( WPROGR, SHPNUM, IVAL )
	IF( IVAL .NE. 0 ) CALL ADDVAL( NUMUSR, IVAL, -1 )
	CALL GETVAL( SHIPTR, SHPNUM, LOC )
	CALL GETVAL( ORBIT, SHPNUM, ORB )
	LEVEL = ORB/3 + 1
	CALL GETVAL( PLCORG, LOC, LEVEL, IVAL )
	IF( IVAL .NE. DPLAYR ) GOTO 100
	CALL GETVAL( NUAPLC, LOC, LEVEL, IVAL )
	CALL ADDVAL( -1, -1 )
	IF( IVAL .GT. 1 ) GOTO 100
	NEWORG = 0
	NUMSHP = 0
	DO 50 I = 1, LUNIT
	    J = I
	    CALL GETVAL( SHIPTR, J, IVAL )
	    IF( IVAL .NE. LOC ) GOTO 50
	    CALL GETVAL( ORBIT, J, IVAL )
	    IF( IVAL/3 + 1 .NE. LEVEL ) GOTO 50
	    CALL GETVAL( ORG, J, K )
	    IF( K.EQ.0 .OR. (NEWORG.NE.0 .AND. K.NE.NEWORG) ) GOTO 50
	    NEWORG = K
	    NUMSHP = NUMSHP + 1
50	CONTINUE
	CALL PUTVAL( PLCORG, LOC, LEVEL, NEWORG )
	CALL PUTVAL( NUAPLC, LOC, LEVEL, NUMSHP )

100	IF( LUNIT .GT. SHPNUM ) RETURN
	LUNIT = LUNIT - 1
	IF( LUNIT .LE. 0 ) GOTO 150
	CALL GETVAL( ORG, LUNIT, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 100
150	CALL PUTVAL( USEFUL, 5, LUNIT )
	RETURN
	END
	SUBROUTINE DISENS( NEW, SHIP, XTR )

	IMPLICIT INTEGER ( A - Z )

	INTEGER NEWARA(13,13), OLDARA(13,13), TC(7), LETTER(6)
	REAL CLASS, ZMASS, ZRAD, ZLUMEN, TEMP
	INTEGER THREAT, TWOATS, ONESTR, THRSHR, ONEDOT, THRSTR
	LOGICAL NEW, XTR, LINE
	INTEGER BLDTOK(3)

C	MODIFIED TO NOT DEPEND ON 36 BIT WORD WITH 5 CHARS IN IT
C	INTEGER COLOR(6,2)

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA

C	MODIFIED TO NOT DEPEND ON 36 BIT WORD WITH 5 CHARS IN IT
C	DATA ((COLOR(I,J),J=1,2),I=1,6)/'DEEP-BLUE ','BLUE-WHITE',
C     & 'WHITE     ','YELLOW    ','LIGHT-RED ','DEEP-RED  '/

	DATA TC/'S','H','G','O','F','L','P'/
	DATA LETTER/'B','A','F','G','K','M'/

	IF( THREAT .NE. 0 ) GOTO 5
	THREAT = 1
	TWOATS = 2
	ONESTR = 3
	THRSHR = 4
	ONEDOT = 5
	THRSTR = 6
5	CONTINUE

	CALL GETVAL( HMFLAG, SHIP, HYPMOV )
	IF( .NOT. XTR ) GOTO 10
	IF( .NOT. NEW ) RETURN
	CALL CURSOR( 20, 12 )
	CALL PCOLOR( ICLLBL )
	CALL STRING( '*** ^E')
	CALL PUNIT( SHIP )
	IF( HYPMOV .EQ. 1 ) CALL STRING('in hyperspace ***^E')
	IF( HYPMOV .EQ. 2 ) CALL STRING('in transit ***^E')
	CALL PCOLOR( ICLWHI )
	RETURN

10	CALL GETVAL( SHIPTR, SHIP, LOC )
	CALL GETVAL( ORBIT, SHIP, ORB )
	CALL GETVAL( PTYPE, LOC, ITYPE )
	IATMOS = ICLBLA
	IF( ITYPE .EQ. 1 .AND. ORB .EQ. 1 ) IATMOS = ICLLBL
	IF( .NOT. NEW .AND. LOC .EQ. OLOC .AND. ORB .EQ. OORB ) GOTO 50
	OLOC = LOC
	OORB = ORB
	CALL CURSOR( 1, 24 )
	CALL STRING('Sensor scan from ^E')
	CALL PUNIT( SHIP )
	CALL STRING(' at ^E')
	CALL PLOC( LOC, ORB )
50	IF( .NOT. NEW ) GOTO 1000
	CALL GETVAL( WPLAN, LOC, PLANUM )
	CALL GETVAL( WMOON, LOC, MOONUM )
	CALL STRING('^M^J^JCat. code: ^E')
	CALL NUMBER( LOC )
	CALL CHROUT('/')
	IF( LOC .GT. NUMSTR ) GOTO 200
	CALL GETVAL( WPLACE, LOC, IVAL )
	CALL NUMBER( IVAL )
	CALL STRING('^M^JSpectral class: ^E')
	CLASS = IQRAN(LOC,60) - 1
	CALL CHROUT( LETTER(IFIX(CLASS/10.0)+1) )
	CALL NUMBER( MOD(IFIX(CLASS),10) )
	CALL STRING('.^M^JMass: ^E')
	ZMASS = -4.9775*10.0^25*(CLASS-20)/30.0 + 2.9855*10.0^27
	POWERT = ALOG10( ZMASS )
	CALL NUMBER( ZMASS/(10.0^POWERT), 0, 10, 3 )
	CALL CHROUT('E')
	CALL NUMBER( POWERT )
	CALL STRING(' MT.^M^JRadius: ^E')
	ZRAD = -15660*(CLASS-20)/30.0 + 974400
	CALL NUMBER( ZRAD, 0, 10, 3 )
	CALL STRING(' km.^M^JDensity: ^E')
	CALL NUMBER( 2.39*(CLASS-20)/30.0 + 0.791, 0, 10, 3 )
	CALL STRING(' G/CM3.^M^JLuminosity: ^E')
	ZLUMEN = -4.458*(CLASS-20)/30.0 + 4.78
	CALL NUMBER( ZLUMEN, 0, 10, 3 )
	CALL STRING(' AL.^M^JSurface temperature: ^E')
	TEMP = -3340*(CLASS-20)/30.0 + 7060
	CALL NUMBER( TEMP, 0, 10, 3 )
	CALL STRING('K.^M^JWave length: ^E')
	CALL NUMBER( 4100 + 351*CLASS, 0, 10, 2 )
	CALL STRING(' microns.^M^JColor: ^E')

C	MODIFIED TO NOT DEPEND ON 36 BIT WORD WITH 5 CHARS IN IT
	GOTO( 61, 62, 63, 64, 65, 66 ) IFIX(CLASS/10)+1
61	CALL STRING('deep-blue^E')
	ISTARC = ICLDBL
	GOTO 100
62	CALL STRING('blue-white^E')
	ISTARC = ICLLBL
	GOTO 100
63	CALL STRING('white^E')
	ISTARC = ICLWHI
	GOTO 100
64	CALL STRING('yellow^E')
	ISTARC = ICLYEL
	GOTO 100
65	CALL STRING('light-red^E')
	ISTARC = ICLPUR
	GOTO 100
66	CALL STRING('deep-red^E')
	ISTARC = ICLRED
	GOTO 100
C	CALL STRING( COLOR(CLASS/10+1,1), 5, 5 )
C	CALL STRING( COLOR(CLASS/10+1,2), 5, 5 )

100	CALL STRING('^M^JPolar spin: ^E')
	CALL NUMBER( IQRAN(LOC,4975)+10 )
	CALL STRING(' days/rot.^M^JDegrees off ecliptic: ^E')
	CALL NUMBER( IQRAN(LOC,91)-1 )
	CALL STRING('^M^JSolar activity: ^E')
	CALL NUMBER( IQRAN(LOC,101)-1 )
	CALL CHROUT('%')
	GOTO 1000

200	CALL NUMBER( (PLANUM*1000 + MOONUM*10 + ITYPE)/10.0, 0, 10, 3 )
	IVAL = IQRAN(LOC,2724)
	ZRAD = IVAL + 4969
	IF( MOONUM .NE. 0 ) ZRAD = ZRAD / 6
	IF( ITYPE .EQ. 3 ) ZRAD = ZRAD * IQRAN(LOC,50)
	CALL STRING('^M^JMass: ^E')
	ZMASS = 1.4045*10.0^22 + IVAL*4.2783*10.0^18
	IF( MOONUM .NE. 0 ) ZMASS = ZMASS / 123
	POWERT = ALOG10( ZMASS )
	CALL NUMBER( ZMASS/(10.0^POWERT), 0, 10, 3 )
	CALL CHROUT( 'E' )
	CALL NUMBER( POWERT )
	CALL STRING(' MT.^M^JRadius: ^E')
	CALL NUMBER( ZRAD, 0, 10, 3 )
	CALL STRING(' km.^M^JDistance from primary: ^E')
	IF( MOONUM .NE. 0 ) GOTO 210
	ZRAD = 5.79*10.0^7 + IQRAN(LOC,1234567)
	IF( PLANUM .GT. 1 ) ZRAD = ZRAD + 4.46*10.0^7*(2.0^PLANUM)
	GOTO 220
210	ZRAD = IQRAN(LOC,9862)*100.0
220	POWERT = ALOG10( ZRAD )
	CALL NUMBER( ZRAD/(10.0^POWERT), 0, 10, 3 )
	CALL CHROUT('E')
	CALL NUMBER( POWERT )
	CALL STRING(' km.^M^JDays/orbit: ^E')
	IF(MOONUM.EQ.0)CALL NUMBER( 365.0*(ZRAD/(1.495*10.0^8)+0.0)^2,
     & 0,10,3 )
	IF(MOONUM.NE.0)CALL NUMBER( 28.0*(ZRAD/(3.844*10.0^5)+0.0)^2,
     & 0,10,3 )
	CALL STRING('^M^JPolar spin: ^E')
	CALL NUMBER( IQRAN(LOC,2561)/100.0, 0, 10, 2 )
	CALL STRING(' days/rot.^M^JDegrees spin off ecliptic: ^E')
	CALL NUMBER( IQRAN(LOC+1,91)-1 )
	CALL STRING('^M^JDegrees off ecliptic: ^E')
	CALL NUMBER( IQRAN(LOC+2,91)-1 )
	CALL STRING('^M^JAtm: ^E')
	GOTO( 222, 223, 224 ) ITYPE
222	I1 = IQRAN( LOC, 10 ) + 15
	CALL NUMBER( I1 )
	CALL STRING('%O2, ^E')
	I2 = IQRAN( LOC+1, 25 ) + 49
	CALL NUMBER( I2 )
	CALL STRING('%N2, ^E')
	I3 = IQRAN( LOC+2, 100-I1-I2 )
	CALL NUMBER( I3 )
	CALL STRING('%CO2, ^E')
	CALL NUMBER( 100-I1-I2-I3 )
	GOTO 225

223	IF( ZMASS .LT. 10.0^21 ) CALL STRING('None^E')
	IF( ZMASS .LT. 10.0^21 ) GOTO 226
224	I1 = IQRAN( LOC, 90 )
	CALL NUMBER( I1 )
	CALL STRING('%H2, ^E')
	I2 = IQRAN( LOC+1, 100-I1 )
	CALL NUMBER( I2 )
	CALL STRING('%HE, ^E')
	CALL NUMBER( 100-I1-I2 )

225	CALL STRING('%Trace^E')
226	CALL STRING('^M^JPopulation:        mil.^M^J
     &Ore density:^M^JFood density:^M^JHunger:^E')

1000	IF( PLANUM .EQ. 0 ) GOTO 1100
	CALL GETVAL( POP, LOC, IVAL )
	IF( IVAL .EQ. OLDPOP .AND. .NOT. NEW ) GOTO 1005
	CALL CURSOR( 13, 13 )
	CALL NUMBER( IVAL, 6 )
	OLDPOP = IVAL
1005	CALL GETVAL( RESTRN, LOC, 1, IVAL )
	IF( IVAL .EQ. OLDORE .AND. .NOT. NEW ) GOTO 1010
	CALL CURSOR( 14, 12 )
	CALL NUMBER( IVAL, 2 )
	OLDORE = IVAL
1010	CALL GETVAL( RESTRN, LOC, 2, IVAL )
	IF( IVAL .EQ. OLDFOD .AND. .NOT. NEW ) GOTO 1020
	CALL CURSOR( 15, 11 )
	CALL NUMBER( IVAL, 2 )
	OLDFOD = IVAL
1020	CALL GETVAL( HUNGER, LOC, IVAL )
	IF( IVAL .EQ. OLDHUN .AND. .NOT. NEW ) GOTO 1030
	CALL CURSOR( 9, 10 )
	CALL NUMBER( IVAL, 8 )
	OLDHUN = IVAL
1030	DO 1070 J = 1, 3
	    IF( ORB .LT. J ) GOTO 1070
	    DO 1040 I = ORB+J*2-2, 16-ORB-J*2
		NEWARA(I,J) = THRSHR
1040	    CONTINUE
1070	CONTINUE
	IF( MOONUM .EQ. 0 ) GOTO 1201

	NEWARA( 12, 13 ) = THREAT
	NEWARA( 13, 13 ) = THREAT
	NEWARA( 12, 12 ) = THREAT
	NEWARA( 13, 12 ) = THREAT
	NEWARA( 12, 11 ) = TWOAT
	NEWARA( 13, 11 ) = THREAT
	NEWARA( 13, 10 ) = TWOAT
	GOTO 1201

1100	IF( ORB .EQ. 3 ) NEWARA( 7, 7 ) = ONESTR
	IF( ORB .EQ. 3 ) GOTO 1201
	DO 1200 I = 1, 13
	    DO 1200 J = 1, 13
		NEWARA(I,J) = THRSTR
1200	CONTINUE
1201	CONTINUE

	IF( LOC .LE. NUMSTR ) GOTO 1246
	DO 1245 I = 1, LUNIT
	    J = I
	    CALL GETVAL( ORG, J, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 1245
	    CALL GETVAL( SHIPTR, J, IVAL )
	    IF( IVAL .NE. LOC .OR. J .EQ. SHIP ) GOTO 1245
	    CALL GETVAL( HMFLAG, J, IVAL )
	    IF( IVAL .NE. 0 ) GOTO 1245
	    CALL GETVAL( ORBIT, J, SORB )
	    I3 = 0
	    IF( SORB .NE. 1 ) GOTO 1230
1220	    I3 = I3 + 1
	    I2 = 0
	    I1 = IQRAN( LOC+J+I3, 13 )
1225	    I2 = I2 + 1
	    IF( NEWARA(I1,I2) .EQ. THRSHR ) GOTO 1225
	    IF( IQRAN( LOC+J-I3, 25 ) .LT. 4 ) GOTO 1245
	    IF( NEWARA(I1,I2) .NE. 0 ) GOTO 1220
	    GOTO 1240

1230	    I3 = I3 + 1
	    I1 = IQRAN( LOC+J+I3, 13 )
	    I2 = IQRAN( LOC-J+I3, 4 ) + SORB^2
	    IF( IQRAN( LOC+J-I3, 25 ) .LT. 2 ) GOTO 1245
	    IF( NEWARA(I1,I2) .NE. 0 ) GOTO 1230

1240	    CALL GETVAL( TYPE, J, STYPE )
	    CALL GETVAL( ORG, J, SORG )
	    NEWARA(I1,I2) = -(STYPE * 10000 + SORG)

1245	CONTINUE
1246	CONTINUE

	DO 1247 IVAL = 1, 12
	    I = IQRAN(LOC+IVAL*ORB,13)
	    J = IQRAN(LOC-IVAL*ORB,13)
	    IF( NEWARA(I,J) .EQ. 0 ) NEWARA(I,J) = ONEDOT
1247	CONTINUE

	IF( .NOT. NEW ) GOTO 1249
	CALL PBACK( ICLWHI )
	CALL CURSOR( 39, 22 )
	CALL CHROUT('/')
	CALL REPEAT('-',39)
	CALL CHROUT('\')
	CALL CURSOR( 39, 8 )
	CALL CHROUT('\')
	CALL REPEAT('-',39)
	CALL CHROUT('/')
	DO 1248 I = 1, 13
	    CALL CURSOR( 39, I+8 )
	    CALL CHROUT('|')
	    CALL CURSOR( 79, I+8 )
	    CALL CHROUT('|')
1248	CONTINUE
	CALL PBACK(ICLBLA)

1249	DO 1300 J = 1, 13
	    LINE = .FALSE.
	    DO 1300 I = 1, 13
		IF( NEW ) OLDARA(I,J) = -1
		IV = NEWARA(I,J)
		IF( IV.EQ.OLDARA(I,J) .AND. IATMOS.EQ.NATMOS
     &		    .AND. SHIP.EQ.OSHIP ) GOTO 1269
		IF( .NOT. LINE )CALL CURSOR( 37+3*I, J+8 )
		IF( IV .NE. 0 ) GOTO 1250
		CALL PBACK( IATMOS )
		CALL STRING('   ^E')
		GOTO 1258
1250		IF( IV .NE. THREAT ) GOTO 1251
		CALL PCOLOR( ICLYEL )
		CALL PBACK( ICLYEL )
		CALL STRING('@@@^E')
		GOTO 1258
1251		IF( IV .NE. TWOATS ) GOTO 1252
		CALL PCOLOR( ICLYEL )
		CALL PBACK( IATMOS )
		CALL CHROUT(' ')
		CALL PBACK( ICLYEL )
		CALL STRING('@@^E')
		GOTO 1258
1252		IF( IV .NE. ONESTR ) GOTO 1253
		CALL PCOLOR( ISTARC )
		CALL PBACK( IATMOS )
		CALL STRING(' * ^E')
		GOTO 1258
1253		IF( IV .NE. THRSHR ) GOTO 1254
		CALL PCOLOR( ICLGRE )
		CALL PBACK( ICLGRE )
		CALL STRING('###^E')
		GOTO 1258
1254		IF( IV .NE. ONEDOT ) GOTO 1255
		CALL PCOLOR( ICLWHI )
		CALL PBACK( IATMOS )
		CALL STRING(' . ^E')
		GOTO 1258
1255		IF( IV .NE. THRSTR ) GOTO 1256
		CALL PCOLOR( ISTARC )
		CALL PBACK( ICLWHI )
		CALL STRING('###^E')
		GOTO 1258
1256		CALL PBACK( IATMOS )
		SPLAYR = MOD( -IV, 10000 )
		IF( SPLAYR.EQ.PLAYER .AND. IATMOS .NE. ICLBLA )
     &		    CALL PCOLOR( ICLBLA )
		IF( SPLAYR.EQ.PLAYER .AND. IATMOS .EQ. ICLBLA )
     &		    CALL PCOLOR( ICLWHI )
		IF( SPLAYR .NE. PLAYER ) CALL PCOLOR( ICLRED )
		CALL CHROUT( TC( (-IV)/10000 ) )
		CALL NUMBER( SPLAYR, -2, 10 )
1258		OLDARA(I,J) = NEWARA(I,J)
		LINE = .TRUE.
		GOTO 1270

1269		LINE = .FALSE.

1270		NEWARA(I,J) = 0

1300	CONTINUE
	NATMOS = IATMOS
	OSHIP = SHIP
	CALL PCOLOR( ICLWHI )
	CALL PBACK( ICLBLA )
	RETURN
	END
	INTEGER FUNCTION IQRAN( SEED, RANGE )
C	TWEAKED TO BE 32 BIT SAFE

	INTEGER SEED, RANGE, I

	IQRAN = SEED
C	DO 10 I = 1, 9
	DO 10 I = 1, 8
	    IQRAN = SHIFT( IQRAN, 4 )
	    IQRAN = IQRAN + SEED
10	CONTINUE
C	IQRAN = IQRAN .XOR. "761345243571
	IQRAN = IQRAN .XOR. 626693556
	IQRAN = MOD( IABS(IQRAN), RANGE ) + 1
	RETURN
	END
	SUBROUTINE PUNIT( SHPNUM )

	IMPLICIT INTEGER ( A - Z )

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	CALL CHROUT('#')
	CALL NUMBER( SHPNUM )
	CALL GETVAL( TYPE, SHPNUM, STYPE )
	CALL PUTYPE( STYPE )

	RETURN
	END
	SUBROUTINE PUTYPE( STYPE )

	IMPLICIT INTEGER ( A - Z )

	INTEGER UNAME( 4, 7 )

C	MODIFIED TO NOT DEPEND ON 36 BIT WORD WITH 5 CHARS IN IT
C	DATA ((UNAME(J,I),J=1,4),I=1,7)/' SPACESHIP          ',
C     &' HYPERSHIP          ',' GROUND UNIT        ',
C     &' ORE PROCESSOR      ',' FOOD PROCESSOR     ',
C     &' LUXURY PROCESSOR   ',' PORT               '/
C	CALL STRING( UNAME(1,STYPE), 5, 17 )
	
	IF( STYPE .EQ. 1 ) CALL STRING(' Spaceship       ^E')
	IF( STYPE .EQ. 2 ) CALL STRING(' Hypership       ^E')
	IF( STYPE .EQ. 3 ) CALL STRING(' Ground unit     ^E')
	IF( STYPE .EQ. 4 ) CALL STRING(' Ore Processor   ^E')
	IF( STYPE .EQ. 5 ) CALL STRING(' Food Processor  ^E')
	IF( STYPE .EQ. 6 ) CALL STRING(' Luxury Processor^E')
	IF( STYPE .EQ. 7 ) CALL STRING(' Port            ^E')
	RETURN
	END
	SUBROUTINE PLOC( LOC, ORB )

	IMPLICIT INTEGER ( A - Z )

	INTEGER STNAME(2)

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	CALL GETVAL( WSTAR, LOC, S )
	CALL GETVAL( NAME, S, 1, STNAME(1) )
	CALL GETVAL( NAME, S, 2, STNAME(2) )
	CALL STRING( STNAME, 6, 12 )
	CALL GETVAL( WPLAN, LOC, P )
	IF( P .EQ. 0 ) CALL STRING('         ^E')
	IF( P .EQ. 0 ) GOTO 100
	CALL STRING('  P^E')
	CALL NUMBER( P, -2 )
	CALL GETVAL( WMOON, LOC, M )
	IF( M .EQ. 0 ) CALL STRING('    ^E')
	IF( M .EQ. 0 ) GOTO 100
	CALL STRING('  M^E')
	CALL NUMBER( M )

100	IF( ORB .EQ. 1 ) CALL STRING(' Ground^E')
	IF( ORB .EQ. 2 ) CALL STRING(' Low   ^E')
	IF( ORB .EQ. 3 ) CALL STRING(' High  ^E')
	END
	SUBROUTINE DISYS( NEW, SHIP, XTR )

	IMPLICIT INTEGER ( A - Z )

	INTEGER OLDAAN(10), LETTER(6), STNAME(2)
	LOGICAL NEW, XTR

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	DATA LETTER/'B','A','F','G','K','M'/

	CALL GETVAL( HMFLAG, SHIP, HYPMOV )
	IF( .NOT. XTR ) GOTO 10
	IF( .NOT. NEW ) RETURN
	CALL CURSOR( 20, 12 )
	CALL STRING('*** ^E')
	CALL PUNIT( SHIP )
	IF( HYPMOV .EQ. 1 ) CALL STRING('in hyperspace ***^E')
	IF( HYPMOV .EQ. 2 ) CALL STRING('in transit ***^E')
	RETURN

10	CALL GETVAL( SHIPTR, SHIP, LOC )
	CALL GETVAL( ORBIT, SHIP, ORB )
	IF( .NOT. NEW .AND. LOC .EQ. OLOC .AND. ORB .EQ. OORB ) GOTO 50
	OLOC = LOC
	OORB = ORB
	CALL CURSOR( 1, 24 )
	CALL STRING('System report from ^E')
	CALL PUNIT( SHIP )
	CALL STRING(' at ^E')
	CALL PLOC( LOC, ORB )
50	IF( .NOT. NEW ) GOTO 300
	CALL CURSOR( 1, 20 )
	CALL STRING('Hyper time/jump:^M^J^E')
	CALL GETVAL( WSTAR, LOC, S )
	DO 100 I = 1, 5
	    CALL GETVAL( TIME, S, I+0, T )
	    IF( T .EQ. 0 ) GOTO 110
	    CALL NUMBER( T, 3 )
	    CALL CHROUT('/')
	    CALL GETVAL( DEST, S, I+0, S1 )
	    CALL GETVAL( NAME, S1, 1, STNAME(1) )
	    CALL GETVAL( NAME, S1, 2, STNAME(2) )
	    CALL STRING( STNAME, 6, 12 )
100	CONTINUE

110	CALL CURSOR( 1, 16 )
	CALL STRING('Satellite:         Type
     &     Allegiance   Low/Num   High/Num^M^J^E')
	CALL GETVAL( NAME, S, 1, IVAL )
	CALL STRING( IVAL, 6, 6 )
	CALL GETVAL( NAME, S, 2, IVAL )
	CALL STRING( IVAL, 6, 6 )
	CALL STRING('     ^E')
	CLASS = IQRAN( S, 60 ) - 1
	CALL CHROUT( LETTER(CLASS/10 + 1) )
	CALL NUMBER( MOD(CLASS,10) )
	CALL CRLF
	CALL GETVAL( WPLACE, S, TLOC )
	IF( TLOC .EQ. 0 ) GOTO 300
200	CALL GETVAL( WSTAR, TLOC, IVAL )
	IF( IVAL .NE. S ) GOTO 300
	CALL GETVAL( WPLAN, TLOC, P )
	CALL GETVAL( WMOON, TLOC, M )
	IF( M .EQ. 0 ) CALL STRING('  Planet #^E')
	IF( M .NE. 0 ) CALL STRING('    Moon #^E')
	IF( M .EQ. 0 ) CALL NUMBER( P, -2 )
	IF( M .NE. 0 ) CALL NUMBER( M, -2 )
	CALL GETVAL( PTYPE, TLOC, IVAL )
	IF( IVAL .EQ. 1 ) CALL STRING('     Habitable^M^J^E')
	IF( IVAL .EQ. 2 ) CALL STRING('     Ordinary^M^J^E')
	IF( IVAL .EQ. 3 ) CALL STRING('     Gasseous^M^J^E')
	TLOC = TLOC + 1
	GOTO 200

300	IF( LOC .EQ. -1 ) RETURN
	CALL GETVAL( POPORG, S, BORG )
	IF( BORG .EQ. 0 ) BORG = 100
	MAGICN = BORG
	CALL GETVAL( PLCORG, S, 1, BLORG )
	IF( BLORG .EQ. 0 ) BLORG = 100
	MAGICN = BLORG + MAGICN*101
	CALL GETVAL( NUAPLC, S, 1, BLNUM )
	IF( BLNUM .EQ. 0 ) BLNUM = 1000
	MAGICN = BLNUM + MAGICN*1001
	CALL GETVAL( PLCORG, S, 2, BHORG )
	IF( BHORG .EQ. 0 ) BHORG = 100
	MAGICN = BHORG + MAGICN*101
	CALL GETVAL( NUAPLC, S, 2, BHNUM )
	IF( BHNUM .EQ. 0 ) BHNUM = 1000
	MAGICN = BHNUM + MAGICN*1001
	IF( MAGICN .EQ. OSORNM .AND. .NOT. NEW ) GOTO 310
	CALL CURSOR( 33, 15 )
	CALL NUMBER( BORG, -2 )
	CALL STRING('        ^E')
	CALL NUMBER( BLORG, -2 )
	CALL CHROUT(' ')
	CALL NUMBER( BLNUM, 3 )
	CALL STRING('     ^E')
	CALL NUMBER( BHORG, -2 )
	CALL CHROUT(' ')
	CALL NUMBER( BHNUM, 3 )
	OSORNM = MAGICN

310	CALL GETVAL( WPLACE, S, TLOC )
	IF( TLOC .EQ. 0 ) RETURN
	IBOD = 0
400	CALL GETVAL( WSTAR, TLOC, IVAL )
	IF( IVAL .NE. S ) RETURN
	IBOD = IBOD + 1
	IF( NEW ) OLDAAN(IBOD) = 0
	CALL GETVAL( POPORG, TLOC, BORG )
	IF( BORG .EQ. 0 ) BORG = 100
	MAGICN = BORG
	CALL GETVAL( PLCORG, TLOC, 1, BLORG )
	IF( BLORG .EQ. 0 ) BLORG = 100
	MAGICN = BLORG + MAGICN*101
	CALL GETVAL( NUAPLC, TLOC, 1, BLNUM )
	IF( BLNUM .EQ. 0 ) BLNUM = 1000
	MAGICN = BLNUM + MAGICN*1001
	CALL GETVAL( PLCORG, TLOC, 2, BHORG )
	IF( BHORG .EQ. 0 ) BHORG = 100
	MAGICN = BHORG + MAGICN*101
	CALL GETVAL( NUAPLC, TLOC, 2, BHNUM )
	IF( BHNUM .EQ. 0 ) BHNUM = 1000
	MAGICN = BHNUM + MAGICN*1001
	IF( MAGICN .EQ. OLDAAN(IBOD) .AND. .NOT. NEW ) GOTO 500
	CALL CURSOR( 33, 15-IBOD )
	CALL NUMBER( BORG, -2 )
	CALL STRING('        ^E')
	CALL NUMBER( BLORG, -2 )
	CALL CHROUT(' ')
	CALL NUMBER( BLNUM, 3 )
	CALL STRING('     ^E')
	CALL NUMBER( BHORG, -2 )
	CALL CHROUT(' ')
	CALL NUMBER( BHNUM, 3 )
	OLDAAN(IBOD) = MAGICN

500	TLOC = TLOC + 1
	GOTO 400
	END
	SUBROUTINE DISTAT( NEW, SHIP )

	IMPLICIT INTEGER ( A - Z )

	INTEGER RESO(4), OLDPDS(3,2), MAXRES(7,4)
	LOGICAL NEW

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	DATA ((MAXRES(I,J),J=1,4),I=1,7)/15,10,4,3, 32,21,9,8,
     &0,0,0,0, 63,0,1,1, 0,63,1,1, 63,63,63,1, 63,63,63,63/

	IF( .NOT. NEW ) GOTO 100
	CALL CURSOR( 1, 24 )
	CALL STRING
     &('Position:^M^JType:^M^JResources:^M^J   Ore:     (^E')
	CALL GETVAL( TYPE, SHIP, IVAL )
	CALL NUMBER( MAXRES( IVAL, 1 ), 2 )
	CALL STRING(')^M^J   Food:    (^E')
	CALL NUMBER( MAXRES( IVAL, 2 ), 2 )
	CALL STRING(')^M^J   Lux:     (^E')
	CALL NUMBER( MAXRES( IVAL, 3 ), 2 )
	CALL STRING(')^M^J   Men:     (^E')
	CALL NUMBER( MAXRES( IVAL, 4 ), 2 )
	CALL STRING(')^M^JTotal power:^M^JPower distribution
     &^M^J   Engines:^M^J   Shields:^M^J   Beam:^M^JPC:^M^J^E')
100	CALL GETVAL( SHIPTR, SHIP, LOC )
	CALL GETVAL( ORBIT, SHIP, ORB )
	CALL GETVAL( HMFLAG, SHIP, IVAL )
	MAGICN = LOC + ORB*2^12 + IVAL*2^16
	IF( MAGICN .EQ. POS .AND. .NOT. NEW ) GOTO 200
	CALL CURSOR( 11, 24 )
	CALL PLOC( LOC, ORB )
	IF( IVAL .EQ. 0 ) CALL STRING('           ^E')
	IF( IVAL .EQ. 1 ) CALL STRING(' Hyperspace^E')
	IF( IVAL .EQ. 2 ) CALL STRING(' Transit   ^E')
	POS = MAGICN
200	IF( SHIP .EQ. OSHIP .AND. .NOT. NEW ) GOTO 300
	CALL CURSOR( 7, 23 )
	CALL PUNIT( SHIP )
	OSHIP = SHIP
300	DO 400 I = 1, 4
	    J = I
	    CALL GETVAL( RES, SHIP, J, IVAL )
	    IF( IVAL .EQ. RESO(I) .AND. .NOT. NEW ) GOTO 400
	    CALL CURSOR( 10, 22-I )
	    CALL NUMBER( IVAL, 2 )
	    RESO(I) = IVAL
400	CONTINUE
	CALL GETVAL( POWER, SHIP, IVAL )
	IF( IVAL .EQ. POW .AND. .NOT. NEW ) GOTO 500
	CALL CURSOR( 14, 17 )
	CALL NUMBER( IVAL, 2 )
	POW = IVAL
500	DO 600 I = 1, 3
	    DO 600 J = 1, 2
		CALL GETVAL( POWDST, SHIP, I+0, J+0, IVAL )
		IF( IVAL .EQ. OLDPDS(I,J) .AND. .NOT. NEW ) GOTO 600
		CALL CURSOR( 11+4*J, 16-I )
		CALL NUMBER( IVAL, 2 )
		OLDPDS(I,J) = IVAL
600	CONTINUE

700	CALL GETVAL( PC, SHIP, IVAL )
	IF( IVAL .EQ. OPC .AND. .NOT. NEW ) GOTO 800
	CALL CURSOR( 5, 12 )
	CALL NUMBER( IVAL, -2 )
	OPC = IVAL

800	RETURN
	END
	SUBROUTINE DISUNT( NEW, UNTLOC, UNTYPE )

	IMPLICIT INTEGER ( A - Z )

	INTEGER OLDSTF(200), SFLAG(4)
	INTEGER TC(7), OC(3)
	LOGICAL NEW

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	DATA TC/'S','H','G','O','F','L','P'/, OC/'.','-','^'/
	DATA SFLAG/' ','*','@','#'/

	IF( .NOT. NEW ) GOTO 50
	CALL CURSOR( 1, 24 )
	IF( UNTYPE .NE. 0 ) CALL PUTYPE( UNTYPE )
	IF( UNTYPE .EQ. 0 ) CALL STRING('units^E')
	IF( UNTLOC .NE. 0 ) CALL STRING(' at ^E')
	IF( UNTLOC .NE. 0 ) CALL PLOC( UNTLOC, 0 )
	IF( UNTLOC .EQ. 0 ) CALL STRING(' in the entire system^E')
	CALL CURSOR( 60, 24 )
	CALL STRING('Total: ^E')
50	SCPTR = 0
	DO 100 I = 1, LUNIT
	    UNIT = I
	    CALL GETVAL( ORG, UNIT, IVAL )
	    IF( IVAL .NE. PLAYER ) GOTO 100
	    CALL GETVAL( SHIPTR, UNIT, SLOC )
	    CALL GETVAL( TYPE, UNIT, STYPE )
	    IF( ( UNTLOC .NE. 0 .AND. SLOC .NE. UNTLOC ) .OR.
     &		( UNTYPE .NE. 0 .AND. STYPE .NE. UNTYPE ) ) GOTO 100
	    SCPTR = SCPTR + 1
	    IF( SCPTR .GT. 200 ) GOTO 100
	    IF( NEW ) OLDSTF( SCPTR ) = 0
	    MAGICN = UNIT
	    MAGICN = MAGICN*8 + STYPE
	    CALL GETVAL( ORBIT, UNIT, SORB )
	    MAGICN = MAGICN*4 + SORB
	    CALL GETVAL( TMTONX, UNIT, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 55
	    CALL GETVAL( HMFLAG, UNIT, IVAL )
	    IVAL = IVAL + 1
55	    MAGICN = MAGICN*4 + IVAL
	    IF( MAGICN .EQ. OLDSTF( SCPTR ) ) GOTO 100
	    CALL CURSOR( MOD(SCPTR-1,10)*8+1, 23-(SCPTR-1)/10 )
	    CALL NUMBER( UNIT, 4 )
	    CALL CHROUT( TC(STYPE) )
	    CALL CHROUT( OC(SORB) )
	    CALL CHROUT( SFLAG(IVAL+1) )
	    OLDSTF( SCPTR ) = MAGICN
100	CONTINUE

	IF( SCPTR .GE. OSCPTR .OR. NEW ) GOTO 201
	DO 200 I = SCPTR, OSCPTR
	    IF( I .LT. 1 .OR. I .GT. 200 ) GOTO 200
	    IF( OLDSTF(I) .EQ. 0 ) GOTO 200
	    CALL CURSOR( MOD(I-1,10)*8+1, 23-(I-1)/10 )
	    CALL REPEAT(' ',7)
	    OLDSTF( I ) = 0
200	CONTINUE
201	CONTINUE
	IF( SCPTR .EQ. OSCPTR .AND. .NOT. NEW ) RETURN
	CALL CURSOR( 67, 24 )
	CALL NUMBER( SCPTR, 4 )
	OSCPTR = SCPTR
	RETURN
	END
	SUBROUTINE DISEDT( NEW, CVERB, CCODE, CDEST )

	IMPLICIT INTEGER ( A - Z )

	INTEGER CVERB( 40 ), CCODE( 40 ), CDEST( 40 )
	INTEGER OLD(40)
	LOGICAL NEW

	DO 100 I = 1, 40
	    IF( NEW ) OLD( I ) = 0
	    MAGICN = CVERB(I) + CCODE(I)*16 + CDEST(I)*256
	    IF( MAGICN .EQ. OLD(I) ) GOTO 100
	    OLD(I) = MAGICN
	    CALL CURSOR( 40*((I-1)/20)+1, 24-MOD(I-1,20) )
	    IF( CVERB(I) .EQ. 0 ) CALL REPEAT( ' ', 37 )
	    IF( CVERB(I) .NE. 0 )
     &		CALL PRINST( I+0, CVERB(I), CCODE(I), CDEST(I) )
100	CONTINUE
	RETURN
	END
	SUBROUTINE PRINST( IPC, IVERB, ICODE, IDEST )

	IMPLICIT INTEGER ( A - Z )

	INTEGER SKPCOD(6), PRCODE(4), UTIL(4)

C	MODIFIED TO NOT DEPEND ON 36 BIT WORD WITH 5 CHARS IN IT
C	INTEGER COMCOD(4,4),
C	DATA ((COMCOD(J,I),J=1,4),I=1,4)/
C     &	'RANDOM JUMP         ','PRODUCE             ',
C     &	'CEASE PRODUCTION    ','SELF DESTRUCT       '/

	DATA SKPCOD/'LT','LE','EQ','NE','GT','GE'/
	DATA PRCODE/'ORE','FOOD','LUX','MEN'/

	IF( UTIL(1) .NE. 0 ) GOTO 2
	UTIL(1) = ISXBIT('Engine')	! "455647515645
	UTIL(2) = ISXBIT('Shield')	! "635051455444
	UTIL(3) = ISXBIT('Beam')	! "424541550000
	UTIL(4) = ISXBIT('Power')	! "605767456200
2	CONTINUE

	CALL NUMBER( IPC, -2 )
	CALL STRING(': ^E')
	GOTO(5,7,20,25,50,55,80,85,90,100,3,3,3,3,110) IVERB

3	RETURN

5	CALL STRING('Move ^E')
	GOTO 9

7	CALL STRING('Jump ^E')

9	CALL PLOC( IDEST, ICODE )
	RETURN

20	CALL STRING('Create ^E')
	CALL PUTYPE( ICODE )
	IF( IDEST .EQ. 0 ) CALL STRING('     ^E')
	IF( IDEST .GT. 0 ) CALL NUMBER( IDEST, 5 )
	CALL STRING('    ^E')
	RETURN

25	ITYPE = IDEST/(2^15)
	ID = MOD( IDEST, 2^15 )
	CALL STRING('Load^E')
	CALL NUMBER( ICODE, 5 )
	CALL CHROUT(' ')
	CALL STRING( PRCODE( MOD( ITYPE, 4 )+1 ), 5, 4 )
	IF( ITYPE .LT. 4 ) CALL STRING(' on   ^E')
	IF( ITYPE .GE. 4 ) CALL STRING(' from ^E')
	IF( ID .GT. 0 ) CALL NUMBER( ID, 8 )
	IF( ID .LE. 0 ) CALL STRING(' surface^E')
	CALL STRING('      ^E')
	RETURN

50	CALL STRING('Tactics     ^E')
	IVAL = IDEST
	DO 52 I = 2, 0, -1
	    CALL NUMBER( MOD( IVAL/(32^I), 32 ), 7 )
52	CONTINUE
	RETURN

55	CALL STRING('Inform^E')
	CALL STRING( IDEST, 6, 6 )
	IF( ICODE .EQ. 0 ) CALL STRING('     ^E')
	IF( ICODE .NE. 0 ) CALL NUMBER( ICODE, 5 )
	CALL REPEAT( ' ', 16 )
	RETURN

80	CALL STRING('Skip ^E')
	ITYPE = IDEST/(2^15)
	CALL STRING( SKPCOD(ITYPE), 5, 2 )
	CALL CHROUT(' ')
	CALL STRING( PRCODE(ICODE), 5, 4 )
	CALL CHROUT(' ')
	CALL NUMBER( MOD( IDEST, 2^15 ), 6 )
	CALL REPEAT( ' ', 15 )
	RETURN

85	CALL STRING('Error ^E')
	IF( IDEST .EQ. 0 ) CALL STRING('stop^E')
	IF( IDEST .EQ. 63 ) CALL STRING('next^E')
	IF( IDEST .GT. 0 .AND. IDEST .LT. 63 ) CALL NUMBER( IDEST, 4 )
	CALL REPEAT( ' ', 23 )
	RETURN

90	IF( IDEST .EQ. 0 ) CALL STRING('Stop    ^E')
	IF( IDEST .NE. 0 ) CALL STRING('Goto^E')
	IF( IDEST .NE. 0 ) CALL NUMBER( IDEST, 4 )
	CALL REPEAT( ' ', 25 )
	RETURN

100	CALL STRING('Build ^E')
	CALL STRING( UTIL(ICODE), 6, 6 )
	CALL NUMBER( IDEST, 4 )
	CALL STRING(' units^E')
	CALL REPEAT( ' ', 11 )
	RETURN

110	CONTINUE

C	MODIFIED TO NOT DEPEND ON 36 BIT WORD WITH 5 CHARS IN IT
C	CALL STRING( COMCOD(1,ICODE), 5, 20 )
	IF( ICODE .EQ. 1 ) CALL STRING('Random jump         ^E')
	IF( ICODE .EQ. 2 ) CALL STRING('Produce             ^E')
	IF( ICODE .EQ. 3 ) CALL STRING('Cease production    ^E')
	IF( ICODE .EQ. 4 ) CALL STRING('Self destruct       ^E')

	CALL REPEAT( ' ', 13 )
	RETURN
	END
	SUBROUTINE DISPOS( NEW )

	IMPLICIT INTEGER ( A - Z )

	INTEGER NMINLO( 500 )			! OR LASPLC
	LOGICAL NEW

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	IF( .NOT. NEW ) RETURN
	DO 100 I = 1, LUNIT
	    UNUM = I
	    CALL GETVAL( ORG, UNUM, IVAL )
	    IF( IVAL .NE. PLAYER ) GOTO 100
	    CALL GETVAL( SHIPTR, UNUM, IVAL )
	    NMINLO( IVAL ) = NMINLO( IVAL ) + 1
100	CONTINUE
	CURPTR = 0
	DO 200 LOC = 1, LASPLC
	    IF( NMINLO(LOC) .EQ. 0 ) GOTO 200
	    CURPTR = CURPTR + 1
	    CALL CURSOR( 40*((CURPTR-1)/20)+1, 24-MOD(CURPTR-1,20) )
	    CALL NUMBER( NMINLO(LOC), 4 )
	    NMINLO(LOC) = 0
	    CALL STRING(' at ^E')
	    CALL PLOC( LOC+0, 0 )
200	CONTINUE
	RETURN
	END
	SUBROUTINE DISPLA( NEW )

	IMPLICIT INTEGER ( A - Z )

	INTEGER UNTIME( 20 ), MONTH(12), FILESP( 13 )
	LOGICAL NEW

	COMMON/FILCOM/FILESP

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	DATA MONTH/'JAN','FEB','MAR','APR','MAY','JUN',
     &		   'JUL','AUG','SEP','OCT','NOV','DEC'/

	IF( .NOT. NEW ) GOTO 100
	CALL CURSOR( 25, 2 )
	FILESP(5) = 0
	FILESP(6) = "077
	CALL OUTSPC( FILESP )
	CALL CURSOR( 2, 24 )
	CALL STRING('Pl   Prog Units   NCSTRU^E')
	CALL CURSOR( 35, 24 )
	CALL STRING('Elapsed:           Started: ^E')
	CALL GETVAL( PTIME, 1, IVAL )
	CALL NUMBER( MOD( IVAL, 31 ) + 1 )
	IVAL = IVAL/31
	CALL CHROUT('-')
	CALL STRING( MONTH( MOD( IVAL, 12 ) + 1 ), 5, 3 )
	CALL CHROUT('-')
	IVAL = IVAL/12
	CALL NUMBER( IVAL+64 )
	CALL CHROUT(' ')
	CALL GETVAL( PTIME, 2, IVAL )
	CALL NUMBER( IVAL/3600000, -2 )
	CALL CHROUT(':')
	CALL NUMBER( MOD( IVAL/60000, 60 ), -2 )
100	CALL GETVAL( PTIME, 3, IVAL )
	CALL CURSOR( 45, 24 )
	CALL NUMBER( IVAL )
	DO 400 I = 1, 20
	    PLYNUM = I
	    IF( NEW ) UNTIME(PLYNUM) = 0
	    CALL GETVAL( PROGS, PLYNUM, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 410
	    CALL GETVAL( NOFUNI, PLYNUM, IVAL1 )
	    IVAL1 = IVAL1 + 1
	    IF( IVAL1 .EQ. ILEFT( UNTIME(PLYNUM) ) ) GOTO 350
	    CALL CURSOR( 40*((I-1)/20)+2, 23-MOD(I-1,20) )
	    CALL NUMBER( PLYNUM, -2 )
	    IF( IVAL .NE. "777777 ) CALL NUMBER( IVAL, 7, 8 )
	    IF( IVAL .EQ. "777777 ) CALL STRING(' empire^E')
	    CALL NUMBER( IVAL1-1, 6 )
350	    CALL GETVAL( NCSTRU, PLYNUM, IVAL2 )
	    IVAL2 = IVAL2 + 1
	    IF( IVAL2 .EQ. IRIGHT( UNTIME(PLYNUM) ) ) GOTO 370
	    CALL CURSOR( 40*((I-1)/20)+22, 23-MOD(I-1,20) )
	    IF( IVAL2 .EQ. 64 ) CALL STRING('Auto^E')
	    IF( IVAL2 .NE. 64 ) CALL NUMBER( IVAL2, 4 )
370	    UNTIME(PLYNUM) = "1000000*IVAL1 + IVAL2
400	CONTINUE

410	CALL GETVAL( USEFUL, 7, WHOINL )
	IF( .NOT. NEW .AND. WHOINL .EQ. OLDINL ) RETURN
	IF( WHOINL .EQ. 0 ) GOTO 500
	CALL CURSOR( 40*((WHOINL-1)/20)+1, 23-MOD(WHOINL-1,20) )
	CALL CHROUT('*')
500	IF( OLDINL .EQ. 0 ) GOTO 600
	CALL CURSOR( 40*((OLDINL-1)/20)+1, 23-MOD(OLDINL-1,20) )
	CALL CHROUT(' ')
600	OLDINL = WHOINL
	RETURN
	END
	SUBROUTINE DISDBG( NEW )

	IMPLICIT INTEGER ( A - Z )

	INTEGER OLDPRG( 20 ), OLDMEM( 40 )
	LOGICAL NEW

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	IF( .NOT. NEW ) GOTO 100
	CALL CURSOR( 1, 4 )
	CALL STRING('LUnit:     /^E')
	CALL NUMBER( MAXUNI, -4 )
	CALL STRING('    LProgr:     /^E')
	CALL NUMBER( MAXPRG, -4 )
	CALL STRING('    LMem:     /^E')
	CALL NUMBER( MAXMEM, -4 )
100	IF( LUNIT .EQ. OLUNIT .AND. .NOT. NEW ) GOTO 105
	CALL CURSOR( 8, 4 )
	CALL NUMBER( LUNIT, -4 )
	OLUNIT = LUNIT
105	CALL GETVAL( USEFUL, 8, LPROGR )
	IF( LPROGR .EQ. OLPRGR .AND. .NOT. NEW ) GOTO 110
	CALL CURSOR( 29, 4 )
	CALL NUMBER( LPROGR, -4 )
	OLPRGR = LPROGR
110	CALL GETVAL( USEFUL, 9, LMEM )
	IF( LMEM .EQ. OLMEM .AND. .NOT. NEW ) GOTO 120
	CALL CURSOR( 48, 4 )
	CALL NUMBER( LMEM, -4 )
	OLMEM = LMEM
120	DO 200 I = 1, 20
	    PRGNUM = I
	    CALL GETVAL( STRADR, PRGNUM, ADDR )
	    CALL GETVAL( LENPRG, PRGNUM, LEN )
	    CALL GETVAL( NUMUSR, PRGNUM, NUM )
	    MAGICN = ADDR + LEN*2^12 + NUM*2^18
	    IF( NEW ) OLDPRG(I) = 0
	    IF( MAGICN .EQ. OLDPRG(I) ) GOTO 200
	    OLDPRG(I) = MAGICN
	    CALL CURSOR( 1, 25-I )
	    IF( MAGICN .EQ. 0 ) CALL STRING('                ^E')
	    IF( MAGICN .EQ. 0 ) GOTO 200
	    CALL NUMBER( PRGNUM, -2 )
	    CALL CHROUT(':')
	    CALL NUMBER( ADDR, -4 )
	    CALL CHROUT(' ')
	    CALL NUMBER( LEN, -2 )
	    CALL CHROUT(' ')
	    CALL NUMBER( NUM, -4 )
200	CONTINUE
	DO 300 I = 1, 40
	    ADDR = I
	    CALL GETVAL( NVERB, ADDR, IV )
	    CALL GETVAL( NCODE, ADDR, IC )
	    CALL GETVAL( NDEST, ADDR, ID )
	    MAGICN = ID + IC*2^12 + IV*2^16
	    IF( NEW ) OLDMEM(I) = 0
	    IF( MAGICN .EQ. OLDMEM(I) ) GOTO 300
	    OLDMEM(I) = MAGICN
	    CALL CURSOR( 20*((I-1)/20)+30, 24-MOD(I-1,20) )
	    IF( MAGICN .EQ. 0 ) CALL STRING('                 ^E')
	    IF( MAGICN .EQ. 0 ) GOTO 300
	    CALL NUMBER( ADDR, -4 )
	    CALL CHROUT(':')
	    CALL NUMBER( IV, -2 )
	    CALL CHROUT(' ')
	    CALL NUMBER( IC, -2 )
	    CALL CHROUT(' ')
	    CALL NUMBER( ID, -6 )
300	CONTINUE
	RETURN
	END
	SUBROUTINE COMAND( ICHAR, COMARA, ARRIND, LCARA )
C***
C***	ROUTINE GET COMMAND FROM USER IF ONE PRESENT.
C***
	INTEGER COMARA(81), LCARA(81), INDEX, ARRIND, ICHAR
	DATA INDEX/0/
C***
C***	IF THERE IS A CHARACTER OUT GET IT, ELSE, SLEEP FOR
C***	0.5 SECONDS OR UNTIL ONE IS.
C***
100	CALL CURBUF
	CALL NAP( 500, "14 )
	CALL CHRBUF( ICHAR )
	IF( ICHAR .EQ. -1 )  RETURN
	IF( ICHAR .EQ. "10 .OR. ICHAR .EQ. "177 )  GOTO 300
	IF( ICHAR .EQ. "25 )  GOTO 400
	IF( ICHAR .EQ. "33 .AND. INDEX .EQ. 0 )  GOTO 200
	IF( ICHAR .LT. "40 )  GOTO 600
	IF( INDEX .GE. 78 )  GOTO 700
C***
C***	NOT SPECIAL CHARACTER, PUT IN ARRAY
C***
	INDEX = INDEX + 1
	CALL CURSOR( 1 + INDEX, 1 )
	CALL CHROUT( ICHAR )
	COMARA(INDEX) = ICON( ICHAR )
	GOTO 100
C***
C***	ESCAPE:  REPEAT LAST COMMAND
C***
200	INDEX = INDSTR
	CALL CURSOR( 2, 1 )
	IF( INDEX .NE. 0 )CALL STRING( COMARA, 1, INDEX )

	GOTO 600
C***
C***	DELETE CHARACTER
C***
300	IF( INDEX .EQ. 0 ) GOTO 600
	INDEX = INDEX - 1
	CALL CURSOR( 2 + INDEX, 1 )
	CALL CHROUT( ' ' )
	GOTO 100
C***
C***	DELETE LINE
C***
400	IF( INDEX .EQ. 0 ) GOTO 600
	CALL CURSOR( 2, 1 )
	DO 500 I = 1, INDEX
	    CALL CHROUT(' ')
500	CONTINUE
	INDEX = 0
	GOTO 100
C***
C***	CARRIAGE RETURN TYPED
C***
600	IF( INDEX .NE. 0 )  GOTO 700
	ICHAR = -1
	GOTO 900
700	COMARA(INDEX + 1) = 0
	CALL CURSOR( 2, 1 )
	DO 800 I = 1, INDEX
	    CALL CHROUT(' ')
800	CONTINUE
	DO 850 I=1, INDEX+1
	    LCARA(I) = COMARA(I)
850	CONTINUE
	CALL ALLCAP( COMARA, INDEX )
	ICHAR = COMARA(1)
900	ARRIND = INDEX
	INDSTR = INDEX
	INDEX = 0
C	CALL NAP( 10, 4 )
	CALL NAP( 1000, 4 )
	RETURN
	END
	SUBROUTINE MESSAG( MSGARA )

	IMPLICIT INTEGER ( A - Z )

	INTEGER MSGARA( 16 )

	COMMON/MESCOM/MESFLG

	IF( MESFLG .LE. 0 ) GOTO 100
	CALL CURSOR( 1, 3 )
	CALL REPEAT( ' ', 80)
100	CALL CURSOR( 1, 3 )
	CALL STRING( MSGARA )
	MESFLG = 10
	RETURN
	END
	SUBROUTINE CEASE

	CALL ENABLE
	CALL GRAFOF
	CALL SETDIS( 0 )
	CALL CURSOR( 1, 1 )
	CALL CLOSE( 1 )
	IF( NUSER(0) .LE. 1 ) CALL SAVESG
	CALL EXPROG
	END
	SUBROUTINE GENINS( PAR, L1, O1, L2, O2, IV, IC, ID )

	IMPLICIT INTEGER ( A - Z )

	INTEGER PAR(19), INSNAM(13), INSNUM(13), SINAME(4), SINUM(4)
	INTEGER SKPCOD(6), RTYPE(4), UTYPE(7), PARNUM(6), UTIL(4)
	LOGICAL JMPERR

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

C***	DEFINE UNIT TYPE CODES: S, H, G, O, F, L, P
	DATA UTYPE/"63,"50,"47,"57,"46,"54,"60/

C***	DEFINE RESOURCE TYPES: O(RE), F(OOD), L(UX), M(EN)
	DATA RTYPE/"57,"46,"54,"55/

C***	DEFINE UTILITIES: E(NGINE) S(HIELD) B(EAM) P(OWER)
	DATA UTIL/"45,"63,"42,"60/

	DATA INSNUM/1,2,3,4,4,4,5,6,7,8,9,9,10/
	DATA SINUM/1,2,3,4/

	IF( INSNAM(1) .NE. 0 ) GOTO 50

C***	DEFINE INSTRUCTIONS: MOVE,MOV,JUMP,JUM,CREATE,CRE
C***	LOAD,TRANSF,PUT,TACTIC,TAC,INFORM,INF
C***	SKIP,ERROR,ERR,GOTO,STOP,BUILD,BUI
	INSNAM(1)  = ISXBIT('Move')		! "555766450000
	INSNAM(2)  = ISXBIT('Jump')		! "526555600000
	INSNAM(3)  = ISXBIT('Create')		! "436245416445
	INSNAM(4)  = ISXBIT('Load')		! "545741440000
	INSNAM(5)  = ISXBIT('Transfer')		! "646241566346
	INSNAM(6)  = ISXBIT('Put')		! "606564000000
	INSNAM(7)  = ISXBIT('Tactic')		! "644143645143
	INSNAM(8)  = ISXBIT('Inform')		! "515646576255
	INSNAM(9)  = ISXBIT('Skip')		! "635351600000
	INSNAM(10) = ISXBIT('Error')		! "456262576200
	INSNAM(11) = ISXBIT('Goto')		! "475764570000
	INSNAM(12) = ISXBIT('Stop')		! "636457600000
	INSNAM(13) = ISXBIT('Build')		! "426551544400

C***	NOARG INSTRUCTION: RANDOM,RAN,PRODUC,PRO,CEASE,CEA,SELF
	SINAME(1) = ISXBIT('Random')		! "624156445755
	SINAME(2) = ISXBIT('Produce')		! "606257446543
	SINAME(3) = ISXBIT('Cease')		! "434541634500
	SINAME(4) = ISXBIT('Selfdestruct')	! "634554460000

	SKPCOD(1) = ISXBIT('LT')		! "546400000000
	SKPCOD(2) = ISXBIT('LE')		! "544500000000
	SKPCOD(3) = ISXBIT('EQ')		! "456100000000
	SKPCOD(4) = ISXBIT('NE')		! "564500000000
	SKPCOD(5) = ISXBIT('GT')		! "476400000000
	SKPCOD(6) = ISXBIT('GE')		! "474500000000
50	CONTINUE

	IC = 0
	ID = 0
	L2 = L1
	O2 = O1
	IV = ISRSIX( INSNAM, PAR(1), 13 )
	IF( IV .EQ. 0 ) GOTO 1100
	IV = INSNUM( IV )
	GOTO(100,100,200,300,400,750,800,900,900,1000) IV

100	CALL PARLOC( PAR(2), L1, O1, JMPERR, ID, IC )
	IF( JMPERR ) GOTO 1200
	L2 = ID
	O2 = IC
150	RETURN

200	IC = ISERCH( UTYPE, FIRSTC( PAR(2) ), 7 )
	IF( IC .EQ. 0 ) GOTO 1200
	CALL CONVRT( PAR(3), 6, 6, PARNUM, 1 )
	CALL GETNUM( PARNUM, 6, ID, 10 )
	IF( ID .LT. 0 ) GOTO 1200
	RETURN

300	CALL CONVRT( PAR(2), 6, 6, PARNUM, 1 )
	CALL GETNUM( PARNUM, 6, IC, 10 )
	IF( IC .LT. 0 ) IC = 0
	CALL CONVRT( PAR(5), 6, 6, PARNUM, 1 )
	CALL GETNUM( PARNUM, 6, ID, 10 )
	IF( PAR(4) .EQ. ISXBIT('FROM') ) ID = ID + 2^17
	IVAL = FIRSTC( PAR(3) )
	IF( IVAL .EQ. "46 ) ID = ID + 2^15
	IF( IVAL .EQ. "54 ) ID = ID + 2*2^15
	IF( IVAL .EQ. "55 ) ID = ID + 3*2^15
350	RETURN

400	ID = 31
	DO 405 I = 2, 4
	    CALL CONVRT( PAR(I), 6, 6, PARNUM, 1 )
	    CALL GETNUM( PARNUM, 6, IVAL, 10 )
	    ID = 32*ID + IVAL
405	CONTINUE
	RETURN

750	ID = PAR(2)
C	ZERO = 0
C	CALL SHIFTC( ID, ZERO, -18 )
C	IF( ZERO .NE. 0 ) GOTO 1200
	CALL CONVRT( PAR(3), 6, 6, PARNUM, 1 )
	CALL GETNUM( PARNUM, 6, IC, 10 )
	IF( IC .GT. 15 ) GOTO 1200
	RETURN

800	IVAL = ISERCH( SKPCOD, PAR(2), 6 )
	IF( IVAL .EQ. 0 ) GOTO 1200
	IC = ISERCH( RTYPE, FIRSTC(PAR(3)), 4 )
	IF( IC .EQ. 0 ) GOTO 1200
	CALL CONVRT( PAR(4), 6, 6, PARNUM, 1 )
	CALL GETNUM( PARNUM, 6, ID, 10 )
	IF( ID .LT. 0 .OR. ID .GE. 2^15 ) GOTO 1200
	ID = ID + IVAL*2^15
	RETURN

900	IF( PAR(2) .EQ. ISXBIT('NEXT') ) GOTO 910
	CALL CONVRT( PAR(2), 6, 6, PARNUM, 1 )
	CALL GETNUM( PARNUM, 2, ID, 10 )
	IF( ID .LT. 0 .OR. ID .GT. 40 ) ID = 0
	RETURN

910	ID = 63
	RETURN

1000	IC = ISERCH( UTIL, FIRSTC(PAR(2)), 4 )
	IF( IC .EQ. 0 ) GOTO 1200
	CALL CONVRT( PAR(3), 6, 6, PARNUM, 1 )
	CALL GETNUM( PARNUM, 6, ID, 10 )
	IF( ID .LE. 0 ) GOTO 1200
	RETURN

1100	IC = ISERCH( SINAME, PAR(1), 7 )
	IF( IC .EQ. 0 ) GOTO 1200
	IC = SINUM( IC )
	IV = 15
	RETURN

1200	CALL MESSAG('Illegal instruction.^E')
	IV = -1
	RETURN
	END
	SUBROUTINE PARLOC( PAR, CLOC, CORB, JMPERR, LOC, ORB )

	IMPLICIT INTEGER ( A - Z )

	INTEGER PAR( 10 ), PN( 6 ), ORBCOD( 3 )
	LOGICAL JMPERR

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	IF( ORBCOD(1) .NE. 0 ) GOTO 10
	ORBCOD(1) = ISXBIT('Ground')		! "476257655644
	ORBCOD(2) = ISXBIT('Low')		! "545767000000
	ORBCOD(3) = ISXBIT('High')		! "505147500000
10	CONTINUE

	JMPERR = .TRUE.
	LOC = CLOC
	ORB = CORB
	CALL GETVAL( WSTAR, LOC, S )
	CALL GETVAL( WPLAN, LOC, P )
	CALL GETVAL( WMOON, LOC, M )
	DO 100 I = 1, 10
	    IF( PAR(I) .EQ. 0 ) GOTO 110
	    IF( (PAR(1).EQ.ISXBIT('TO') .OR. PAR(1).EQ.ISXBIT('AT'))
     &		.AND. I .EQ. 1 ) GOTO 100
	    K = ISRSIX( ORBCOD, PAR(I), 3 )
	    IF( K .EQ. 0 ) GOTO 30
	    ORB = K
	    GOTO 100

30	    DO 50 J = 1, NUMSTR
		CALL GETVAL( NAME, J+0, 1, IVAL )
		IF( IVAL .NE. PAR(I) ) GOTO 50
		S = J
		P = 0
		M = 0
		ORB = 3
		GOTO 100
50	    CONTINUE
	    CALL CONVRT( PAR(I), 6, 6, PN, 1 )
	    CALL GETNUM( PN, 6, IVAL, 10 )
	    IF( PN(1) .NE. 'S' ) GOTO 60
	    S = IVAL
	    P = 0
	    M = 0
	    ORB = 3
	    GOTO 100
60	    IF( PN(1) .NE. 'P' ) GOTO 70
	    P = IVAL
	    M = 0
	    ORB = 3
	    GOTO 100
70	    IF( PN(1) .NE. 'M' ) RETURN
	    M = IVAL
	    ORB = 3
100	CONTINUE

110	DO 200 I = 1, LASPLC
	    LOC = I
	    CALL GETVAL( WSTAR, LOC, IVAL )
	    IF( IVAL .NE. S ) GOTO 200
	    CALL GETVAL( WPLAN, LOC, IVAL )
	    IF( IVAL .NE. P ) GOTO 200
	    CALL GETVAL( WMOON, LOC, IVAL )
	    IF( IVAL .EQ. M ) GOTO 250
200	CONTINUE
	RETURN

250	JMPERR = .FALSE.
	RETURN
	END
	SUBROUTINE SAVESG

	IMPLICIT INTEGER ( A - Z )
	LOGICAL ERROR

	INTEGER FILESP(13)

	COMMON/FILCOM/FILESP

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	IF( JOB(-1) .EQ. 0 ) RETURN	! SAVESG NOT USEFUL UNLESS TOPS10
	CALL GETVAL( USEFUL, 17, IVAL )
	IF( IVAL .EQ. 0 ) RETURN
	CALL ENABLE
	CALL OFILE( 2, FILESP, "400000000014 )
	IF( ERROR(0) ) CALL BUGMSG('INIT: UPD OPEN FAILURE.^E',0,0)
	FILESP(5) = ISXBIT('UPD')
	CALL WFILE( 2, FILESP )
	IF( ERROR(0) ) CALL BUGMSG('INIT: UPD ENTER FAILURE.^E',0,0)

	BEGBLK = NHIBLK(0)
	CALL E( BEGBLK+3, TOPLOC )
	CALL FILPUT( 2, TOPLOC )
	DO 100 I = 1, 490
	    CALL E( BEGBLK+I+3, BEGADR )
	    CALL FILPUT( 2, BEGADR )
100	CONTINUE
	DO 200 I = BEGADR, TOPLOC
	    CALL E( I+0, IVAL )
	    CALL FILPUT( 2, IVAL )
200	CONTINUE
	CALL CLOSE( 2 )
	RETURN
	END

	SUBROUTINE SYSWHO( IJOB )
	INTEGER UNAME(2)
	IF( JOB(IJOB) .EQ. 0 ) RETURN
	CALL STRING('Job ^E')
	CALL NUMBER( IJOB )
	CALL CHROUT(' ')
	UNAME(1) = IGTAB( IJOB, "31 )
	UNAME(2) = IGTAB( IJOB, "32 )
	CALL STRING( UNAME, 6, 12 )
	CALL STRING(' [^E')
	CALL NUMBER( ILEFT( IGTAB( IJOB, 2 ) ), 0, 8 )
	CALL CHROUT(',')
	CALL NUMBER( IRIGHT( IGTAB( IJOB, 2 ) ), 0, 8 )
	CALL STRING('] ^E')
	CALL STRING(' TTY^E')
	CALL NUMBER( ITTY( IJOB ), 0, 8 )
	CALL STRING(' at ^E')
	CALL NODLIN( ITTY(IJOB), IN, IL )
	CALL STRING( NODE( IN ), 6, 6 )
	CALL CHROUT('(')
	CALL NUMBER( IN, 0, 8 )
	CALL STRING(')^E')
C	CALL STRING(' line ^E')
C	CALL NUMBER( IL, 0, 8 )
C	CALL CHROUT(' ')
C	CALL STRING( JSTAT( IJOB ), 6, 2 )
	RETURN
	END
	SUBROUTINE FMAIN

	IMPLICIT INTEGER ( A - Z )

	INTEGER COM(81), PAR(20), EVERB(40), ECODE(40), EDEST(40)
	INTEGER LCARA(81)
	INTEGER COMNAM(25), FILESP(13), TC(7), FPAR(7), DISNAM(8)
	INTEGER TAC(3)
	INTEGER LOOPEN
	INTEGER SNAME(2)
	LOGICAL NEW, LPRIVD, INIFLG, LMOVE, XTR1, XTR2, OXTR1, OXTR2
	LOGICAL JMPERR, MLTISP, JFLAG

	COMMON/FILCOM/FILESP
	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA

	COMMON/ARRCOM/
     &	    NAME,DEST,TIME,WPLACE,
     &	    RESTRN,WSTAR,WPLAN,WMOON,PTYPE,
     &	    POP,POPORG,HUNGER,OPRIND,PLCORG,NUAPLC,
     &	    ORG,RES,TYPE,SHIPTR,ORBIT,HMFLAG,
     &	    WPROGR,PC,ONERPC,TMTONX,PRDTIM,POWER,POWDST,
     &	    PROGS,PRGJOB,NOFUNI,EMPCOD,EMPDST,EMPC,EMPINF,NCSTRU,
     &	    NVERB,NCODE,NDEST,STRADR,LENPRG,NUMUSR,
     &	    MESTRN,PTIME,USEFUL

	COMMON/USRCOM/LASPLC,NUMSTR,NPROGS,LUNIT,PLAYER,
     & MAXUNI,MAXPRG,MAXMEM,MAXPLA

	COMMON/MESCOM/MESFLG


C***	DEFINE SHIP TYPE CHARACTERS
	DATA TC/'S','H','G','O','F','L','P'/

C***	START HIM ON DISPLAY #1 (SENSOR DISPLAY)
	DATA DTYPE/1/, NEW/.TRUE./

	IF( DISNAM(1) .NE. 0 ) GOTO 5

	ICLWHI = 1
	ICLDBL = 2
	ICLRED = 3
	ICLLBL = 4
	ICLPUR = 5
	ICLGRE = 6
	ICLYEL = 7
	ICLBLA = 8

C***	DISPLAY TYPES: SENSOR, SEN, SYSTEM, SYS, STATUS, STA,
C***	UNITS, UNI, EDIT, EDI, POSITI, POS, PLAYER, PLA, DEBUG, DEB
	DISNAM(1) =  ISXBIT('sensors')	! "634556635762
	DISNAM(2) =  ISXBIT('systems')	! "637163644555
	DISNAM(3) =  ISXBIT('status')	! "636441646563
	DISNAM(4) =  ISXBIT('units')	! "655651646300
	DISNAM(5) =  ISXBIT('edit')	! "454451640000
	DISNAM(6) = ISXBIT('positions')! "605763516451
	DISNAM(7) = ISXBIT('players')	! "605441714562
	DISNAM(8) = ISXBIT('debug')	! "444542654700

C***	DEFINED COMMANDS:
C***	DISPLA,DIS,NEW,MISSION,MIS,CLEAR,CLE,STAND,WAIT,SAVE,DONE,EXIT,
C***	GAG,UNGAG,INSERT,INS,I,REPLAC,REP,R,DELETE,DEL,D,TRANSF,TRA,T,
C***	NEWTAC,NEWPC,SENORD,ORDER,ORD,SENTAC,SENPC,WHO
	COMNAM( 1) = ISXBIT('Display')		! "445163605441
	COMNAM( 2) = ISXBIT('New')		! "564567000000
	COMNAM( 3) = ISXBIT('Mission')		! "555163635157
	COMNAM( 4) = ISXBIT('Clear')		! "435445416200
	COMNAM( 5) = ISXBIT('Stand')		! "636441564400
	COMNAM( 6) = ISXBIT('Wait')		! "674151640000
	COMNAM( 7) = ISXBIT('Save')		! "634166450000
	COMNAM( 8) = ISXBIT('Done')		! "445756450000
	COMNAM( 9) = ISXBIT('Exit')		! "457051640000
	COMNAM(10) = ISXBIT('Gag')		! "474147000000
	COMNAM(11) = ISXBIT('Ungag')		! "655647414700
	COMNAM(12) = ISXBIT('Insert')		! "515663456264
	COMNAM(13) = ISXBIT('Replace')		! "624560544143
	COMNAM(14) = ISXBIT('Delete')		! "444554456445
	COMNAM(15) = ISXBIT('Transfer')		! "646241566346
	COMNAM(16) = ISXBIT('Newtactic')	! "564567644143
	COMNAM(17) = ISXBIT('Newpc')		! "564567604300
	COMNAM(18) = ISXBIT('Sendorder')	! "634556576244
	COMNAM(19) = ISXBIT('Senorder')		! "634556576244
	COMNAM(20) = ISXBIT('Order')		! "576244456200
	COMNAM(21) = ISXBIT('Sendtactic')	! "634556644143
	COMNAM(22) = ISXBIT('Sentactic')	! "634556644143
	COMNAM(23) = ISXBIT('Sendpc')		! "634556604300
	COMNAM(24) = ISXBIT('Senpc')		! "634556604300
	COMNAM(25) = ISXBIT('Who')		! "675057000000
5	CONTINUE

C***	****************************
C***	****** BEGIN MAINLINE ******
C***	****************************

	CALL PBACK( ICLBLA )
	CALL PCOLOR( ICLWHI )
	CALL SETTTY( COM, PAR, LEN, LPRIVD, FILESP )
	CALL CHECK( INIFLG )
	IF( INIFLG ) CALL INITDB( COM, PAR, LPRIVD )
	CALL GETVAL( USEFUL, 16, IVAL )
	IF( IVAL .EQ. 0 .OR. LPRIVD ) GOTO 10
	CALL STRING('Stand alone.  Try again later.^M^J^B')
	CALL EXPROG

10	CALL CTRAP
	    CALL CEASE

	CALL GETVAL( USEFUL, 1, NUMSTR )
	CALL GETVAL( USEFUL, 4, LASPLC )
	CALL GETVAL( USEFUL, 5, LUNIT )
	CALL GETVAL( USEFUL, 6, NPROGS )
	CALL GETVAL( USEFUL, 12, MAXUNI )
	CALL GETVAL( USEFUL, 13, MAXPRG )
	CALL GETVAL( USEFUL, 14, MAXMEM )
	CALL GETVAL( USEFUL, 15, MAXPLA )
	CALL PPN( I, IVAL )
	DO 50 PLAYER = 1, NPROGS
	    CALL GETVAL( PROGS, PLAYER+0, J )
	    IF( J .EQ. IVAL ) GOTO 60
	    IF( J .EQ. 0 ) GOTO 70
50	CONTINUE
55	CONTINUE
	CALL STRING('There are too many people in the system.^M^J^B')
	CALL EXPROG

60	CALL PUTVAL( EMPCOD, PLAYER, 0 )
	DO 64 SHIP = 1, LUNIT
	    CALL GETVAL( ORG, SHIP+0, IVAL )
	    IF( IVAL .EQ. PLAYER ) GOTO 67
64	CONTINUE
65	CONTINUE
	CALL CLRSCR
	CALL CURSOR( 23, 14 )
	CALL STRING('Your forces have been destroyed.^E')
	CALL CURSOR( 23, 10 )
	CALL STRING('Do you wish to start again (Y/N)? ^B')
	CALL CHRWAT( ICHAR )
	IF( ICHAR .GT. 91 ) ICHAR = ICHAR - 32
	ICHAR = ICON( ICHAR )
	IF( ICHAR .EQ. 'N' ) CALL EXPROG
	IF( ICHAR .NE. 'Y' ) GOTO 65
	GOTO 72

67	CALL GETVAL( SHIPTR, SHIP, ELOC )
	CALL GETVAL( ORBIT, SHIP, EORB )
	GOTO 90

70	CALL PUTVAL( PROGS, PLAYER, IVAL )
72	ELOC = IRAN( LASPLC-NUMSTR ) + NUMSTR
	CALL GETVAL( PTYPE, ELOC, IVAL )
	IF( IVAL .EQ. 3 ) GOTO 72
	EORB = 1
	CALL ADDUNT( ELOC, 2, SHIP, LMOVE )
	IF( .NOT. LMOVE ) GOTO 55

90	CALL GRAFON
	CALL USRSET( "1030, TTYSPD )

C***	*****************************
C***	****** BEGIN GAME LOOP ******
C***	*****************************

100	CALL USRSET( "2030, TTYSPD )
	CALL USRSET( "2031, TTYSPD )
	IF(100*IGTAB("54,"11)/IGTAB("50,"11).LE.85.OR.LPRIVD) GOTO 101
	CALL CLRSCR
	CALL CURSOR( 21, 12 )
	CALL STRING('It is over styxline.  Try again later.^E')
	CALL CEASE

101	CALL GETVAL( USEFUL, 16, IVAL )
	IF( LPRIVD .OR. IVAL .EQ. 0 ) GOTO 102
	CALL CLRSCR
	CALL CURSOR( 25, 12 )
	CALL STRING('Stand alone.  Try again later.^E')
	CALL CEASE

102	CALL EXUNIT
	CALL GETVAL( ORG, SHIP, IVAL )
	IF( IVAL .EQ. PLAYER ) GOTO 105
	DO 103 SHIP = 1, LUNIT
	    CALL GETVAL( ORG, SHIP+0, IVAL )
	    IF( IVAL .EQ. PLAYER ) GOTO 104
103	CONTINUE
	CALL CLRSCR
	CALL CURSOR( 24, 12 )
	CALL STRING('Your forces have been destroyed.^E')
	CALL CEASE

104	NEW = .TRUE.

105	CALL GETVAL( SHIPTR, SHIP, CLOC )
	CALL GETVAL( SHIPTR, SHIP, CORB )
	CALL GETVAL( WSTAR, CLOC, CSTAR )
	CALL GETVAL( HMFLAG, SHIP, HYPMOV )
	XTR1 = .FALSE.
	XTR2 = .FALSE.
	IF( CLOC .NE. OLOC .AND. HYPMOV .NE. 0 ) XTR1 = .TRUE.
	IF( CSTAR .NE. OSTAR .AND. HYPMOV .NE. 0 ) XTR2 = .TRUE.
	IF( DTYPE .EQ. 1 .AND. XTR1 .NE. OXTR1 ) NEW = .TRUE.
	IF( DTYPE .EQ. 2 .AND. XTR2 .NE. OXTR2 ) NEW = .TRUE.
	OXTR1 = XTR1
	OXTR2 = XTR2
	IF( XTR1 .OR. XTR2 ) GOTO 106
	OLOC = CLOC
	OSTAR = CSTAR
106	IF( .NOT. NEW ) GOTO 110
	MESFLG = 0
	CALL USRSET( "2002, 1 )
	CALL CLRSCR
	CALL CURSOR( 1, 2 )
	CALL STRING('ET for ^E')
	CALL GETVAL( TYPE, SHIP, IVAL )
	CALL CHROUT( TC(IVAL) )
	CALL NUMBER( SHIP )
	CALL STRING(':^M^J>^E')

110	CALL GETVAL( TMTONX, SHIP, TIMETO )
	IF( .NOT. NEW .AND. TIMETO .EQ. OTIMET ) GOTO 120
	OTIMET = TIMETO
	CALL CURSOR( 14, 2 )
	IF( TIMETO .EQ. 0 ) CALL STRING('Ready^E')
	IF( TIMETO .GT. 0 ) CALL NUMBER( TIMETO, 5 )

120	IF( DTYPE .EQ. 1 ) CALL DISENS( NEW, SHIP, XTR1 )
	IF( DTYPE .EQ. 2 ) CALL DISYS( NEW, SHIP, XTR2 )
	IF( DTYPE .EQ. 3 ) CALL DISTAT( NEW, SHIP )
	IF( DTYPE .EQ. 4 ) CALL DISUNT( NEW, UNTLOC, UNTYPE )
	IF( DTYPE .EQ. 5 ) CALL DISEDT( NEW, EVERB, ECODE, EDEST )
	IF( DTYPE .EQ. 6 ) CALL DISPOS( NEW )
	IF( DTYPE .EQ. 7 ) CALL DISPLA( NEW )
	IF( DTYPE .EQ. 8 ) CALL DISDBG( NEW )

	CALL GETVAL( USEFUL, 10, WHOTO )
	IF( WHOTO .NE. PLAYER ) GOTO 126
	CALL PUTVAL( -1, 0 )
	CALL GETVAL( USEFUL, 11, WHOFRM )
	CALL MESSAG('^G^E')
	CALL NUMBER( WHOFRM, -2 )
	CALL STRING(': ^E')
	DO 125 I = 1, 72
	    CALL GETVAL( MESTRN, I+0, IVAL )
	    CALL PUTVAL( -1, 0 )
	    IF( IVAL .EQ. 0 ) GOTO 126
	    CALL CHROUT( IVAL )
125	CONTINUE
126	CONTINUE

	IF( MESFLG .LE. 0 ) GOTO 130
	MESFLG = MESFLG - 1
	IF( MESFLG .GT. 0 ) GOTO 130
	OBLORN = 0
	CALL CURSOR( 1, 3 )
	CALL REPEAT( ' ', 80 )

130	CALL GETVAL( EMPCOD, PLAYER, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 139
	CALL PUTVAL( -1, 0 )
	CALL GETVAL( EMPDST, PLAYER, BLORUN )
	CALL GETVAL( EMPC, PLAYER, IPC )
	GOTO( 137, 138, 131, 136 ) IVAL

131	IF( BLORUN .EQ. OBLORN ) GOTO 139
	DO 133 I = 1, 7
	    FPAR(I) = 0
133	CONTINUE
	CALL MESSAG('Battle at ^E')
	CALL PLOC( BLORUN, IPC )
	CALL STRING(' Engaged:^E')
	DO 134 I = 1, LUNIT
	    UNUM = I
	    CALL GETVAL( SHIPTR, UNUM, IVAL )
	    IF( IVAL .NE. BLORUN ) GOTO 134
	    CALL GETVAL( ORG, UNUM, IVAL )
	    IF( IVAL .NE. PLAYER ) GOTO 134
	    CALL GETVAL( TYPE, UNUM, IVAL )
	    FPAR(IVAL) = FPAR(IVAL) + 1
134	CONTINUE
	DO 135 I = 1, 7
	    IF( FPAR(I) .EQ. 0 ) GOTO 135
	    CALL NUMBER( FPAR(I), 5 )
	    CALL CHROUT( TC(I) )
135	CONTINUE
	OBLORN = BLORUN
	GOTO 139

136	IF( BLORUN .EQ. OBLORN ) GOTO 139
	CALL MESSAG('^G*********** Revolt at ^E')
	CALL PLOC( BLORUN, 0 )
	CALL STRING(' ***********^E')
	OBLORN = BLORUN
	GOTO 139

137	CALL MESSAG('Error ^E')
	CALL PUNIT( BLORUN )
	CALL STRING(' @ Ins. #^E')
	CALL GETVAL( WPROGR, BLORUN, WP )
	CALL GETVAL( STRADR, WP, ADDR )
	ADDR = ADDR + IPC - 1
	CALL GETVAL( NVERB, ADDR, IV )
	CALL GETVAL( NCODE, ADDR, IC )
	CALL GETVAL( NDEST, ADDR, ID )
	CALL PRINST( IPC, IV, IC, ID )
	GOTO 139

138	CALL MESSAG('Inform ^E')
	CALL GETVAL( EMPINF, PLAYER, IVAL )
	CALL STRING( IVAL, 6, 6 )
	IF( IPC .NE. 0 ) CALL NUMBER( IPC, 3 )
	CALL STRING(' from ^E')
	CALL NUMBER( BLORUN )
	CALL GETVAL( TYPE, BLORUN, IVAL )
	CALL CHROUT(TC(IVAL))
	CALL STRING(' at ^E')
	CALL GETVAL( SHIPTR, BLORUN, IVAL )
	CALL GETVAL( ORBIT, BLORUN, I )
	CALL PLOC( IVAL, I )

139	NEW = .FALSE.
	TMTOWA = MAX0( TMTOWA-1, 0 )
	IF( TMTOWA .GT. 0 ) GOTO 100
	CALL OUTBUF( 1 )
	CALL COMAND( ICHAR, COM, LEN, LCARA )
	IF( ICHAR .EQ. -1 ) GOTO 100
	CALL PARSE( COM, LEN, PAR, ITOKS, 20 )
	IF( ITOKS .EQ. 0 ) GOTO 100
	IF( ITOKS .EQ. 20 ) GOTO 141
	DO 140 J = ITOKS+1, 20
	    PAR(J) = 0
140	CONTINUE
141	CONTINUE
	ICOM = ISRSIX( COMNAM, PAR(1), 25 )
	IF( ICOM .EQ. 0 ) GOTO 200
	GOTO( 145,145, 150,150, 157, 158, 160,  161, 162,
     &		164, 166, 170,170, 180,
     &		184, 190, 195, 250,250,250, 1102,1102, 1104,1104, 1300
     &		) ICOM

C***	DISPLA COMMAND

145	IF( PAR(2) .EQ. 0 ) NEW = .TRUE.
	IF( PAR(2) .EQ. 0 ) GOTO 100
	IDTYPE = ISRSIX( DISNAM, PAR(2), 8 )
	IF( IDTYPE .EQ. 8 .AND. .NOT. LPRIVD ) IDTYPE = 0
	IF( IDTYPE .NE. 0 ) GOTO 146
	CALL MESSAG('Unknown display type: ^E')
	CALL STRING( PAR(2), 6, 6 )
	GOTO 100

146	IF( IDTYPE .NE. 4 ) GOTO 147
	I = 3
	UNTYPE = PAR(3)
	IVAL = FIRSTC(UNTYPE)
	UNTYPE = ISERCH( TC, ICON( UNTYPE+32+IVAL ), 7 )
	IF( UNTYPE .NE. 0 ) I = I + 1
	UNTLOC = 0
	IF( PAR(I) .EQ. "415454000000 ) GOTO 148
	CALL PARLOC( PAR(I), CLOC, CORB, JMPERR, UNTLOC, IVAL )
	IF( JMPERR ) UNTLOC = 0
	GOTO 148

147	I = 0
	IF( ITOKS .GE. 3 ) CALL GETNUM( COM, LEN, I, 10 )
	IF( I .LT. 0 .OR. I .GT. LUNIT ) GOTO 149
	IF( I.EQ.0 .AND. IDTYPE.EQ.4 .AND. PAR(3).NE.0 ) GOTO 147
	IF( I .EQ. 0 ) I = SHIP
	CALL GETVAL( ORG, I, IVAL )
	IF( IVAL .NE. PLAYER ) GOTO 149
	SHIP = I
148	DTYPE = IDTYPE
	NEW = .TRUE.
	GOTO 100

149	CALL MESSAG('Unit is not in fleet.^E')
	NEW = .FALSE.
	GOTO 100

C***	MISSION COMMAND

150	DO 155 I = 1, 40
	    EVERB(I) = 0
	    ECODE(I) = 0
	    EDEST(I) = 0
155	CONTINUE
	IF( DTYPE .EQ. 5 ) NEW = .TRUE.
	CALL GETVAL( SHIPTR, SHIP, ELOC )
	CALL GETVAL( ORBIT, SHIP, EORB )
	CALL GETNUM( COM, LEN, MISS, 10 )
	IF( MISS .LE. 0 .OR. MISS .GT. LUNIT ) GOTO 100
	CALL GETVAL( ORG, MISS, IVAL )
	IF( IVAL .NE. PLAYER ) GOTO 100
	CALL GETVAL( SHIPTR, MISS, ELOC )
	CALL GETVAL( SHIPTR, MISS, EORB )
	CALL GETVAL( WPROGR, MISS, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 100
	CALL GETVAL( STRADR, IVAL, ADDR )
	CALL GETVAL( LENPRG, IVAL, LEN )
	IF( LEN .EQ. 0 .OR. ADDR .EQ. 0 ) GOTO 100
	DO 156 I = 1, LEN
	    CALL GETVAL( NVERB, ADDR, EVERB(I) )
	    CALL GETVAL( NCODE, ADDR, ECODE(I) )
	    CALL GETVAL( NDEST, ADDR, EDEST(I) )
	    ADDR = ADDR + 1
156	CONTINUE
	GOTO 100

C***	STAND ALONE COMMAND	(KICK EVERYBODY ELSE OUT OF GAME)

157	IF( .NOT. LPRIVD ) GOTO 200
	CALL GETVAL( USEFUL, 16, IVAL )
	CALL PUTVAL( USEFUL, 16, 1-IVAL )
	GOTO 100

C***	WAIT COMMAND	(TO HELP CREATE THE EMPIRE)

158	IF( .NOT. LPRIVD ) GOTO 200
	CALL GETVAL( USEFUL, 16, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 200
	CALL GETVAL( USEFUL, 17, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 200
	CALL GETNUM( COM, LEN, TMTOWA, 10 )
	IF( TMTOWA .LE. 0 ) TMTOWA = 1
	GOTO 100

C***	SAVE COMMAND	(ALLOW A NON-EMPIRE GAME TO BE SAVED)

160	IF( .NOT. LPRIVD ) GOTO 200
	CALL GETVAL( USEFUL, 17, IVAL )
	IF( IVAL .EQ. 0 ) CALL PUTVAL( USEFUL, 17, 1 )
	GOTO 100

C***	DONE COMMAND	(SAVE EMPIRE GAME, LET USERS IN)

161	CALL GETVAL( USEFUL, 16, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 162
	CALL GETVAL( USEFUL, 17, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 162
	CALL PUTVAL( -1, 2 )
	CALL PUTVAL( PROGS, PLAYER, "777777 )

C***	EXIT COMMAND

162	CALL PUTVAL( NCSTRU, PLAYER, 63 )
	CALL CEASE
	GOTO 100

C***	GAG COMMAND

164	CALL USRSET( "2013, 0 )
	CALL MESSAG('Terminal is now gagged.^E')
	GOTO 100

C***	UNGAG COMMAND

166	CALL USRSET( "2013, 1 )
	CALL MESSAG('Terminal is no longer gagged.^E')
	GOTO 100

C***	INSERT COMMAND

170	CALL GETNUM( COM, LEN, LINE, 10 )
	IF( LINE .LT. 1 .OR. LINE .GT. 40 ) GOTO 175
	CALL GENINS( PAR(3), ELOC, EORB, ENLOC, ENORB, EV, EC, ED )
	IF( EV .LT. 0 ) GOTO 100
	EVERB(LINE) = EV
	ECODE(LINE) = EC
	EDEST(LINE) = ED
	ELOC = ENLOC
	EORB = ENORB
	GOTO 100

175	CALL MESSAG('Line out of bounds.^E')
	GOTO 100

C***	DELETE COMMAND

180	CALL GETNUM( COM,LEN, PAR(1),10, PAR(2),10, PAR(3),10,
     & PAR(4),10, PAR(5),10, PAR(6),10, PAR(7),10, PAR(8),10,
     & PAR(9),10, PAR(10),10, PAR(11),10, PAR(12),10, PAR(13),10,
     & PAR(14),10, PAR(15),10, PAR(16),10, PAR(17),10, PAR(18),10,
     & PAR(19),10, PAR(20),10 )
	DO 181 I = 1, 20
	    LINE = PAR(I)
	    IF( LINE .EQ. 0 ) GOTO 100
	    IF( LINE .LT. 1 .OR. LINE .GT. 40 ) GOTO 175
	    EVERB(LINE) = 0
	    ECODE(LINE) = 0
	    EDEST(LINE) = 0
181	CONTINUE
	GOTO 100

C***	TRANSFER COMMAND

184	CALL GETNUM( COM, LEN, PAR(1),10, PAR(2),10, PAR(3),10 )
	IF( PAR(3) .EQ. 0 ) PAR(3) = PAR(2)
	IF(PAR(1).GE.1.AND.PAR(1).LE.40.AND.PAR(1)+PAR(3)-PAR(2).LE.40
     &	.AND.PAR(2).GE.0.AND.PAR(2).LE.PAR(3).AND.PAR(3).LE.40)GOTO 185
	CALL MESSAG('Transfer line numbers out of range.^E')
	GOTO 100

185	IF( PAR(1) .GT. PAR(2) ) GOTO 186
	J = PAR(2)
	K = PAR(3)
	LINE = PAR(1)
	IVAL = 1
	GOTO 187

186	J = PAR(3)
	K = PAR(2)
	LINE = PAR(1) + PAR(3) - PAR(2)
	IVAL = -1

187	DO 188 I = J, K, IVAL
	    EVERB(LINE) = EVERB(I)
	    EVERB(I) = 0
	    ECODE(LINE) = ECODE(I)
	    ECODE(I) = 0
	    EDEST(LINE) = EDEST(I)
	    EDEST(I) = 0
	    LINE = LINE + IVAL
188	CONTINUE

	DO 189 I = 1, 40
	    IF( (EVERB(I) .EQ. 8 .OR. EVERB(I) .EQ. 9)
     &		.AND. EDEST(I).GE.PAR(2) .AND. EDEST(I).LE.PAR(3))
     &		EDEST(I) = EDEST(I) - PAR(2) + PAR(1)
189	CONTINUE
	GOTO 100

C***	NEWTAC COMMAND

190	CALL GETNUM( COM, LEN, TAC(1),10, TAC(2),10, TAC(3),10 )
	DO 192 I = 1, 3
	    TAC(I) = MAX0( 0, TAC(I) )
192	CONTINUE
	GOTO 100

C***	NEWPC COMMAND

195	CALL GETNUM( COM, LEN, NEWPCV, 10 )
	IF( NEWPCV .LT. 0 .OR. NEWPCV .GT. 40 ) NEWPCV = 0
	GOTO 100

C***	NOT IN COMMAND LIST.  EITHER SNN, CNNNN OR DIRECT COMMAND

200	CALL CONVRT( PAR(1), 6, 6, FPAR, 1 )
	CALL GETNUM( FPAR(2), 5, UNUM, 10 )

C***	TRY SNN (SEND) COMMAND

	IF( FPAR(1).NE.'S'.OR.UNUM.LT.1.OR.UNUM.GT.NPROGS) GOTO 210
	I = ISERCH( COM, ' ', LEN )
	IF( I .EQ. 0 .OR. I .GE. LEN ) GOTO 100
	IF( LEN-I .GT. 71 ) LEN = I+71
	DO 205 J = I, LEN
	    CALL PUTVAL( MESTRN, J-I+1, ICON(LCARA(J)) )
205	CONTINUE
	CALL PUTVAL( USEFUL, 10, UNUM )
	CALL PUTVAL( USEFUL, 11, PLAYER )
	COM(1) = '*'
	GOTO 100

C***	TRY CNNNN (COMMAND COMMAND)

210	IF( FPAR(1) .NE. 'C' .OR. UNUM .EQ. 0 ) GOTO 220
	IF( UNUM .LT. 0 .OR. UNUM .GT. LUNIT ) GOTO 149
	CALL GETVAL( ORG, UNUM, IVAL )
	IF( IVAL .NE. PLAYER ) GOTO 149
	I = 2
	GOTO 230

C***	TRY DIRECT COMMAND

220	UNUM = SHIP
	I = 1

230	CALL GETVAL( SHIPTR, UNUM, SLOC )
	CALL GETVAL( SHIPTR, UNUM, SORB )
	CALL GENINS( PAR(I), SLOC, SORB, I, J, EV, EC, ED )
	IF( EV .LT. 0 ) GOTO 100
	MLTISP = .FALSE.
	ILEN = 1
	GOTO 1000

C***	ORDER COMMAND

250	ILEN = 0
	DO 275 I = 1, 40
	    IF( EVERB(I) .NE. 0 ) ILEN = I
275	CONTINUE
	MLTISP = .TRUE.

1000	ICOM = 10000			! ICOM = 'SORD'
	CALL MESSAG('Orders sent to: ^E')

1010	CALL GETVAL( USEFUL, 7, WHOINL )
	IF( WHOINL .EQ. 0 )  GOTO 1030
	CALL GETVAL( NCSTRU, WHOINL, IVAL )
	IF( IVAL .EQ. 63 )  GOTO 1030
	CALL ADDVAL( -1, 1 )
	CALL PUTVAL( NCSTRU, PLAYER, 0 )
	CALL NAP( 500, 4 )
	GOTO 1010

1030	CALL PUTVAL( USEFUL, 7, PLAYER )
	CALL GETVAL( USEFUL, 8, LPROGR )
	PRGNUM = 0
	ADDR = 0
	IF( LPROGR .EQ. 0 )  GOTO 1061
	DO 1060 I = 1, LPROGR
	    FPNUM = I
	    CALL GETVAL( STRADR, FPNUM, ADDR )
	    CALL GETVAL( LENPRG, FPNUM, NLEN )
	    IF( NLEN .LT. ILEN ) GOTO 1060
	    IF( NLEN .GT. ILEN ) GOTO 1050
	    IF( ILEN .EQ. 0 )  GOTO 1041
	    DO 1040 J = 1, ILEN
		CALL GETVAL( NVERB, ADDR, IVAL )
		IF( MLTISP .AND. IVAL .NE. EVERB(J) )  GOTO 1050
		IF( .NOT. MLTISP .AND. IVAL .NE. EV )  GOTO 1050
		CALL GETVAL( NCODE, ADDR, IVAL )
		IF( MLTISP .AND. IVAL .NE. ECODE(J) )  GOTO 1050
		IF( .NOT. MLTISP .AND. IVAL .NE. EC )  GOTO 1050
		CALL GETVAL( NDEST, ADDR, IVAL )
		IF( MLTISP .AND. IVAL .NE. EDEST(J) )  GOTO 1050
		IF( .NOT. MLTISP .AND. IVAL .NE. ED )  GOTO 1050
		ADDR = ADDR + 1
1040	    CONTINUE
1041	    CONTINUE
	    PRGNUM = FPNUM
	    GOTO 1101

1050	    CALL GETVAL( NUMUSR, FPNUM, IVAL )
	    IF( IVAL .GT. 0 ) GOTO 1060
	    IF( PRGNUM .GT. 0 ) GOTO 1060
	    PRGNUM = FPNUM
	    IF( NLEN .NE. ILEN ) PRGNUM = -PRGNUM
	    FLEN = NLEN
1060	CONTINUE
1061	CONTINUE

	IF( PRGNUM .NE. 0 )  GOTO 1070
	CALL ADDVAL( USEFUL, 8, 1 )
	PRGNUM = LPROGR + 1
	IF( PRGNUM .GT. MAXPRG ) CALL BUGMSG('LPROGR>MAXPRG^E',0,0)
	CALL PUTVAL( LENPRG, PRGNUM, ILEN )
	CALL GETVAL( USEFUL, 9, LMEM )
	IF(LMEM+ILEN.GT.MAXMEM) CALL BUGMSG('LMEM>MAXMEM^E',0,0)
	CALL ADDVAL( -1, ILEN )
	CALL PUTVAL( STRADR, PRGNUM, LMEM+1 )
1070	CALL GETVAL( STRADR, IABS(PRGNUM), ADDR )
	IF( ILEN .EQ. 0 ) GOTO 1101
	DO 1100 I = 1, ILEN
	    IF( .NOT. MLTISP )  GOTO 1080
	    CALL PUTVAL( NVERB, ADDR, EVERB(I) )
	    CALL PUTVAL( NCODE, ADDR, ECODE(I) )
	    CALL PUTVAL( NDEST, ADDR, EDEST(I) )
	    GOTO 1090
1080	    CALL PUTVAL( NVERB, ADDR, EV )
	    CALL PUTVAL( NCODE, ADDR, EC )
	    CALL PUTVAL( NDEST, ADDR, ED )
1090	    ADDR = ADDR + 1
1100	CONTINUE
1101	CONTINUE
	IF( PRGNUM .GT. 0 ) GOTO 1105

	PRGNUM = -PRGNUM
	CALL PUTVAL( LENPRG, PRGNUM, ILEN )
	LPROGR = LPROGR + 1
	CALL ADDVAL( USEFUL, 8, 1 )
	CALL PUTVAL( STRADR, LPROGR, ADDR )
	CALL PUTVAL( LENPRG, LPROGR, FLEN-ILEN )
	GOTO 1105

C***	SENTAC COMMAND

1102	ICOM = 10001			! ICOM = 'STAC'
	MLTISP = .TRUE.
	CALL MESSAG('Tactics sent to: ^E')
	GOTO 1105

C***	SENPC COMMAND

1104	ICOM = 10002			! ICOM = 'SPC'
	MLTISP = .TRUE.
	CALL MESSAG('PC sent to: ^E')

1105	DO 1106 I = 1, 7
	    FPAR(I) = 0
1106	CONTINUE
	JFLAG = ( PAR(2).EQ.ISXBIT('UNITS') .OR. PAR(2).EQ.ISXBIT('UNI') )
	LOOPEN=1

C	Added because commands with no destination were falling to "no unit"
C	instead of the ship in view. (Linux port)
	PAR(1) = SHIP
	IF( .NOT. MLTISP ) GOTO 1119
	CALL GETNUM( COM,LEN, PAR(1),10, PAR(2),10, PAR(3),10,
     & PAR(4),10, PAR(5),10, PAR(6),10, PAR(7),10, PAR(8),10,
     & PAR(9),10, PAR(10),10, PAR(11),10, PAR(12),10, PAR(13),10,
     & PAR(14),10, PAR(15),10, PAR(16),10, PAR(17),10, PAR(18),10,
     & PAR(19),10, PAR(20),10 )
	IF( JFLAG )  GOTO 1130
	IF( PAR(1) .EQ. 0 ) PAR(1) = SHIP
	LOOPEN=20

1119	CONTINUE
	DO 1120 I = 1, LOOPEN
	    UNUM = PAR(I)
1110	    IF( UNUM .LT. 1 .OR. UNUM .GT. LUNIT )  GOTO 1120
	    CALL GETVAL( ORG, UNUM, IVAL )
	    IF( IVAL .NE. PLAYER )  GOTO 1120
	    CALL GETVAL( HMFLAG, UNUM, IVAL )
	    IF( IVAL .EQ. 1 ) GOTO 1120
	    CALL GETVAL( TYPE, UNUM, IVAL )
	    FPAR(IVAL) = FPAR(IVAL) + 1
	    IF( ICOM .NE. 10000 ) GOTO 1113
	    CALL GETVAL( WPROGR, UNUM, CURPRG )
	    CALL PUTVAL( -1, PRGNUM )
	    IF( CURPRG .NE. 0 )  CALL ADDVAL( NUMUSR, CURPRG, -1 )
	    CALL ADDVAL( NUMUSR, PRGNUM, 1 )
	    CALL PUTVAL( PC, UNUM, 1 )
	    CALL PUTVAL( ONERPC, UNUM, 0 )
	    GOTO 1120

1113	    CONTINUE
	    IF( ICOM .NE. 10001 ) GOTO 1117
	    CALL GETVAL( POWER, UNUM, IVAL )
	    IF( TAC(1)+TAC(2)+TAC(3) .GT. IVAL ) GOTO 1120
	    DO 1115 J = 1, 3
		CALL GETVAL( POWDST, UNUM, J+0, 2, IVAL )
		CALL PUTVAL( POWDST, UNUM, J+0, 1, MIN0(TAC(J),IVAL) )
1115	    CONTINUE
	    GOTO 1120

1117	    CALL PUTVAL( PC, UNUM, NEWPCV )
	    CALL PUTVAL( ONERPC, UNUM, 0 )

1120	CONTINUE
	GOTO 1141

1130	I = PAR(1)
	IF( I .LT. 1 .OR. I .GT. LUNIT )  I = 1
	J = PAR(2)
	IF( J .LT. 1 .OR. J .GT. LUNIT )  J = LUNIT
	DO 1140 K = I, J
	    UNUM = K
	    CALL GETVAL( ORG, UNUM, IVAL )
	    IF( IVAL .NE. PLAYER )  GOTO 1140
	    CALL GETVAL( SHIPTR, UNUM, IVAL )
	    IF( UNTLOC .NE. 0 .AND. IVAL .NE. UNTLOC ) GOTO 1140
	    CALL GETVAL( HMFLAG, UNUM, IVAL )
	    IF( IVAL .EQ. 1 ) GOTO 1140
	    CALL GETVAL( TYPE, UNUM, IVAL )
	    IF( UNTYPE .NE. 0 .AND. IVAL .NE. UNTYPE ) GOTO 1140
	    FPAR(IVAL) = FPAR(IVAL) + 1
	    IF( ICOM .NE. 10000 ) GOTO 1133
	    CALL GETVAL( WPROGR, UNUM, CURPRG )
	    CALL PUTVAL( -1, PRGNUM )
	    IF( CURPRG .NE. 0 )  CALL ADDVAL( NUMUSR, CURPRG, -1 )
	    CALL ADDVAL( NUMUSR, PRGNUM, 1 )
	    CALL PUTVAL( PC, UNUM, 1 )
	    CALL PUTVAL( ONERPC, UNUM, 0 )
	    GOTO 1140

1133	    CONTINUE
	    IF( ICOM .NE. 10001 ) GOTO 1137
	    CALL GETVAL( POWER, UNUM, IVAL )
	    IF( TAC(1)+TAC(2)+TAC(3) .GT. IVAL ) GOTO 1140
	    DO 1135 J = 1, 3
		CALL GETVAL( POWDST, UNUM, J+0, 2, IVAL )
		CALL PUTVAL( POWDST, UNUM, J+0, 1, MIN0(TAC(J),IVAL) )
1135	    CONTINUE
	    GOTO 1140

1137	    CALL PUTVAL( PC, UNUM, NEWPCV )
	    CALL PUTVAL( ONERPC, UNUM, 0 )

1140	CONTINUE
1141	CONTINUE

	IF( ICOM .EQ. 10000 ) CALL PUTVAL( USEFUL, 7, 0 )
	JFLAG = .FALSE.
	DO 1200 I = 1, 7
	    IF( FPAR(I) .EQ. 0 ) GOTO 1200
	    CALL NUMBER( FPAR(I), 5 )
	    CALL CHROUT( TC(I) )
	    JFLAG = .TRUE.
1200	CONTINUE
	IF( JFLAG ) GOTO 100
	CALL STRING(' No unit.^E')
	GOTO 100

C***	WHO COMMAND

1300	CALL GETNUM( COM, LEN, EMPNUM, 10 )
	IF( EMPNUM .GT. 0 .AND. EMPNUM .LE. NPROGS ) GOTO 1305
	CALL MESSAG('Illegal player number.^E')
	GOTO 100

1305	CALL MESSAG('Player #^E')
	CALL NUMBER( EMPNUM, -2 )
	CALL GETVAL( NCSTRU, EMPNUM, IVAL )
	IF( IVAL .LT. 63 ) GOTO 1310
	CALL GETVAL( PROGS, EMPNUM, IVAL )
	CALL STRING(' is running automatically for ^E')
	IF( IVAL .EQ. "777777 ) CALL STRING('the empire.^E')
	IF( IVAL .EQ. "777777 ) GOTO 100
	CALL STRING('[*,^E')
	CALL NUMBER( IVAL, 0, 8 )
	CALL STRING('].^E')
	GOTO 100

1310	CALL STRING(' is ^E')
	CALL GETVAL( PRGJOB, EMPNUM, J )
	CALL SYSWHO(J)
	GOTO 100

	END
