Cindx#	greebl.for - Multi-user game where the ballons are out to get you!
C@HDR@	$Id$
C@HDR@
C@HDR@	Copyright (c) 1982-2026 Christopher Caldwell (Christopher.M.Caldwell0@gmail.com)
C@HDR@
C@HDR@	Permission is hereby granted, free of charge, to any person
C@HDR@	obtaining a copy of this software and associated documentation
C@HDR@	files (the "Software"), to deal in the Software without
C@HDR@	restriction, including without limitation the rights to use,
C@HDR@	copy, modify, merge, publish, distribute, sublicense, and/or
C@HDR@	sell copies of the Software, and to permit persons to whom
C@HDR@	the Software is furnished to do so, subject to the following
C@HDR@	conditions:
C@HDR@	
C@HDR@	The above copyright notice and this permission notice shall be
C@HDR@	included in all copies or substantial portions of the Software.
C@HDR@	
C@HDR@	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
C@HDR@	KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
C@HDR@	WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
C@HDR@	AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
C@HDR@	HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
C@HDR@	WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
C@HDR@	FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
C@HDR@	OTHER DEALINGS IN THE SOFTWARE.
C
Chist#	2026-02-17 - Christopher.M.Caldwell0@gmail.com - Created
C------------------------------------------------------------------------
Cdoc#	greebl.for - Multi-user game where the ballons are out to get you!
Cdoc#	Made with Roger Long's inspiration and Robert Kenney's HIPAK.MAC.
C------------------------------------------------------------------------
	SUBROUTINE DEFCOL

	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA

	CALL PCOLOR( ICLWHI )
	CALL PBACK( ICLBLA )
	RETURN
	END

	SUBROUTINE FMAIN

	IMPLICIT INTEGER ( A - Z )

	INTEGER FILSPC( 13 )		! WHERE RUN FROM
	INTEGER COMARA( 80 ), ILEN	! INPUT ARRAY FOR DATA FILE
	INTEGER PARARA( 40 ), PLEN	! PARARASED STUFF FOR INITDB
	INTEGER XDIR( 9 ), YDIR( 9 )
	INTEGER PLAYER
	INTEGER SCREEN,INUSE,POS,DIREXN,CONFLG
	INTEGER TYPE,USEFUL,CHAREP,RECOVR,WHOSEN,SCORE
	LOGICAL FIRING, REPING, INIFLG, NEW

	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA

	DATA SCREEN,INUSE,POS,DIREXN,CONFLG,
     &	TYPE,USEFUL,CHAREP,RECOVR,WHOSEN,SCORE
     &	    /1,2,3,4,5,6,7,8,9,10,11/
	DATA XDIR/-1,0,1,-1,0,1,-1,0,1/
	DATA YDIR/-1,-1,-1,0,0,0,1,1,1/
	DATA IGREBL/-1/, IPLAYR/-1/

	IF( ICLWHI .NE. 0 ) GOTO 3
	ICLWHI = 1
	ICLDBL = 2
	ICLRED = 3
	ICLLBL = 4
	ICLPUR = 5
	ICLGRE = 6
	ICLYEL = 7
	ICLBLA = 8

3	CALL SETTTY( COMARA, PAR, ILEN, PRIVD, FILSPC )
	CALL ENABLE
	CALL CHECK( INIFLG )
	IF( .NOT. INIFLG ) GOTO 10000

C***************************** INITDB *******************************

	CALL INIT( SCREEN, 18, 24, 80 )
	CALL DEFADR( 1, IRIGHT(ITBADR(SCREEN)) )
	CALL SETDIS( 1 )
	CALL CLRSCR
	CALL PBACK( ICLLBL )
	CALL PCOLOR( ICLLBL )
	CALL CURSOR( 1, 24 )
	CALL CHROUT('/')
	CALL REPEAT('-',78)
	CALL CHROUT('\')
	CALL CURSOR( 1, 3 )
	CALL CHROUT('\')
	CALL REPEAT('-',78)
	CALL CHROUT('/')
	DO 100 I = 1, 20
	    CALL CURSOR( 1, I+3 )
	    CALL CHROUT('|')
	    CALL CURSOR( 80, I+3 )
	    CALL CHROUT('|')
100	CONTINUE
	DO 200 I = 1, 200
150	    IX = IRAN( 80 )
	    IY = IRAN( 20 ) + 3
	    IF( ICHRAT(IX,IY) .NE. 32 ) GOTO 150
	    CALL CURSOR( IX, IY )
	    CALL CHROUT('*')
200	CONTINUE
	CALL PBACK( ICLBLA )
	CALL CURSOR( 1, 2 )
	CALL STRING('Time:^E')
	CALL CURSOR( 26, 2 )
	CALL STRING('Greeble kills:^E')
	CALL CURSOR( 51, 2 )
	CALL STRING('Player kills:^E')

	CALL INIT( INUSE, 1, 100 )
	DO 210 I = 1, 100
	    CALL PUTVAL( INUSE, I+0, 0 )
210	CONTINUE
	CALL INIT( POS, 7, 100, 2 )
	CALL INIT( DIREXN, 7, 100 )
	CALL INIT( CONFLG, 1, 100 )
	CALL INIT( TYPE, 6, 100 )
	CALL INIT( USEFUL, 36, 3 )
	CALL PUTVAL( USEFUL, 1, 0 )
	CALL PUTVAL( USEFUL, 2, 0 )
	CALL PUTVAL( USEFUL, 3, 0 )
	CALL INIT( CHAREP, 7, 100 )
	CALL INIT( RECOVR, 5, 100 )
	CALL INIT( WHOSEN, 7, 100 )
	CALL INIT( SCORE, 18, 100, 2 )
	CALL UNLOCK
	GOTO 10010
C***************************** SETUP ********************************

10000	CALL DEFADR( 1, IRIGHT(ITBADR(SCREEN)) )
C10000	CALL DEFSCR( 1, SCREEN )
10010	CALL SETDIS( 0 )
10020	CALL CTRAP
	    CALL EXPROG
	CALL STRING('^M^JInput character to represent player: ^B')
	CALL CHRWAT( ICHAR )
	CALL ENABLE
	CALL LOCK
	IF( ICHAR .GT. 90 ) ICHAR = ICHAR - 32
	IF( ICHAR .LT. 65 .OR. ICHAR .GT. 90 ) GOTO 10030
	DO 10025 I = 100, 1, -1
	    CALL GETVAL( INUSE, I+0, IVAL )
	    IF( IVAL .EQ. 1 ) GOTO 10023
	    PLAYER = I
	    GOTO 10025

10023	    CALL GETVAL( CHAREP, I+0, IVAL )
	    IF( IVAL .EQ. ICHAR ) GOTO 10030
10025	CONTINUE
	GOTO 10040

10030	CALL UNLOCK
	CALL STRING('^M^JCharacter in use.  ^E')
	GOTO 10020

10040	CALL PUTVAL( INUSE, PLAYER, 1 )
	CALL PUTVAL( CHAREP, PLAYER, ICHAR )
	CALL PUTVAL( POS, PLAYER, 1, 127 )
	CALL PUTVAL( POS, PLAYER, 2, 127 )
	CALL PUTVAL( TYPE, PLAYER, 1 )
	CALL PUTVAL( DIREXN, PLAYER, 5 )
	CALL PUTVAL( CONFLG, PLAYER, 0 )
	CALL PUTVAL( RECOVR, PLAYER, 0 )
	CALL PUTVAL( SCORE, PLAYER, 1, 0 )
	CALL PUTVAL( SCORE, PLAYER, 2, 0 )
	CALL UNLOCK
	CALL SETDIS( 1 )
	CALL NEWSCR( SCREEN )
	NEW = .FALSE.

10050	IX = IRAN( 80 )
	IY = IRAN( 20 ) + 3
	IF( ICHRAT( IX, IY ) .NE. 32 ) GOTO 10050
	CALL LOCK
	CALL CURSOR( IX, IY )
	CALL PUTVAL( POS, PLAYER, 1, IX )
	CALL PUTVAL( POS, PLAYER, 2, IY )
	CALL PBACK( ICLBLA )
	CALL PCOLOR( ICLWHI )
	CALL CHROUT( ICHAR )
	CALL UNLOCK
	CALL GRAFON
	CALL CTRAP
	    CALL CEASE( .FALSE. )
C****************************** COMMANDS ****************************

10100	IF( NEW ) CALL NEWSCR( SCREEN )
	IF( .NOT. NEW ) CALL UPDATE( SCREEN )
	NEW = .FALSE.
	CALL GETVAL( INUSE, PLAYER, IVAL )
	IF( IVAL .NE. 1 ) CALL CEASE( .TRUE. )
	CALL SETDIS( 0 )
	CALL GETVAL( SCORE, PLAYER, 1, IVAL )
	IF( IVAL .EQ. IGREBL ) GOTO 10102
	CALL CURSOR( 41, 2 )
	CALL NUMBER( IVAL )
	IGREBL = IVAL
10102	CALL GETVAL( SCORE, PLAYER, 2, IVAL )
	IF( IVAL .EQ. IPLAYR ) GOTO 10103
	CALL CURSOR( 65, 2 )
	CALL NUMBER( IVAL )
	IPLAYR = IVAL
10103	CALL SETDIS( 1 )
10110	CALL CHRBUF( ICHAR )
	IF( ICHAR .EQ. -1 ) GOTO 20000
	IF( REPING .AND. ICHAR .GT. 48 .AND. ICHAR .LE. 57 ) GOTO 10300
	CALL PUTVAL( CONFLG, PLAYER, 0 )
	CALL PUTVAL( DIREXN, PLAYER, 5 )
	REPING = .FALSE.
	IF( FIRING .AND. ICHAR .GT. 48 .AND. ICHAR .LE. 57 ) GOTO 10200
	FIRING = .FALSE.
	IF( ICHAR .GT. 48 .AND. ICHAR .LE. 57 ) GOTO 10300
	ICHAR = ICON( ICHAR )
	CALL ALLCAP( ICHAR, 1 )
	IF( ICHAR .EQ. 'F' ) FIRING = .TRUE.
	IF( ICHAR .EQ. '.' ) FIRING = .TRUE.
	IF( ICHAR .EQ. 'R' ) REPING = .TRUE.
	IF( ICHAR .EQ. '0' ) REPING = .TRUE.
	IF( ICHAR .EQ. 'N' ) NEW = .TRUE.
	IF( ICHAR .EQ. 'E' ) CALL CEASE( .FALSE. )
	GOTO 10110

10200	CONTINUE
	FIRING = .FALSE.
	IF( ICHAR .EQ. 53 ) GOTO 10110
	CALL GETVAL( RECOVR, PLAYER, IVAL )
	IF( IVAL .GT. 0 ) GOTO 10110
	CALL GETVAL( POS, PLAYER, 1, IX )
	CALL GETVAL( POS, PLAYER, 2, IY )
	IDIR = ICHAR-48
	CALL TORP
	CALL PUTVAL( WHOSEN, ITORP, PLAYER )
	CALL PUTVAL( RECOVR, PLAYER, 5 )
	GOTO 10110

10300	CONTINUE
	CALL PUTVAL( DIREXN, PLAYER, ICHAR-48 )
	CALL PUTVAL( CONFLG, PLAYER, 0 )
	IF( REPING ) CALL PUTVAL( -1, 1 )
	REPING = .FALSE.
	GOTO 10110
C****************************** MOVES *******************************

20000	CALL LOCK
	CALL GETVAL( USEFUL, 1, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 20001
	CALL UNLOCK
	CALL NAP( 250, 4 )
	GOTO 10100

20001	CALL PUTVAL( USEFUL, 1, 1 )
	CALL UNLOCK
	CALL NAP( 250, 4 )
	CALL GETVAL( USEFUL, 3, IVAL )
	CALL ADDVAL( -1, 1 )
	CALL COLCUR( 7, 2 )
	CALL NUMBER( IVAL, -6 )
	IF( MOD( IVAL, 250 ) .EQ. 0 ) CALL MAKMON
	DO 20100 I = 1, 100
	    IOBJ = I
	    CALL GETVAL( INUSE, IOBJ, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 20100
	    CALL GETVAL( RECOVR, IOBJ, IVAL )
	    IF( IVAL .LE. 0 ) GOTO 20002
	    CALL ADDVAL( -1, -1 )
	    GOTO 20100

20002	    CALL GETVAL( TYPE, IOBJ, ITYPE )
	    CALL GETVAL( DIREXN, IOBJ, IDIR )
	    CALL GETVAL( POS, IOBJ, 1, IX )
	    CALL GETVAL( POS, IOBJ, 2, IY )
	    IF( ITYPE .NE. 2 ) GOTO 20010
	    JOBJ = IDIR
	    IVAL = 0
	    IF( JOBJ .NE. 0 ) CALL GETVAL( INUSE, JOBJ, IVAL )
	    IF( IVAL .NE. 0 ) CALL GETVAL( TYPE, JOBJ, IVAL )
	    IF( IVAL .EQ. 1 ) GOTO 20005
	    J = 0
20003	    J = J + 1
	    IF( J .GT. 30 ) GOTO 20100
	    JOBJ = IRAN( 100 )
	    CALL GETVAL( INUSE, JOBJ, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 20003
	    CALL GETVAL( TYPE, JOBJ, IVAL )
	    IF( IVAL .NE. 1 ) GOTO 20003
	    CALL PUTVAL( DIREXN, IOBJ, JOBJ )
20005	    CALL GETVAL( POS, JOBJ, 1, IMX )
	    IF( IMX .GT. 100 ) GOTO 20003
	    CALL GETVAL( POS, JOBJ, 2, IMY )
	    IDIR = ISGN(IMX-IX) + 3*ISGN(IMY-IY) + 5
	    IF( IMX.NE.IX .AND. IMY.NE.IY .AND. IMX-IX.NE.IMY-IY
     &		.AND. IX-IMX.NE.IMY-IY ) GOTO 20010
	    CALL TORP
	    CALL PUTVAL( WHOSEN, ITORP, IOBJ )
	    CALL PUTVAL( RECOVR, IOBJ, 6 )
	    GOTO 20100

20010	    IF( IDIR .EQ. 5 ) GOTO 20100
	    CALL GETVAL( CHAREP, IOBJ, ICHAR )
	    INX = IX + XDIR( IDIR )
	    INY = IY + YDIR( IDIR )
	    INCHAR = ICHRAT( INX, INY )
	    IF( INCHAR .EQ. 32 ) GOTO 20050
	    IF( INCHAR .EQ. 42 .AND. ITYPE .EQ. 2 )
     &		CALL PUTVAL( RECOVR, IOBJ, 10 )
	    IF( INCHAR .EQ. 42 .AND. ITYPE .EQ. 2 ) GOTO 20050
	    CALL PUTVAL( CONFLG, IOBJ, 0 )
	    CALL PUTVAL( DIREXN, IOBJ, 5 )
	    IF( ITYPE .NE. 3 ) GOTO 20100
	    IF( INCHAR .EQ. 42 ) GOTO 20020
	    IF( (INCHAR.LE.64 .OR. INCHAR.GE.91) .AND.
     &		INCHAR.NE.46 .AND. INCHAR.NE.64) GOTO 20025
	    DO 20013 J = 1, 100
		JOBJ = J
		CALL GETVAL( INUSE, JOBJ, IVAL )
		IF( IVAL .EQ. 0 ) GOTO 20013
		CALL GETVAL( POS, JOBJ, 1, IVAL )
		IF( IVAL .NE. INX ) GOTO 20013
		CALL GETVAL( POS, JOBJ, 2, IVAL )
		IF( IVAL .EQ. INY ) GOTO 20015
20013	    CONTINUE
20015	    CONTINUE
	    CALL PUTVAL( INUSE, JOBJ, 0 )
	    IF( INCHAR .EQ. 46 ) GOTO 20020
	    CALL GETVAL( WHOSEN, IOBJ, JOBJ )
	    CALL GETVAL( INUSE, JOBJ, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 20020
	    CALL GETVAL( TYPE, JOBJ, IVAL )
	    IF( IVAL .NE. 1 ) GOTO 20020
	    IF( INCHAR .EQ. 64 ) CALL ADDVAL( SCORE, JOBJ, 1, 1 )
	    IF( INCHAR .NE. 64 ) CALL ADDVAL( SCORE, JOBJ, 2, 1 )
20020	    CALL CURSOR( INX, INY )
	    CALL PBACK( ICLBLA )
	    CALL CHROUT(' ')
	    IF( INCHAR .NE. 64 ) GOTO 20025
	    CALL ADDVAL( USEFUL, 2, -1 )
	    IF( NUSER(0) .LE. 1 ) CALL MAKMON
20025	    CALL PUTVAL( INUSE, IOBJ, 0 )
	    IF( ICHRAT( IX, IY ) .NE. ICHAR ) GOTO 20100
	    CALL CURSOR( IX, IY )
	    CALL PBACK( ICLBLA )
	    CALL CHROUT(' ')
	    GOTO 20100

20050	    CALL CURSOR( IX, IY )
	    IF(ICHRAT(IX,IY).NE.ICHAR) GOTO 20055
	    CALL PBACK( ICLBLA )
	    CALL CHROUT(' ')
20055	    CALL PUTVAL( POS, IOBJ, 1, INX )
	    CALL PUTVAL( POS, IOBJ, 2, INY )
	    CALL CURSOR( INX, INY )
	    CALL PBACK( ICLBLA )
	    IF( ICHAR .EQ. '.' ) CALL PCOLOR( ICLRED )
	    IF( ICHAR .EQ. '@' ) CALL PCOLOR( ICLYEL )
	    IF( ICHAR.GT.'A' .AND. ICHAR.LE.'Z' ) CALL PCOLOR(ICLWHI)
	    CALL CHROUT( ICHAR )
	    CALL GETVAL( CONFLG, IOBJ, IVAL )
	    IF( IVAL .EQ. 0 ) CALL PUTVAL( DIREXN, IOBJ, 5 )
20100	CONTINUE
	CALL PUTVAL( USEFUL, 1, 0 )
	GOTO 10100
	ENTRY TORPH

	ITORP = IFIND(0)
	IF( ITORP .EQ. 0 ) GOTO 30290

	CALL PUTVAL( POS, ITORP, 1, IX )
	CALL PUTVAL( POS, ITORP, 2, IY )
	CALL PUTVAL( TYPE, ITORP, 3 )
	CALL PUTVAL( CHAREP, ITORP, 46 )
	CALL PUTVAL( DIREXN, ITORP, IDIR )
	CALL PUTVAL( CONFLG, ITORP, 1 )
30290	CALL UNLOCK
	RETURN
	ENTRY IFINDR( IOBJP )

	CALL LOCK
	DO 40100 IOBJP = 1, 100
	    CALL GETVAL( INUSE, IOBJP+0, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 40200
40100	CONTINUE
	IOBJP = 0
	RETURN

40200	CALL PUTVAL( -1, 1 )
	CALL PUTVAL( RECOVR, IOBJP, 0 )
	RETURN
	ENTRY MAKEMO

	IMON = IFIND(0)
	IF( IMON .EQ. 0 ) CALL UNLOCK
	IF( IMON .EQ. 0 ) RETURN
50100	IMX = IRAN( 80 )
	IMY = IRAN( 20 ) + 3
	IF( ICHRAT( IMX, IMY ) .NE. 32 ) GOTO 50100
	CALL CURSOR( IMX, IMY )
	CALL PBACK( ICLBLA )
	CALL PCOLOR( ICLYEL )
	CALL CHROUT( '@' )
	CALL PUTVAL( POS, IMON, 1, IMX )
	CALL PUTVAL( POS, IMON, 2, IMY )
	CALL PUTVAL( DIREXN, IMON, 0 )
	CALL PUTVAL( CONFLG, IMON, 0 )
	CALL PUTVAL( TYPE, IMON, 2 )
	CALL PUTVAL( CHAREP, IMON, 64 )
	CALL ADDVAL( USEFUL, 2, 1 )
	CALL UNLOCK
	RETURN
	ENTRY KILCHR

	CALL UNLOCK
	CALL LOCK
	CALL GETVAL( POS, PLAYER, 1, IX )
	CALL GETVAL( POS, PLAYER, 2, IY )
	CALL CURSOR( IX, IY )
	CALL CHROUT(' ')
	CALL PUTVAL( INUSE, PLAYER, 0 )
	CALL UNLOCK
	RETURN
	END
	SUBROUTINE CEASE( IFLAG )
	LOGICAL IFLAG
	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA
	CALL ENABLE
	IF( .NOT. IFLAG ) CALL KILCHR
	CALL GRAFOF
	CALL SETDIS( 0 )
	CALL CLRSCR
	CALL CURSOR( 1, 24 )
	IF( IFLAG ) CALL COLSTR(ICLRED,
     & 'You have been hit by a bullet.^M^J^E')
	CALL CLOSE( 1 )
C
C	This will never work anywhere other than under Tops10
	IF( JOB(1) .NE. 0 ) CALL EXECUT( "051440000000 )
C
	CALL EXPROG
	END

	SUBROUTINE TORP
	CALL TORPH
	RETURN
	END

	INTEGER FUNCTION IFIND( DUMMY )
	CALL IFINDR( IFIND )
	RETURN
	END

	SUBROUTINE MAKMON
	CALL MAKEMO
	RETURN
	END

	SUBROUTINE COLCUR( IX, IY )
	CALL DEFCOL
	CALL CURSOR( IX, IY )
	RETURN
	END

    	SUBROUTINE COLSTR( ICOL, MSGARA )
	INTEGER MSGARA( 16 )
	CALL PCOLOR( ICOL )
	CALL STRING( MSGARA )
	RETURN
	END
