Cindx#	cave.for - A multi-user game to wander around in a cave made up of hexagons and monsters
C@HDR@	$Id$
C@HDR@
C@HDR@	Copyright (c) 1982-2026 Christopher Caldwell (Christopher.M.Caldwell0@gmail.com)
C@HDR@
C@HDR@	Permission is hereby granted, free of charge, to any person
C@HDR@	obtaining a copy of this software and associated documentation
C@HDR@	files (the "Software"), to deal in the Software without
C@HDR@	restriction, including without limitation the rights to use,
C@HDR@	copy, modify, merge, publish, distribute, sublicense, and/or
C@HDR@	sell copies of the Software, and to permit persons to whom
C@HDR@	the Software is furnished to do so, subject to the following
C@HDR@	conditions:
C@HDR@	
C@HDR@	The above copyright notice and this permission notice shall be
C@HDR@	included in all copies or substantial portions of the Software.
C@HDR@	
C@HDR@	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
C@HDR@	KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
C@HDR@	WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
C@HDR@	AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
C@HDR@	HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
C@HDR@	WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
C@HDR@	FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
C@HDR@	OTHER DEALINGS IN THE SOFTWARE.
C
Chist#	2026-02-17 - Christopher.M.Caldwell0@gmail.com - Created
C------------------------------------------------------------------------
Cdoc#	cave.for - A multi-user game to wander around in a cave made up of hexagons and monsters
Cdoc#	In some ways based on the old Gygax Dungeons and Dragons.
Cdoc#	Made with Roger Long's inspiration and Robert Kenney's HIPAK.MAC.
C------------------------------------------------------------------------
	SUBROUTINE DEFCOL

	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA

	CALL PCOLOR( ICLWHI )
	CALL PBACK( ICLBLA )
	RETURN
	END

	LOGICAL FUNCTION STREQ( SIX1, SIX2 )

	IMPLICIT INTEGER ( A - Z )
	INTEGER CHK1(6), CHK2(6)


	STREQ = ( SIX1 .EQ. SIX2 )
	IF( JOB(-1) .NE. 0 ) RETURN
	CALL CONVRT( SIX1, 6, 6, CHK1, 1 )
	CALL ALLCAP( CHK1, 6 )
	CALL CONVRT( SIX2, 6, 6, CHK2, 1 )
	CALL ALLCAP( CHK2, 6 )
	DO 100 I = 1, 6
	    STREQ = ( CHK1(I) .EQ. CHK2(I) )
	    IF( CHK1(I) .EQ. 0 .OR. .NOT. STREQ ) RETURN
100	CONTINUE
	RETURN
	END


	SUBROUTINE INITDB( COMARA, PARARA, FILESP )

	IMPLICIT INTEGER ( A - Z )

	INTEGER COMARA(80), PARARA(40), FILESP(13), SIXARA(4)
	LOGICAL ERROR, IEOF
	INTEGER MAXWSZ

	DATA NUMBRM/1250/
	DATA MAXWSZ/6/

	IF( JOB(-1) .EQ. 0 ) MAXWSZ = 20

C	OPEN UP THE VOCABULARY DATA FILE
	FILESP( 5 ) = ISXBIT('DAT')
	CALL OFILE( 2, FILESP, 0 )
	IF( ERROR(0) )  CALL EXPROG
	CALL RFILE( 2, FILESP )
	IF( ERROR(0) )  CALL EXPROG
100	CALL GETSTR( COMARA, 80, ILEN, 2, IEOF )
	IF( IEOF )  CALL EXPROG
	IF( ILEN .LE. 0 .OR. COMARA(1) .EQ. ';' ) GOTO 100
	CALL GETNUM( COMARA, ILEN, NVERBS, 10, NOBJ, 10 )

C	ARRAY #1 IS THE MASTER ARRAY WITH ALL THE PTR'S TO ARRAY #2
C	VALUE		MEANS
C	0		ROCK
C	1-510		POINTERS
C	511		NOTHING
	CALL INIT( 1, 9, 50, 50, 4 )
C
C	ARRAY #2 CONSISTS OF A LIST OF POINTERS AND CONTAINS
C	ALL THE THINGS STORED AT A LOCATION (AT MOST 10)
	CALL INIT( 2, 9, 510, 11 )
C
C	ARRAY #3 CONSISTS OF THE NAMES OF THE ITEMS
	CALL INIT( 3, 36, 100 )
C
C	ARRAY #4 CONSISTS OF THE WEIGHTS OF THE ITEMS
	CALL INIT( 4, 18, 510 )
C
C	ARRAY #5 CONSISTS OF POINTERS FOR ITEMS THAT STORE THINGS
C	OR A 511 IF IT CAN'T BE USED TO STORE THINGS
	CALL INIT( 5, 9, 510 )
C
C	ARRAY #6 DAMAGE ARRAY
	CALL INIT( 6, 10, 52, 4 )
C
C	ARRAY #7 CONTAINS JOB NUMBERS AND EXPERIENCE FOR PLAYERS
	CALL INIT( 7, 18, 26, 2 )
C
C	ARRAY #8 CONTAINS WHICH DIRECTION PLAYER IS POINTING
	CALL INIT( 8, 3, 52 )
C
C	ARRAY #9 CONTAINS ALL VERBS
	CALL INIT( 9, 36, 3*NVERBS/2 )
C
C	ARRAY #10 TELLS IF INDEX IS IN USE
	CALL INIT( 10, 1, 510 )
C
C	ARRAY #11 CONSISTS OF THE INDICES TO STUFF IN THE STORE
	CALL INIT( 11, 9, 80 )
C
C	ARRAY #12 CONSISTS OF THE POINTERS TO THE NAMES OF INDICES
	CALL INIT( 12, 7, 510 )
C
C	ARRAY #13 CONSISTS OF COST OF EACH KIND OF ITEM
	CALL INIT( 13, 12, 100 )
C
C	ARRAY #14 CONSISTS OF WEIGHT TYPE OF ITEM CAN CARRY
	CALL INIT( 14, 18, 100 )
C
C	ARRAY #15 CONSISTS OF ITEM TYPE (WHERE IT GOES)
	CALL INIT( 15, 3, 100 )
C
C	ARRAY #16 CONTAINS FLAGS (1 = STAIRWAY BETWEEN FLOORS)
	CALL INIT( 16, 1, 50, 50, 4 )
C
C	ARRAY #17 CONTAINS DAMAGE FACTOR FOR EACH TYPE OF ITEM
	CALL INIT( 17, 7, 100 )
C
C	ARRAY #18 CONTAINS STRENGTH REQUIRED TO USE OBJECT
	CALL INIT( 18, 4, 100 )
C
C	ARRAY #19 CONTAINS X, Y AND Z POSITION OF PLAYER
	CALL INIT( 19, 6, 52, 3 )
C
C	ARRAY #20 CONTAINS SOURCE, VOLUME, LENGTH AND MESSAGE
C	AND WHO WON THE GAME.
	CALL INIT( 20, 7, 75 )
C
C	ARRAY #21 FLAG INDICATING SUCCESS OF ATTACK
	CALL INIT( 21, 3, 52 )
C
C	ARRAY #22 IS A LIST OF PROGRAMMER NUMBERS AND
C	THE AMOUNT OF MONEY THEY HAVE LEFT TO SPEND.
	CALL INIT( 22, 18, 100, 2 )
C
C	ARRAY #23 CONTAINS DESIRED ALLY SETUPS
	CALL INIT( 23, 1, 26, 26 )
C
C	ARRAY #24 CONTAINS WHAT TYPE WEAPON (HIT, THROWN, FIRED)
	CALL INIT( 24, 2, 100 )
C
C	ARRAY #25 CONTAINS STANDARD WEIGHT FOR MONSTERS
	CALL INIT( 25, 18, 26 )
C
C	ARRAY #26 CONTAINS STANDARD DEXTERITY FOR MONSTERS
	CALL INIT( 26, 6, 26 )
C
C	ARRAY #27 CONTAINS STANDARD & ACTUAL STRENGTH FOR MONSTERS
	CALL INIT( 27, 6, 26, 2 )
C
C	ARRAY #28 CONTAINS PERCENTAGE OF
C	BITING, CLAWING, BURNING, HITTING AND SMOTHERING ATTACKS / 5
	CALL INIT( 28, 5, 26, 5 )
C
C	ARRAY #29 CONTAINS NUMBER OF HEXES THAT MONSTER OCCUPIES
	CALL INIT( 29, 5, 26 )
C
C	ARRAY #30 CONTAINS THE MONSTER'S PREFERENCE OF FLOORS - 1
	CALL INIT( 30, 2, 26 )
C
C	ARRAY #31 CONTAINS THE DIRECTION TO THE CURRENT HEX OF MONSTER
	CALL INIT( 31, 3, 26, 20 )
C
C	ARRAY #32 CONTAINS AMOUNT OF TIME TO RECOVER
	CALL INIT( 32, 6, 52 )
C
C	ARRAY #33 CONTAINS NUMBER TIMES DISI HAS BEEN HANDLED
	CALL INIT( 33, 36, 1 )

	DO 400 Z = 1, 4
	    X = IRAN( 48 ) + 1
	    Y = IRAN( 48 ) + 1
	    DIR = IRAN( 6 )
	    IPASS = 1
	    DO 400 I = 1, NUMBRM
		IF( IPASS .GT. 0 )  DIR = IRAN( 6 )
200		CALL NEWXY( X, Y, DIR, NX, NY )
		IF( NX .GT. 1 .AND. NX .LT. 50 .AND. NY .GT. 1 .AND.
     &			NY .LT. 50 ) GOTO 300
		IPASS = 1
		GOTO 400
300		X = NX
		Y = NY
		CALL PUTVAL( 1, X, Y, Z+0, 511 )
		IF( IRAN(10) .EQ. 1 )  IPASS = -IPASS
400	CONTINUE

	DO 600 ZTEMP = 1, 4
	    Z = ZTEMP
500	    X = IRAN( 50 )
	    Y = IRAN( 50 )
	    CALL GETVAL( 1, X, Y, Z, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 500
	    IF( Z .NE. 4 )CALL GETVAL( 1, X, Y, Z+1, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 500
	    CALL PUTVAL( 16, X, Y, Z, 1 )
600	CONTINUE

	I = 0
700	CALL GETSTR( COMARA, 80, ILEN, 2, IEOF )
	    IF( IEOF )  CALL EXPROG
	    IF( ILEN .EQ. 0 .OR. COMARA(1) .EQ. ';' ) GOTO 700
	    CALL PARSE( COMARA, ILEN, PARARA, LENGTH, 40 )
	    IF( LENGTH .EQ. 0 ) GOTO 700
	    DO 800 J = 1, LENGTH
		IF( PARARA(J) .EQ. ISXBIT('-') ) GOTO 700
		IF( PARARA(J) .EQ. ISXBIT('.') ) GOTO 900
		I = I + 1
		CALL PUTVAL( 9, I, PARARA(J) )
800	    CONTINUE
	    I = I + 1
	    CALL PUTVAL( 9, I, -1 )
	GOTO 700

900	I = 52
	J = 52
1000	CALL GETSTR( COMARA, 80, ILEN, 2, IEOF )
	IF( IEOF )  CALL EXPROG
	IF( ILEN .EQ. 0 .OR. COMARA(1) .EQ. ';' ) GOTO 1000
	IF( COMARA(1) .EQ. '.' ) GOTO 1400
C	CALL ALLCAP( COMARA, ILEN )
	I = I + 1
	DO 1100 I1 = 1, MAXWSZ 
	    IF( ICON(COMARA(I1)) .LE. 32 ) GOTO 1105
1100	CONTINUE
	I1 = MAXWSZ
1105	CALL CONVRT( COMARA, I1, 1, SIXARA, 6 )
	CALL PUTVAL( 3, I, SIXARA(1) )
	CALL GETNUM( COMARA,ILEN, TYPE,10, CANCAR,10, WEIGHS,10,
     & NUMOBJ,10, OCOST,10, IDAM,10, STRENG,10, ITWEAP,10 )
	CALL PUTVAL( 13, I, OCOST )
	CALL PUTVAL( 14, I, CANCAR )
	CALL PUTVAL( 15, I, TYPE )
	CALL PUTVAL( 17, I, IDAM )
	CALL PUTVAL( 18, I, STRENG )
	IF( ITWEAP .GT. 0 ) CALL PUTVAL( 24, I, ITWEAP )
1200	IF( NUMOBJ .EQ. 0 ) GOTO 1000
	NUMOBJ = NUMOBJ - 1
	J = J + 1
	IF( CANCAR .EQ. 0 )  CALL PUTVAL( 5, J, 511 )
	CALL PUTVAL( 4, J, WEIGHS )
	CALL PUTVAL( 10, J, 1 )
	CALL PUTVAL( 12, J, I )
	IF( J .GT. 132 ) GOTO 1300
	CALL PUTVAL( 11, J-52, J )
	GOTO 1200

1300	X = IRAN( 50 )
	Y = IRAN( 50 )
	Z = -ITWEAP
	IF( Z .LE. 0 )  Z = IRAN( 4 )
	CALL GETVAL( 1, X, Y, Z, IVAL )
	IF( IVAL .NE. 511 ) GOTO 1300
	CALL DROP( FAILED, .FALSE., X, Y, Z, J )
	GOTO 1200

1400	I = 0
1500	CALL GETSTR( COMARA, 80, ILEN, 2, IEOF )
	IF( IEOF ) CALL EXPROG
	IF( ILEN .EQ. 0 .OR. COMARA(1) .EQ. ';' ) GOTO 1500
	IF( COMARA(1) .EQ. '.' ) GOTO 1700
C	CALL ALLCAP( COMARA, ILEN )
	I = I + 1
	DO 1600 I1 = 1, MAXWSZ
	    IF( ICON(COMARA(I1)) .LE. 32 ) GOTO 1605
1600	CONTINUE
	I1 = MAXWSZ
1605	CALL CONVRT( COMARA, I1, 1, IVAL, 6 )
	CALL PUTVAL( 3, I+26, IVAL )
	CALL GETNUM( COMARA,ILEN, WEIGHS,10, DEX,10, STRENG,10,
     & BITE,10, CLAW,10, BURN,10, HIT,10, SMOTHR,10, NHEX,10,
     & IFLOOR,10 )
	CALL PUTVAL( 25, I, WEIGHS )
	CALL PUTVAL( 26, I, DEX )
	CALL PUTVAL( 27, I, 1, STRENG )
	CALL PUTVAL( 28, I, 1, BITE/5 )
	CALL PUTVAL( 28, I, 2, CLAW/5 )
	CALL PUTVAL( 28, I, 3, BURN/5 )
	CALL PUTVAL( 28, I, 4, HIT/5 )
	CALL PUTVAL( 28, I, 5, SMOTHR/5 )
	CALL PUTVAL( 29, I, NHEX )
	CALL PUTVAL( 30, I, IFLOOR-1 )
	GOTO 1500

1700	CALL CLOSE( 2 )
	CALL UNLOCK
	RETURN
	END
	SUBROUTINE NEWXY( OX, OY, DIR, NX, NY )

	IMPLICIT INTEGER ( A - Z )

	INTEGER XDIR(6), YDIR(6)
	DATA XDIR/0,1,1,0,-1,-1/, YDIR/-1,0,1,1,1,0/

	X = OX
	Y = OY
	NX = X + XDIR( DIR )
	IF( NX .LT. 1 .OR. NX .GT. 50 )  NX = 0
	NY = Y + YDIR( DIR )
	IF( MOD( X, 2 ) .NE. 0 .AND. XDIR( DIR ) .NE. 0 )  NY = NY - 1
	IF( NY .LT. 1 .OR. NY .GT. 50 )  NX = 0
	RETURN
	END
	INTEGER FUNCTION NEWDIR( DIR, INC )

	IMPLICIT INTEGER ( A - Z )

	NEWDIR = 0
	IF( DIR .EQ. 0 )  RETURN
	NEWDIR = DIR + INC
	IF( NEWDIR .LT. 1 )  NEWDIR = NEWDIR + 6
	IF( NEWDIR .GT. 6 )  NEWDIR = NEWDIR - 6
	RETURN
	END

	FUNCTION ICHCOD( ICHAR, IFG, IBG )
	IF( ICHAR .LT. 0 .OR. ICHAR .GT. 256 ) ICHAR = ICON( ICHAR )
	ICHCOD = IFG*256*256 + IBG*256 + ICHAR
	RETURN
	END

	SUBROUTINE UPDSCR(PLAYER,NEWSCR,STRENG,DEXTER,CANSEE,DISIND)

	IMPLICIT INTEGER ( A - Z )

	INTEGER SCRARA( 54, 21 ), OLDARA( 54, 21 )
	LOGICAL CANSEE( 52 ), NEWSCR, CHANGE, NEXT
	INTEGER TOLOAD( 4 )

	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA

	CALL GETVAL( 19, PLAYER, 1, X )
	CALL GETVAL( 19, PLAYER, 2, Y )
	CALL GETVAL( 19, PLAYER, 3, Z )
	CALL GETVAL( 8, PLAYER, DIR )

	DO 100 INDEX = 1, 52
	    CANSEE( INDEX ) = .FALSE.
	    IF( INDEX .GT. 26 ) GOTO 100
	    CALL GETVAL( 10, INDEX+0, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 100
	    CALL GETVAL( 8, INDEX+0, IVAL )
	    IF( IVAL .LT. 7 ) LPLAYR = INDEX
100	CONTINUE
	IF( LPLAYR .EQ. PLAYER ) CALL MONSTR

	YC = -1
	YC = 0 - MOD( X+1, 2 )
	DO 901 YTEMP = Y-4, Y+4
	    Y1 = YTEMP
	    YC = YC + 2
	    IF( Y1 .LT. 1 .OR. Y1 .GT. 50 ) GOTO 901
	    XC = -3
	    DO 900 XTEMP = X-6, X+6
		X1 = XTEMP
		XC = XC + 4
		IF( X1 .LT. 1 .OR. X1 .GT. 50 ) GOTO 900
		IF( X1 .EQ. X .AND. Y1 .EQ. Y ) GOTO 300
		NDIR = FINDIR( X, Y, X1+0, Y1+0 )
		CALL NEWXY( X, Y, NDIR, X2, Y2 )
		IF( X1 .EQ. X2 .AND. Y1 .EQ. Y2 ) GOTO 300
		IF(.NOT.(NDIR.EQ.NEWDIR(DIR,1).OR.NDIR.EQ.
     &		    NEWDIR(DIR,-1) .OR. NDIR .EQ. DIR) ) GOTO 900
		X2 = X
		Y2 = Y
200		NDIR = FINDIR( X2, Y2, X1+0, Y1+0 )
		CALL NEWXY( X2, Y2, NDIR, X2, Y2 )
		IF( X1 .EQ. X2 .AND. Y1 .EQ. Y2 ) GOTO 300
		CALL GETVAL( 1, X2, Y2, Z, IVAL )
		IF( IVAL .EQ. 0 ) GOTO 900
		GOTO 200

300		YA = YC + MOD( X1+1, 2 )
		CALL LOAD(SCRARA,ICLLBL,ICLDBL,XC,YA,'>','-','-','<')
		SCRARA( XC, YA+1 ) = ICHCOD('<',ICLLBL,ICLDBL)
		SCRARA( XC+5, YA+1 ) = ICHCOD('>',ICLLBL,ICLDBL)
		CALL LOAD(SCRARA,ICLLBL,ICLDBL,XC,YA+2,'>','-','-','<')
		CALL GETVAL( 1, X1+0, Y1+0, Z, IVAL )
		IF( IVAL .NE. 0 ) GOTO 400
		CALL LOAD(SCRARA,ICLGRE,ICLDBL,XC,YA+1,'#','#','#','#')
		GOTO 900

400		IF( IVAL .NE. 511 ) GOTO 600
		CALL LOAD(SCRARA,ICLLBL,ICLDBL,XC,YA+1,' ',' ',' ',' ')
		IF( Z .EQ. 1 ) GOTO 500
		CALL GETVAL( 16, X1+0, Y1+0, Z-1, IVAL )
		IF( IVAL .EQ. 0 ) GOTO 500
		SCRARA( XC+2, YA+1 ) = ICHCOD('D',ICLRED,ICLWHI)
		SCRARA( XC+3, YA+1 ) = ICHCOD('N',ICLRED,ICLWHI)

500		CALL GETVAL( 16, X1+0, Y1+0, Z, IVAL )
		IF( IVAL .EQ. 0 ) GOTO 900
		SCRARA( XC+2, YA+1 ) = ICHCOD('U',ICLDBL,ICLWHI)
		IF( MOD(SCRARA(XC+3,YA+1),256) .EQ. ICON('N') ) GOTO 505
		SCRARA( XC+3, YA+1 ) = ICHCOD('P',ICLDBL,ICLWHI)
		GOTO 900
505		SCRARA( XC+3, YA+1 ) = ICHCOD('D',ICLDBL,ICLWHI)
		GOTO 900

600		BEST = 0
		DO 700 IVAL1 = 1, 10
		    CALL GETVAL( 2, IVAL, IVAL1+0, INDEX )
		    IF( INDEX .EQ. 0 ) GOTO 700
		    IF( INDEX .LE. 52 ) CANSEE(INDEX) = .TRUE.
		    IVAL2 = WEIGHT( INDEX )
		    IF( IVAL2 .LT. BEST ) GOTO 700
		    BEST = IVAL2
		    BINDEX = INDEX
		    IF( INDEX .GT. 52 ) GOTO 700
		    CALL GETVAL( 19, INDEX, 1, AX )
		    CALL GETVAL( 19, INDEX, 2, AY )
		    IF( AX .NE. X1 .OR. AY .NE. Y1 ) BINDEX = -INDEX
700		CONTINUE
		IF( BINDEX .LT. 0 .OR. BINDEX .GT. 52 ) GOTO 800
		CALL GETVAL( 8, BINDEX, IVAL )
		SCRARA( XC+1, YA+1 ) = ICHCOD(' ',ICLLBL,ICLDBL)
		SCRARA( XC+4, YA+1 ) = ICHCOD(' ',ICLLBL,ICLDBL)
		ICOL = ICLPUR
		IF( BINDEX .GT. 26 ) ICOL = ICLRED
		IF( BINDEX .EQ. PLAYER ) ICOL = ICLWHI
		IF( BINDEX .GT. 26 .AND. IVAL .LT. 4 )
     &		    SCRARA( XC+1, YA+1 ) = ICHCOD('M',ICOL,ICLDBL)
		IF( BINDEX .GT. 26 .AND. IVAL .GE. 4 )
     &		    SCRARA( XC+3, YA+1 ) = ICHCOD('M',ICOL,ICLDBL)
		IF(BINDEX.LE.26)
     &		    IVAL1=ICHCOD(ICON(BINDEX+64),ICOL,ICLDBL)
		IF(BINDEX.GT.26)
     &		    IVAL1=ICHCOD(ICON(BINDEX+38),ICOL,ICLDBL)
		IF( IVAL .LT. 4 )  SCRARA( XC+2, YA+1 ) = IVAL1
		IF( IVAL .GE. 4 .AND. BINDEX .LE. 26 )
     &		    SCRARA( XC+3, YA+1 ) = IVAL1
		IF( IVAL .GE. 4 .AND. BINDEX .GT. 26 )
     &			SCRARA( XC+4, YA+1 ) = IVAL1
		IF(IVAL.EQ.0)SCRARA(XC+3,YA+1)=ICHCOD('=',ICOL,ICLDBL)
		IF(IVAL.EQ.1)SCRARA(XC+3,YA+1)=ICHCOD('.',ICOL,ICLDBL)
		IF(IVAL.EQ.2)SCRARA(XC+3,YA+1)=ICHCOD('\',ICOL,ICLDBL)
		IF(IVAL.EQ.3)SCRARA(XC+3,YA+1)=ICHCOD('/',ICOL,ICLDBL)
		IF(IVAL.EQ.4)SCRARA(XC+2,YA+1)=ICHCOD('^',ICOL,ICLDBL)
		IF(IVAL.EQ.5)SCRARA(XC+2,YA+1)=ICHCOD('\',ICOL,ICLDBL)
		IF(IVAL.EQ.6)SCRARA(XC+2,YA+1)=ICHCOD('/',ICOL,ICLDBL)
		GOTO 900

800		ICOL = ICLWHI
		IBACK = ICLDBL
		IF( BINDEX .LT. 0 ) ICOL = ICLRED
		BINDEX = IABS(BINDEX)
		CALL GETVAL( 12, BINDEX, TINDEX )
		CALL GETVAL( 13, TINDEX, OCOST )
		IF( OCOST .LE. 500 .AND. TINDEX .NE. DISIND ) GOTO 850
		ICOL = ICLBLA
		IBACK = ICLYEL
850		CALL GETVAL( 3, TINDEX, I1 )
		CALL CONVRT( I1, 4, 6, TOLOAD, 0 )
		CALL LOAD(SCRARA,ICOL,IBACK,XC,YA+1,
     &		    TOLOAD(1),TOLOAD(2),TOLOAD(3),TOLOAD(4))
900	CONTINUE
901	CONTINUE

	IF( .NOT. NEWSCR ) GOTO 1000
	CALL CLRSCR
	CALL COLCUR( 55, 23 )
	CALL STRING('Head:^E')
	CALL CURSOR( 55, 22 )
	CALL STRING('Body:^E')
	CALL CURSOR( 55, 21 )
	CALL STRING('Back:^E')
	CALL CURSOR( 55, 20 )
	CALL STRING('Weapon arm:^E')
	CALL CURSOR( 55, 19 )
	CALL STRING('Shield arm:^E')
	CALL CURSOR( 55, 18 )
	CALL STRING('Belt:^E')
	CALL CURSOR( 55, 12 )
	CALL STRING('Strength:^E')
	CALL CURSOR( 55, 11 )
	CALL STRING('Dexterity: ^E')
	CALL CURSOR( 67, 8 )
	CALL CHROUT('4')
	CALL CURSOR( 63, 7 )
	CALL CHROUT('5')
	CALL CURSOR( 71, 7 )
	CALL CHROUT('3')
	CALL CURSOR( 67, 6 )
	CALL CHROUT( PLAYER+64 )
	CALL CURSOR( 63, 5 )
	CALL CHROUT('6')
	CALL CURSOR( 71, 5 )
	CALL CHROUT('2')
	CALL CURSOR( 67, 4 )
	CALL CHROUT('1')
	CALL CURSOR( 1, 1 )
	CALL CHROUT('>')

1000	CHANGE = .FALSE.
	IUNSEN = ICHCOD(' ',ICLWHI,ICLBLA)
	LASTBG=0
	LASTFG=0
	DO 1200 Y1 = 1, 20
	    NEXT = .FALSE.
	    DO 1200 X1 = 1, 54
		IF( NEWSCR ) OLDARA(X1,Y1) = ICHCOD(' ',ICLWHI,ICLBLA)
		ITEM = SCRARA(X1,Y1)
		IF( ITEM .NE. 0 ) GOTO 1050
		ITEM = IUNSEN
		SCRARA(X1,Y1) = ITEM
1050		IF( SCRARA( X1, Y1 ) .EQ. OLDARA( X1, Y1 ) ) GOTO 1100
		CHANGE = .TRUE.
		IF( .NOT. NEXT )  CALL CURSOR( X1+0, Y1+4 )
		NEXT = .TRUE.
		ICHAR = MOD( ITEM, 256 )
		IBG = MOD( ITEM/256, 256 )
		IFG = ITEM / 256 / 256
		IF( LASTBG .NE. IBG ) CALL PBACK( IBG )
		IF( LASTFG .NE. IFG ) CALL PCOLOR( IFG )
		CALL CHROUT( ICHAR )
		LASTBG = IBG
		LASTFG = IFG
		OLDARA( X1, Y1 ) = SCRARA( X1, Y1 )
1100		SCRARA( X1, Y1 ) = IUNSEN
		NEXT = .FALSE.
1200	CONTINUE

	IF( CHANGE .AND. .NOT. NEWSCR .AND. DIR .EQ. 0 ) CALL CHROUT(7)

	IF( STRENG .EQ. OSTREN .AND. .NOT. NEWSCR ) GOTO 1300
	CALL COLCUR( 67, 12 )
	CALL NUMBER( STRENG, 2 )
	OSTREN = STRENG
1300	IF( DEXTER .EQ. ODEXTR .AND. .NOT. NEWSCR )  RETURN
	CALL COLCUR( 67, 11 )
	CALL NUMBER( DEXTER, 2 )
	ODEXTR = DEXTER
	RETURN
	END
	FUNCTION FINDIR( X1, Y1, X2, Y2 )

	IMPLICIT INTEGER ( A - Z )

	IF( X1 .NE. X2 ) GOTO 100
	FINDIR = 1
	IF( Y1 .LT. Y2 )  FINDIR = 4
	RETURN

100	IF( X1 .GT. X2 ) GOTO 200
	IF( Y1 .GT. Y2 )  FINDIR = 2
	IF( Y1 .EQ. Y2 )  FINDIR = 2 + MOD( X1, 2 )
	IF( Y1 .LT. Y2 )  FINDIR = 3
	RETURN

200	IF( Y1 .LT. Y2 )  FINDIR = 5
	IF( Y1 .EQ. Y2 )  FINDIR = 6 - MOD( X1, 2 )
	IF( Y1 .GT. Y2 )  FINDIR = 6
	RETURN
	END
	SUBROUTINE LOAD( SCRARA, IFG, IBG, X, Y, I1, I2, I3, I4 )

	IMPLICIT INTEGER ( A - Z )

	INTEGER SCRARA( 54, 21 )

	SCRARA(X+1,Y) = ICHCOD(I1,IFG,IBG)
	SCRARA(X+2,Y) = ICHCOD(I2,IFG,IBG)
	SCRARA(X+3,Y) = ICHCOD(I3,IFG,IBG)
	SCRARA(X+4,Y) = ICHCOD(I4,IFG,IBG)
	RETURN
	END
	SUBROUTINE COMAND( ICHAR, COMARA, ARRIND )
C
C  --	ROUTINE GET COMMAND FROM USER IF ONE PRESENT.
C
	INTEGER COMARA(81), INDEX, ARRIND, ICHAR
	DATA INDEX/0/
C
C  --	IF THERE IS A CHARACTER OUT GET IT, ELSE, SLEEP FOR
C  --	0.5 SECONDS OR UNTIL ONE IS.
C
100	CALL CURBUF
	CALL NAP( 500, "14 )
	CALL CHRBUF( ICHAR )
	IF( ICHAR .EQ. -1 )  RETURN
	IF( ICHAR .EQ. "10 .OR. ICHAR .EQ. "177 ) GOTO 300
	IF( ICHAR .EQ. "25 ) GOTO 400
	IF( ICHAR .EQ. "33 .AND. INDEX .EQ. 0 ) GOTO 200
	IF( ICHAR .LT. "40 ) GOTO 600
	IF( INDEX .GE. 78 ) GOTO 700
C
C  --	NOT SPECIAL CHARACTER, PUT IN ARRAY
C
	INDEX = INDEX + 1
	CALL COLCUR( 1 + INDEX, 1 )
	CALL CHROUT( ICHAR )
	COMARA(INDEX) = ICON( ICHAR )
	GOTO 100
C
C  --	ESCAPE:  REPEAT LAST COMMAND
C
200	INDEX = INDSTR
	CALL COLCUR( 2, 1 )
	IF( INDEX .NE. 0 )CALL STRING( COMARA, 1, INDEX )

	GOTO 600
C
C  --	DELETE CHARACTER
C
300	INDEX = INDEX - 1
	IF( INDEX .LT. 0 )  INDEX = 0
	CALL COLCUR( 2 + INDEX, 1 )
	CALL CHROUT( ' ' )
	GOTO 100
C
C  --	DELETE LINE
C
400	CALL COLCUR( 2, 1 )
	DO 500 I = 1, INDEX
	    CALL CHROUT(' ')
500	CONTINUE
	INDEX = 0
	GOTO 100
C
C  --	CARRIAGE RETURN TYPED
C
600	IF( INDEX .NE. 0 ) GOTO 700
	ICHAR = -1
	GOTO 900
700	COMARA(INDEX + 1) = 0
	CALL COLCUR( 2, 1 )
	DO 800 I = 1, INDEX
	CALL CHROUT(' ')
800	CONTINUE
C	CALL ALLCAP( COMARA, INDEX )
	ICHAR = COMARA(1)
900	ARRIND = INDEX
	INDSTR = INDEX
	INDEX = 0
	CALL NAP( 500, 4 )
	RETURN
	END
	SUBROUTINE BUGMSG( MSGARA, N1, N2, N3, N4 )

	IMPLICIT INTEGER ( A - Z )

	INTEGER MSGARA( 16 )

	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA

	CALL CLRSCR
	CALL COLCUR( 1, 12 )
	CALL COLSTR(ICLRED,'FATAL ERROR: ^E')
	CALL STRING( MSGARA )
	CALL STRING(' ( ^E')
	CALL OUTNUM( N1, N2, N3, N4 )
	CALL STRING(' ).^M^J^E')
	CALL CLOSE( 1 )
	CALL USRSET( "2007, 0 )
	CALL USRSET( "2002, 0 )
	CALL USRSET( "2021, 1 )
	CALL EXPROG
	END
	SUBROUTINE CEASE( X, Y, Z, IPLAYR )

	IMPLICIT INTEGER ( A - Z )
	LOGICAL FAILED

	PLAYER = IABS( IPLAYR )
	CALL GETVAL( 5, PLAYER, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 101
	DO 100 I = 1, 10
	    CALL GETVAL( 2, IVAL, I+0, IVAL1 )
	    IF( IVAL1 .EQ. 0 ) GOTO 100
	    CALL TAKOUT( IVAL1, PLAYER, FAILED )
	    CALL DROP( FAILED, .TRUE., X, Y, Z, IVAL1 )
100	CONTINUE
101	CONTINUE
	CALL REMOVE( X, Y, Z, PLAYER, FAILED )
	IF(FAILED)CALL BUGMSG('CEASE: REMOVE#1^E',X,Y,Z,PLAYER)
	CALL PUTVAL( 10, PLAYER, 0 )
	CALL PUTVAL( 7, PLAYER, 1, 0 )
	CALL USRSET( "2007, 0 )
	CALL USRSET( "2002, 0 )
	CALL USRSET( "2021, 1 )
	IF( NUSER(0) .LE. 1 .OR. IPLAYR .GT. 0 )GOTO 200
	CALL CLOSE( 1 )
	CALL ADDUSR( -1 )
	CALL QGONE
200	CALL COLCUR( 1, 1 )
	CALL CLOSE( 1 )
	CALL EXPROG
	END
	SUBROUTINE DROP( FAILED, LOCKIT, X1, Y1, Z, INDEX )

	IMPLICIT INTEGER ( A - Z )

	LOGICAL REPLAC, FAILED, LOCKIT

	FAILED = .TRUE.
	IF( LOCKIT ) CALL LOCK
	X = X1
	Y = Y1
	INDEX1 = INDEX
	CALL GETVAL( 1, X, Y, Z, INDEX2 )

100	IF( INDEX2 .LT. 511 ) GOTO 300
	DO 200 INDEX2 = 1, 510
	    CALL GETVAL( 2, INDEX2+0, 11, INDEX3 )
	    IF( INDEX3 .EQ. 0 ) GOTO 300
200	CONTINUE
	IF( LOCKIT ) CALL UNLOCK
	RETURN

300	CALL GETVAL( 2, INDEX2, 11, IVAL )
	REPLAC = .FALSE.
	IF( IVAL .EQ. 10 )  REPLAC = .TRUE.
	IF( IVAL .LT. 10 )  CALL ADDVAL( -2, 1 )
	CALL PUTVAL( 1, X, Y, Z, INDEX2 )
	DO 400 INDEX3 = 1, 10
	    CALL GETVAL( 2, INDEX2, INDEX3+0, INDEX4 )
	    IF( REPLAC .AND. INDEX4 .GT. 52 ) GOTO 500
	    IF( INDEX4 .EQ. 0 ) GOTO 700
400	CONTINUE
	IF( LOCKIT ) CALL UNLOCK
	RETURN

500	CALL PUTVAL( -2, INDEX1 )
	INDEX1 = INDEX4
600	DIR = IRAN( 6 )
	CALL NEWXY( X, Y, DIR, NX, NY )
	IF( NX .EQ. 0 ) GOTO 600
	CALL GETVAL( 1, NX, NY, Z, INDEX2 )
	IF( INDEX2 .EQ. 0 ) GOTO 600
	X = NX
	Y = NY
	GOTO 100

700	CALL PUTVAL( -2, INDEX1 )
	IF( LOCKIT ) CALL UNLOCK
	FAILED = .FALSE.
	RETURN
	END
	SUBROUTINE REMOVE( X, Y, Z, INDEX1, FAILED )

	IMPLICIT INTEGER ( A - Z )
	LOGICAL FAILED

	CALL LOCK
	FAILED = .TRUE.
	CALL GETVAL( 1, X, Y, Z, INDEX2 )
	IF( INDEX2 .EQ. 0 .OR. INDEX2 .EQ. 511 ) GOTO 300
	DO 100 INDEX3 = 1, 10
	    CALL GETVAL( 2, INDEX2, INDEX3+0, INDEX4 )
	    IF( INDEX4 .EQ. INDEX1 ) GOTO 200
100	CONTINUE
	CALL UNLOCK
	RETURN

200	CALL PUTVAL( 2, INDEX2, INDEX3+0, 0 )
	CALL ADDVAL( 2, INDEX2, 11, -1 )
	CALL GETVAL( -2, INDEX3 )
	IF( INDEX3 .EQ. 0 )  CALL PUTVAL( 1, X, Y, Z, 511 )
	FAILED = .FALSE.
300	CALL UNLOCK
	RETURN
	END

	SUBROUTINE WRDPRB( WORD, MSGARA )
	IMPLICIT INTEGER ( A - Z )

	INTEGER MSGARA( 16 )

	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA
	CALL MESSAG( ICLYEL, '"^E' )
	CALL STRING( WORD, 6, 0 )
	CALL STRING('" ^E')
	CALL STRING( MSGARA )
	RETURN
	END

	SUBROUTINE ADDWRD( ISIX, ITYP, IND )
	INTEGER WRDLST(400), WRDTYP(400), WRDIND(400)
	COMMON /WRDCOM/ WRDLST, WRDTYP, WRDIND, NUMWDS
	WRDLST(NUMWDS) = ISIX
	WRDTYP(NUMWDS) = ITYP
	WRDIND(NUMWDS) = IND
	NUMWDS = NUMWDS + 1
	RETURN
	END

	INTEGER FUNCTION WRDSRC( SRCH4 )
	IMPLICIT INTEGER ( A - Z )
	INTEGER WRDLST(400), WRDTYP(400), WRDIND(400)
	COMMON /WRDCOM/ WRDLST, WRDTYP, WRDIND, NUMWDS

        WRDSRC = ISRSIX( WRDLST, SRCH4, NUMWDS )
	IF( WRDSRC .GT. 0 ) RETURN
	IF( WRDSRC .LT. 0 ) CALL WRDPRB(SRCH4,'is ambiguous.^E')
	IF( WRDSRC .EQ. 0 )
     &	    CALL WRDPRB(SRCH4,'is not in my vocabulary.^E')
	RETURN
	END

	SUBROUTINE WRDNUM( PARARA, WRDPTR, VERB, WORD1, WORD2, LENGTH )

	IMPLICIT INTEGER ( A - Z )
	INTEGER PARARA( 40 ), WRDLST(400), WRDTYP(400), WRDIND(400)
	INTEGER CVT(3)

	COMMON /WRDCOM/ WRDLST, WRDTYP, WRDIND, NUMWDS
	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA

	VERB = 0
	WORD1 = 0
	WORD2 = 0

	IF( SCOMMA .NE. 0 ) GOTO 50
	SCOMMA    = ISXBIT(',')					! "140000000000
	SQUOTE    = ISXBIT('"')					! "020000000000
50	CONTINUE

	NUMWDS = 1
	CALL ADDWRD( ISXBIT('the'              ), 0, 0 )	! "645045000000
	CALL ADDWRD( ISXBIT('in'               ), 0, 0 )	! "515600000000
	CALL ADDWRD( ISXBIT('on'               ), 0, 0 )	! "575600000000
	CALL ADDWRD( ISXBIT('to'               ), 0, 0 )	! "645700000000
	CALL ADDWRD( ISXBIT('from'             ), 0, 0 )	! "466257550000
	CALL ADDWRD( ISXBIT('with'             ), 0, 0 )	! "675164500000
	CALL ADDWRD( ISXBIT('at'               ), 0, 0 )	! "416400000000

	DO 80 I = 1, 6
	    CVT(1) = I + 48
	    CALL CONVRT( CVT, 1, 0, NNAME, 6 )
	    CALL ADDWRD( NNAME, 1, I+0 )
80	CONTINUE
	CALL ADDWRD( ISXBIT('right'            ), 1, 7 )	! DIRECTION
	CALL ADDWRD( ISXBIT('clockwise'        ), 1, 7 )	! DIRECTION
	CALL ADDWRD( ISXBIT('left'             ), 1, 8 )	! DIRECTION
	CALL ADDWRD( ISXBIT('counterclockwise' ), 1, 8 )	! DIRECTION
	I = 0
	J = 0
100	I = I + 1
200	    J = J + 1
	    CALL GETVAL( 9, J, ISXVRB )
	    IF( ISXVRB .EQ. -1 ) GOTO 100
	    IF( ISXVRB .EQ. 0 ) GOTO 250
	    CALL ADDWRD( ISXVRB, 2, I )
	GOTO 200

250	DO 280 I = 1, 100
	    CALL GETVAL( 10, I+0, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 280
	    CALL GETVAL( 3, I+0, NNAME )		! ADD FULL NAME
	    CALL ADDWRD( NNAME, 3, I+0 )
	    IF( I .GT. 26 ) GOTO 260
	    CVT(1) = I + 64
	    CALL CONVRT( CVT, 1, 0, NNAME, 6 )		! ADD SINGLE LETTER
	    CALL ADDWRD( NNAME, 3, I+0 )		! FOR ANOTHER PLAYER
	    GOTO 280
260	    IF( I .GT. 52 ) GOTO 280
	    CVT(1) = ICON('M')				! ADD MX FOR
	    CVT(2) = I + 64 - 26			! A MONSTER
	    CALL CONVRT( CVT, 2, 0, NNAME, 6 )
	    CALL ADDWRD( NNAME, 3, I+0 )
280	CONTINUE

290	WRDPTR = WRDPTR + 1
	IF(PARARA(WRDPTR).EQ.SCOMMA .OR. PARARA(WRDPTR)
     &	    .EQ.SQUOTE .OR.WRDPTR.GT.LENGTH)GOTO 800
        I = WRDSRC( PARARA(WRDPTR) )
	IF( I .LE. 0 ) GOTO 900				! DIE IF UNKNOWN WORD
	IF( WRDTYP(I) .EQ. 0 ) GOTO 290			! SKIP NOISE WORDS
	IF( WRDTYP(I) .NE. 1 ) GOTO 295
	VERB = 17
	WORD1 = -WRDIND(I)
	GOTO 300

295	IF( WRDTYP(I) .NE. 2 ) GOTO 297
	VERB = WRDIND(I)
	GOTO 300

297	CALL WRDPRB( WRDLST(I), 'is not a verb or a direction.^E')
	GOTO 900

300	WRDPTR = WRDPTR + 1
	IF(PARARA(WRDPTR).EQ.SCOMMA .OR. PARARA(WRDPTR)
     &	    .EQ.SQUOTE .OR.WRDPTR.GT.LENGTH)GOTO 800
	I = WRDSRC( PARARA(WRDPTR) )
	IF( I .LE. 0 ) GOTO 900				! DIE IF UNKNOWN WORD
	IF( WRDTYP(I) .EQ. 0 ) GOTO 300			! SKIP NOISE WORDS
	IF( WRDTYP(I) .NE. 1 ) GOTO 400
	WORD1 = -WRDIND(I)
	GOTO 500

400	IF( WRDTYP(I) .NE. 3 ) GOTO 450
	WORD1 = WRDIND(I)
	GOTO 500

450	CALL WRDPRB( WRDLST(I), 'is not a noun or a direction.^E')
	GOTO 900

500	WRDPTR = WRDPTR + 1
	IF(PARARA(WRDPTR).EQ.SCOMMA .OR. PARARA(WRDPTR)
     &	    .EQ.SQUOTE .OR.WRDPTR.GT.LENGTH)GOTO 800
        I = WRDSRC( PARARA(WRDPTR) )
	IF( I .LE. 0 ) GOTO 900				! DIE IF UNKNOWN WORD
	IF( WRDTYP(I) .EQ. 0 ) GOTO 500			! SKIP NOISE WORDS
	IF( WRDTYP(I) .NE. 3 ) GOTO 550
	WORD2 = WRDIND(I)
	GOTO 800

550	CALL WRDPRB( WRDLST(I), 'is not a noun.^E')
	GOTO 900

800	IF( WRDPTR .GT. LENGTH )  WRDPTR = 0
	RETURN

900	VERB = 0
	NOUN1 = 0
	NOUN2 = 0
	RETURN
	END

	SUBROUTINE MESSAG(ICOL, MSGARA )

	INTEGER MSGARA( 16 )

	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA

	CALL COLCUR( 1, 2 )
	DO 100 I = 1, 79
	    CALL CHROUT(' ')
100	CONTINUE
	CALL CHROUT( "15 )
	CALL COLSTR( ICOL, MSGARA )
	RETURN
	END
	SUBROUTINE PUTIN( INDEX1, INDEX2, FAILED )

	IMPLICIT INTEGER ( A - Z )
	LOGICAL FAILED

	CALL LOCK
	FAILED = .TRUE.
	CALL GETVAL( 5, INDEX2, IVAL )
	IF( IVAL .NE. 0 ) GOTO 300
	DO 100 IVAL = 1, 510
	    CALL GETVAL( 2, IVAL+0, 11, IVAL1 )
	    IF( IVAL1 .EQ. 0 ) GOTO 200
100	CONTINUE
200	CALL PUTVAL( 5, INDEX2, IVAL )

300	CALL GETVAL( 2, IVAL, 11, IVAL1 )
	IF( IVAL1 .GE. 10 ) GOTO 600
	CALL ADDVAL( -2, 1 )

	DO 400 IVAL1 = 1, 10
	    CALL GETVAL( 2, IVAL, IVAL1+0, IVAL2 )
	    IF( IVAL2 .EQ. 0 ) GOTO 500
400	CONTINUE
500	CALL PUTVAL( -2, INDEX1 )
	FAILED = .FALSE.
600	CALL UNLOCK
	RETURN
	END
	SUBROUTINE PHOLD( INDEX1, IPLAYR, FAILED )

	IMPLICIT INTEGER ( A - Z )
	LOGICAL FAILED

	CALL LOCK
	PLAYER = IABS( IPLAYR )
	FAILED = .FALSE.
	CALL GETVAL( 5, PLAYER, INDEX2 )
	IF( INDEX2 .NE. 0 ) GOTO 300
	DO 100 INDEX2 = 1, 510
	    CALL GETVAL( 2, INDEX2+0, 11, INDEX3 )
	    IF( INDEX3 .EQ. 0 ) GOTO 200
100	CONTINUE
200	CALL PUTVAL( 5, PLAYER, INDEX2 )

300	CALL GETVAL( 2, INDEX2, 11, NUMUSE )
	IF( NUMUSE .GE. 10 ) GOTO 600
	CALL ADDVAL( -2, 1 )

	CALL GETVAL( 12, INDEX1, INDEX3 )
	CALL GETVAL( 15, INDEX3, TYPE )
	IF( TYPE .EQ. 0 ) GOTO 400
	CALL GETVAL( 2, INDEX2, TYPE, INDEX3 )
	IF( IPLAYR .LT. 0 .AND. INDEX3 .NE. 0 ) GOTO 400
	CALL PUTVAL( -2, INDEX1 )
	IF( INDEX3 .EQ. 0 ) GOTO 700
	INDEX1 = INDEX3

400	INDEX3 = 6
500	    CALL GETVAL( 2, INDEX2, INDEX3, INDEX4 )
	    IF( INDEX4 .NE. 0 .AND. IPLAYR .LT. 0 ) GOTO 550
	    CALL PUTVAL( -2, INDEX1 )
	    IF( INDEX4 .EQ. 0 ) GOTO 700
	    INDEX1 = INDEX4
550	    INDEX3 = INDEX3 + 1
	IF( INDEX3 .LT. 11 ) GOTO 500

600	FAILED = .TRUE.
700	CALL UNLOCK
	RETURN

	END
	SUBROUTINE TAKOUT( INDEX1, INDEX2, FAILED )

	IMPLICIT INTEGER ( A - Z )
	LOGICAL FAILED

	CALL LOCK
	FAILED = .TRUE.
	CALL GETVAL( 5, INDEX2, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 300

	DO 100 IVAL1 = 1, 10
	    CALL GETVAL( 2, IVAL, IVAL1+0, IVAL2 )
	    IF( IVAL2 .NE. INDEX1 ) GOTO 100
	    FAILED = .FALSE.
	    CALL PUTVAL( -2, 0 )
	    GOTO 200

100	CONTINUE
	GOTO 300

200	CALL ADDVAL( 2, IVAL, 11, -1 )
	CALL GETVAL( 2, IVAL, 11, IVAL1 )
	IF( IVAL1 .GT. 0 ) GOTO 300
	CALL PUTVAL( 5, INDEX2, 0 )
300	CALL UNLOCK
	RETURN
	END
	SUBROUTINE PNAME( INDEX, ILEN )

	IMPLICIT INTEGER ( A - Z )

	CALL GETVAL( 12, INDEX, INDEX1 )
	CALL GETVAL( 3, INDEX1, NAME )
	USELEN = ILEN
	IF( JOB(-1) .EQ. 0 ) GOTO 100
	IF( USELEN .LT. -6 ) USELEN = -6
	IF( USELEN .GT. 6 ) USELEN = 6

100	CALL STRING( NAME, 6, USELEN )
	RETURN
	END
	INTEGER FUNCTION WEIGHT( INDEX1 )

	IMPLICIT INTEGER ( A - Z )
	LOGICAL PDLERR

	WEIGHT = 0

100	CALL GETVAL( 4, INDEX1, DUMMY )
	WEIGHT = WEIGHT + DUMMY
	CALL GETVAL( 5, INDEX1, INDEX2 )
	IF( INDEX2 .EQ. 0 .OR. INDEX2 .EQ. 511 ) GOTO 300
	INDEX3 = 0

200	IF( INDEX3 .EQ. 10 ) GOTO 300
	INDEX3 = INDEX3 + 1
	CALL GETVAL( 2, INDEX2, INDEX3, INDEX4 )
	IF( INDEX4 .EQ. 0 .OR. INDEX4 .EQ. 511 ) GOTO 200
	CALL PUSHVL( INDEX1, PDLERR )
	CALL PUSHVL( INDEX2, PDLERR )
	CALL PUSHVL( INDEX3, PDLERR )
	INDEX1 = INDEX4
	GOTO 100

300	CALL POPVAL( INDEX3, PDLERR )
	IF( PDLERR )  RETURN
	CALL POPVAL( INDEX2, PDLERR )
	CALL POPVAL( INDEX1, PDLERR )
	GOTO 200

	END
	INTEGER FUNCTION COST( INDEX1 )

	IMPLICIT INTEGER ( A - Z )
	LOGICAL PDLERR

	COST = 0

100	CALL GETVAL( 12, INDEX1, INDEX5 )
	CALL GETVAL( 13, INDEX5, DUMMY )
	COST = COST + DUMMY
	CALL GETVAL( 5, INDEX1, INDEX2 )
	IF( INDEX2 .EQ. 0 .OR. INDEX2 .EQ. 511 ) GOTO 300
	INDEX3 = 0

200	IF( INDEX3 .EQ. 10 ) GOTO 300
	INDEX3 = INDEX3 + 1
	CALL GETVAL( 2, INDEX2, INDEX3, INDEX4 )
	IF( INDEX4 .EQ. 0 ) GOTO 200
	CALL PUSHVL( INDEX1, PDLERR )
	CALL PUSHVL( INDEX2, PDLERR )
	CALL PUSHVL( INDEX3, PDLERR )
	INDEX1 = INDEX4
	GOTO 100

300	CALL POPVAL( INDEX3, PDLERR )
	IF( PDLERR )  RETURN
	CALL POPVAL( INDEX2, PDLERR )
	CALL POPVAL( INDEX1, PDLERR )
	GOTO 200

	END
	INTEGER FUNCTION HOLDS( INDEX, NAME )

	IMPLICIT INTEGER ( A - Z )

	HOLDS = 0
	CALL GETVAL( 5, INDEX, INDEX1 )
	IF( INDEX1 .EQ. 0 .OR. INDEX1 .EQ. 511 )  RETURN
	DO 100 ITEMP = 1, 10
	    INDEX2 = ITEMP
	    CALL GETVAL( 2, INDEX1, INDEX2, INDEX3 )
	    IF( INDEX3 .EQ. 0 ) GOTO 100
	    CALL GETVAL( 12, INDEX3, INDEX4 )
	    IF( NAME .EQ. INDEX4 ) GOTO 200
100	CONTINUE
	RETURN

200	HOLDS = INDEX3
	RETURN
	END
	INTEGER FUNCTION AT( X, Y, Z, NAME )

	IMPLICIT INTEGER ( A - Z )

	AT = 0
	CALL GETVAL( 1, X, Y, Z, INDEX1 )
	IF( INDEX1 .EQ. 0 .OR. INDEX1 .EQ. 511 )  RETURN
	DO 100 ITEMP = 1, 10
	    INDEX2 = ITEMP
	    CALL GETVAL( 2, INDEX1, INDEX2, INDEX3 )
	    IF( INDEX3 .EQ. 0 .OR. INDEX3 .EQ. 511 ) GOTO 100
	    CALL GETVAL( 12, INDEX3, INDEX4 )
	    IF( NAME .EQ. INDEX4 ) GOTO 200
100	CONTINUE
	RETURN

200	AT = INDEX3
	RETURN
	END
	INTEGER FUNCTION CANHLD( INDEX1 )

	IMPLICIT INTEGER ( A - Z )

	CALL GETVAL( 12, INDEX1, INDEX2 )
	CALL GETVAL( 14, INDEX2, CANHLD )
	CANHLD = CANHLD - WEIGHT( INDEX1 )
	IF( CANHLD .LT. 0 )  CANHLD = 0
	RETURN
	END
	LOGICAL FUNCTION ENEMY( X, Y, Z, PLAYER, DEXTER )

	IMPLICIT INTEGER ( A - Z )

	DICE1 = 0
	DO 100 ITEMP = 1, 52
	    IF( ITEMP .EQ. PLAYER ) GOTO 100
	    IPLAYR = ITEMP
	    CALL GETVAL( 10, IPLAYR, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 100
	    IVAL = 0
	    IF(IPLAYR.LE.26)CALL GETVAL( 23, IPLAYR, PLAYER, IVAL )
	    IF( IVAL .EQ. 1 ) GOTO 100
	    CALL GETVAL( 19, IPLAYR, 1, AX )
	    IF( AX .NE. X ) GOTO 100
	    CALL GETVAL( 19, IPLAYR, 2, AY )
	    IF( AY .NE. Y ) GOTO 100
	    CALL GETVAL( 19, IPLAYR, 3, AZ )
	    IF( AZ .NE. Z ) GOTO 100
	    DICE1 = DICE1 + IRAN( 18 )
100	CONTINUE

	ENEMY = .FALSE.
	IF( DICE1 .GT. DEXTER )  ENEMY = .TRUE.
	RETURN
	END
	SUBROUTINE MAP( FAILED )

	IMPLICIT INTEGER ( A - Z )

	INTEGER FILESP( 13 )
	LOGICAL FAILED, ERROR

	I = ITTY( JOB(0) )
	CALL NODLIN( I, IN, IL )
	FILESP( 3 ) = ISXBIT('LPT00') + (IN/8)*4096 + MOD(IN,8)*64
	FILESP( 4 ) = IGTAB(JOB(0),"137)
	FILESP( 5 ) = ISXBIT('MAP')
	CALL OFILE( 10, FILESP, 0 )
	IF( ERROR(0) )  RETURN
	CALL WFILE( 10, FILESP )
	IF( ERROR(0) )  RETURN
	CALL SELECT( 10 )

	DO 400 ZTEMP = 4, 1, -1
	    Z = ZTEMP
	    CALL CHROUT( 12 )
	    CALL STRING
     &('^M^S^S^S^I^I^I^I^I^I    * * * C a v e  m a p * * *
     &^M^S^I^I^I^I^I^I^I      Floor ^E')
	    CALL NUMBER( Z )
	    CALL STRING('^M^S^S^S^I^I    ^E')
	    DO 50 I = 1, 25
		CALL NUMBER( I*2, 4 )
50	    CONTINUE
	    CALL STRING('^M^S^E')
	    DO 300 YTEMP = 50, 1, -1
		Y = YTEMP
		CALL STRING('^I^I    >^E')
		DO 100 XTEMP = 2, 50, 2
		    IVAL1 = 0
		    CALL GETVAL( 16, XTEMP+0, Y, Z, IVAL1 )
		    CALL GETVAL( 1, XTEMP+0, Y, Z, IVAL )
		    CALL PHEX( IVAL, IVAL1 )
100		CONTINUE
		CALL NUMBER( Y, 3 )
		CALL STRING('^M^S^I^I^E')
		CALL NUMBER( Y, 2 )
		CALL CHROUT(' ')
		DO 200 XTEMP = 1, 49, 2
		    IVAL1 = 0
		    CALL GETVAL( 16, XTEMP+0, Y, Z, IVAL1 )
		    CALL GETVAL( 1, XTEMP+0, Y, Z, IVAL )
		    CALL PHEX( IVAL, IVAL1 )
200		CONTINUE
		CALL STRING('<^M^S^E')
300	    CONTINUE
	    CALL STRING('^I^I  ^E')
	    DO 350 I = 1, 25
		CALL NUMBER( I*2-1, 4 )
350	    CONTINUE
400	CONTINUE

	CALL STRING('^LMap indices:^M^S^S^S^E')
	IPOS = 0
	DO 500 Z = 4, 1, -1
	    DO 500 Y = 50, 1, -1
		DO 500 X = 1, 50
		    CALL GETVAL( 1, X+0, Y+0, Z+0, IVAL )
		    IF( IVAL .EQ. 0 .OR. IVAL .EQ. 511 ) GOTO 500
		    IPOS = IPOS + 1
		    CALL STRING('       ^E')
		    CALL CHROUT('(')
		    CALL NUMBER( X+0, -2 )
		    CALL CHROUT(',')
		    CALL NUMBER( Y+0, -2 )
		    CALL CHROUT(',')
		    CALL NUMBER( Z+0 )
		    CALL STRING('):  ^E')
		    CALL NUMBER( IVAL, 3 )
		    CALL NUMBER( IVAL, 4, 36 )
		    IF( MOD( IPOS, 4 ) .EQ. 0 )  CALL STRING('^M^S^E')
500	CONTINUE

	CALL STRING('^LGroup indices:^M^S^S^S^E')
	DO 700 ITEMP = 1, 510
	    IND = ITEMP
	    CALL GETVAL( 2, IND, 11, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 700
	    CALL STRING('       ^E')
	    CALL NUMBER( IND, 3 )
	    CALL NUMBER( -IND, 3, 36 )
	    CALL STRING('  Length:^E')
	    CALL NUMBER( IVAL, 2 )
	    DO 600 J = 1, 10
		CALL GETVAL( 2, IND, J+0, IVAL )
		IF( IVAL .EQ. 0 ) GOTO 600
		CALL STRING('   ^E')
		CALL NUMBER( J+0, 2 )
		CALL CHROUT(':')
		CALL NUMBER( IVAL, 3 )
600	    CONTINUE
	    CALL STRING('^M^S^E')
700	CONTINUE

	CALL STRING
     &('^LObject indices:^M^S^S^SIndex^IName^IWeight^IHolds^I
     &IS^IDamage^ISuccess^IJob^IDir^ICoordinate^I^IAllies^M^S^E')
	DO 1100 ITEMP = 1, 510
	    IND = ITEMP
	    CALL GETVAL( 10, IND, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 1100
	    CALL NUMBER( IND, 3 )
	    CALL CHROUT( 9 )
	    CALL PNAME( IND, 4 )
	    CALL CHROUT( 9 )
	    CALL GETVAL( 4, IND, IVAL )
	    CALL NUMBER( IVAL )
	    CALL CHROUT(':')
	    CALL NUMBER( WEIGHT(IND) )
	    CALL CHROUT(9)
	    CALL GETVAL( 5, IND, IVAL )
	    IF( IVAL .EQ. 511 ) GOTO 800
	    CALL NUMBER( IVAL )
	    CALL NUMBER( -IVAL, 0, 36 )
800	    CALL CHROUT( 9 )
	    CALL GETVAL( 12, IND, IVAL )
	    CALL NUMBER( IVAL )
	    IF( IND .GT. 52 ) GOTO 1000
	    CALL CHROUT( 9 )
	    CALL GETVAL( 6, IND, 1, IVAL )
	    CALL NUMBER( IVAL )
	    CALL CHROUT(',')
	    CALL GETVAL( 6, IND, 2, IVAL )
	    CALL NUMBER( IVAL )
	    CALL CHROUT(',')
	    CALL GETVAL( 6, IND, 3, IVAL )
	    CALL NUMBER( IVAL )
	    CALL CHROUT( 9 )
	    CALL GETVAL( 21, IND, IVAL )
	    CALL NUMBER( IVAL )
	    CALL CHROUT( 9 )
	    IF( IND .LE. 26 )CALL GETVAL( 7, IND, 1, IVAL )
	    IF( IND .LE. 26 )CALL NUMBER( IVAL )
	    CALL CHROUT( 9 )
	    CALL GETVAL( 8, IND, IVAL )
	    CALL NUMBER( IVAL )
	    CALL CHROUT( 9 )
	    CALL GETVAL( 19, IND, 1, X )
	    CALL GETVAL( 19, IND, 2, Y )
	    CALL GETVAL( 19, IND, 3, Z )
	    CALL OUTNUM( X, Y, Z )
	    IF( IND .GT. 26 ) GOTO 901
	    CALL CHROUT( 9 )
	    CALL CHROUT( 9 )
	    DO 900 PTEMP = 1, 26
		P = PTEMP
		CALL GETVAL( 23, IND, P, IVAL )
		IF( IVAL .NE. 0 )  CALL CHROUT( P+64 )
900	    CONTINUE
901	    CONTINUE
1000	    CALL STRING('^M^S^E')
1100	CONTINUE

	CALL STRING('^LInformation for item types:^M^S^S^SIndex^IName
     &^ICost^ICarries^IWhere^IDamage^IStren^IType^M^S^E')
	DO 1300 ITEMP = 1, 100
	    IND = ITEMP
	    CALL GETVAL( 3, IND, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 1300
	    CALL NUMBER( IND, 3 )
	    CALL CHROUT( 9 )
	    CALL STRING( IVAL, 6, 4 )
	    CALL CHROUT( 9 )
	    CALL GETVAL( 13, IND, IVAL )
	    CALL CHROUT('$')
	    CALL NUMBER( IVAL )
	    CALL CHROUT( 9 )
	    CALL GETVAL( 14, IND, IVAL )
	    CALL NUMBER( IVAL )
	    CALL CHROUT( 9 )
	    CALL GETVAL( 15, IND, IVAL )
	    CALL NUMBER( IVAL )
	    CALL CHROUT( 9 )
	    CALL GETVAL( 17, IND, IVAL )
	    CALL NUMBER( IVAL/10 )
	    CALL CHROUT(' ')
	    CALL NUMBER( MOD(IVAL,10)-5 )
	    CALL CHROUT( 9 )
	    CALL GETVAL( 18, IND, IVAL )
	    CALL NUMBER( IVAL )
	    CALL CHROUT( 9 )
	    CALL GETVAL( 24, IND, IVAL )
	    CALL NUMBER( IVAL )
	    CALL STRING('^M^S^E')
1300	CONTINUE

	CALL STRING('^LStore indices:^M^S^S^S^E')
	IPOS = 0
	DO 1400 ITEMP = 1, 80
	    IND = ITEMP
	    CALL GETVAL( 11, IND, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 1400
	    CALL STRING('                  ^E')
	    CALL NUMBER( IND, 2 )
	    CALL STRING('  -  ^E')
	    CALL NUMBER( IVAL, 3 )
	    IPOS = IPOS + 1
	    IF( MOD( IPOS, 4 ) .EQ. 0 ) CALL STRING('^M^S^E')
1400	CONTINUE
	FAILED = .FALSE.
	CALL CLOSE( 10 )
	CALL SELECT( 0 )
	RETURN
	END
	SUBROUTINE PHEX( IVAL, IVAL1 )

	IF( IVAL1 .EQ. 0 )CALL CHROUT('<')
	IF( IVAL1 .NE. 0 )CALL CHROUT('[')
	IF( IVAL .EQ. 0 )  CALL STRING('##^E')
	IF( IVAL .EQ. 511 )  CALL STRING('  ^E')
	IF( IVAL .GT. 0 .AND. IVAL .LT. 511 )CALL NUMBER( IVAL, 2, 36 )
	IF( IVAL1 .EQ. 0 )CALL CHROUT('>')
	IF( IVAL1 .NE. 0 )CALL CHROUT(']')

	RETURN
	END
	SUBROUTINE MONSTR

C****** SUBROUTINE CONTROLS ALL MONSTERS ************************

	IMPLICIT INTEGER ( A - Z )
	LOGICAL FAILED

	DO 1000 I = 1, 26
	    MINDEX = I
	    TINDEX = MINDEX + 26
	    CALL GETVAL( 10, TINDEX, IVAL )
	    IF( IVAL .NE. 0 ) GOTO 100

C****** MONSTER MUST BE (RE) CREATED ****************************

	    CALL PUTVAL( -10, 1 )
	    CALL GETVAL( 25, MINDEX, IVAL )
	    CALL PUTVAL( 4, TINDEX, IVAL )
	    CALL GETVAL( 27, MINDEX, 1, IVAL )
	    CALL PUTVAL( 27, MINDEX, 2, IVAL )
	    CALL PUTVAL( 12, TINDEX, TINDEX )
	    CALL PUTVAL( 8, TINDEX, IRAN(6) )
	    CALL GETVAL( 30, MINDEX, Z )
	    Z = IRAN( Z+1 )
50	    X = IRAN( 49 ) + 1
	    Y = IRAN( 49 ) + 1
	    CALL GETVAL( 1, X, Y, Z, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 50
	    CALL DROP( FAILED, .TRUE., X, Y, Z, TINDEX )
	    CALL PUTVAL( 19, TINDEX, 1, X )
	    CALL PUTVAL( 19, TINDEX, 2, Y )
	    CALL PUTVAL( 19, TINDEX, 3, Z )
	    CALL GETVAL( 29, MINDEX, NHEX )
	    IF( NHEX .LE. 1 ) GOTO 71
	    DO 70 IHEX= 1, NHEX-1
60		IDIR = IRAN(6)
		CALL NEWXY( X, Y, IDIR, NX, NY )
		IF( NX .EQ. 0 ) GOTO 60
		CALL GETVAL( 1, NX, NY, Z, IVAL )
		IF( IVAL .EQ. 0 ) GOTO 60
		CALL PUTVAL( 31, MINDEX, IHEX+0, IDIR )
		CALL DROP( FAILED, .TRUE., NX, NY, Z, TINDEX )
		X = NX
		Y = NY
70	    CONTINUE
71	    CONTINUE

C****** MOVE MONSTER ********************************************

100	    CALL GETVAL( 27, MINDEX, 2, STRENG )
	    CALL GETVAL( 26, MINDEX, DEXTER )
	    CALL GETVAL( 19, TINDEX, 1, X )
	    CALL GETVAL( 19, TINDEX, 2, Y )
	    CALL GETVAL( 19, TINDEX, 3, Z )
	    CALL GETVAL( 32, TINDEX, RECOVR )
	    IF( RECOVR .GT. 0 ) CALL ADDVAL( -32, -1 )
	    CALL GETVAL( 6, TINDEX, 1, HOATME )
	    IF( HOATME .EQ. 0 ) GOTO 105
	    CALL PUTVAL( -6, 0 )
	    CALL GETVAL( 6, TINDEX, 3, FORCE )
C	    IF( IRAN(6)+IRAN(6)+IRAN(6).LT.DEXTER.AND.RECOVR.LE.0 )
C     & GOTO 104
	    STRENG = STRENG - FORCE
	    CALL PUTVAL( 21, HOATME, 2 )
	    CALL PUTVAL( 27, MINDEX, 2, STRENG )
	    IF( STRENG .GT. 0 ) GOTO 105
	    CALL PUTVAL( 6, HOATME, 4, TINDEX )
	    CALL REMOVE( X, Y, Z, TINDEX, FAILED )
	    IF(FAILED)CALL BUGMSG('MONSTR: REMOVE#1^E',X,Y,Z,TINDEX)
	    CALL GETVAL( 29, MINDEX, NHEX )
	    IF( NHEX .LE. 1 ) GOTO 103
	    DO 102 IHEX = 1, NHEX-1
		CALL GETVAL( 31, MINDEX, IHEX+0, IDIR )
		CALL NEWXY( X, Y, IDIR, NX, NY )
		CALL REMOVE( NX, NY, Z, TINDEX, FAILED )
		IF(FAILED)CALL BUGMSG('MONSTR: REMOVE#2^E',NX,NY,Z,TINDEX)
		X = NX
		Y = NY
102	    CONTINUE
103	    CONTINUE
	    CALL PUTVAL( 10, TINDEX, 0 )
	    GOTO 1000
104	    CALL PUTVAL( 21, HOATME, 3 )

C****** FIND OUT IF ANY ENEMY IS PRESENT, IF SO, ATTACK *********

105	    IF( RECOVR .GT. 0 ) GOTO 1000
	    BSTDST = 100.
	    DO 150 A = 1, 26
		AINDEX = A
		CALL GETVAL( 10, AINDEX, IVAL )
		IF( IVAL .EQ. 0 ) GOTO 150
		CALL GETVAL( 19, AINDEX, 3, AZ )
		IF( AZ .NE. Z ) GOTO 150
		CALL GETVAL( 19, AINDEX, 1, AX )
		CALL GETVAL( 19, AINDEX, 2, AY )
		DIST = SQRT((X-AX+0.0)^2 + (Y-AY+0.0)^2)
		IF( DIST .GT. BSTDST ) GOTO 150
		BSTDST = DIST
		BINDEX = AINDEX
		DIR = FINDIR( X, Y, AX, AY )
150	    CONTINUE
	    IF( BSTDST .GT. 10 ) DIR = IRAN( 6 )
	    MONCTR = 0
	    GOTO 170

160	    MONCTR = MONCTR + 1
	    IF( MONCTR .EQ. 10 ) GOTO 1000
	    DIR = NEWDIR( DIR, IRAN(3)-2 )

170	    CALL PUTVAL( 8, TINDEX, DIR )
	    CALL NEWXY( X, Y, DIR, NX, NY )
	    IF( NX .EQ. 0 ) GOTO 160
	    CALL GETVAL( 1, NX, NY, Z, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 160
	    IF( BSTDST.LE.2.0 .AND. AT(NX,NY,Z,BINDEX).NE.0 ) GOTO 600
	    CALL DROP( FAILED, .TRUE., NX, NY, Z, TINDEX )
	    IF( FAILED ) GOTO 160
	    CALL REMOVE( X, Y, Z, TINDEX, FAILED )
	    IF(FAILED)CALL BUGMSG('MONSTR: REMOVE#3^E',X,Y,Z,TINDEX)
	    CALL PUTVAL( 19, TINDEX, 1, NX )
	    CALL PUTVAL( 19, TINDEX, 2, NY )
	    CALL GETVAL( 29, MINDEX, NHEX )
	    IF( NHEX .LE. 1 ) GOTO 301
	    DIR = NEWDIR( DIR, 3 )
	    DO 300 IHEX = 1, NHEX-1
		CALL GETVAL( 31, MINDEX, IHEX+0, IDIR )
		CALL NEWXY( X, Y, IDIR, NX, NY )
		CALL PUTVAL( 31, MINDEX, IHEX+0, DIR )
		DIR = IDIR
		CALL REMOVE( NX, NY, Z, TINDEX, FAILED )
		CALL DROP( FAILED, .TRUE., X, Y, Z, TINDEX )
		X = NX
		Y = NY
300	    CONTINUE
301	    CONTINUE
	    IF( 20-DEXTER .GT. 0 ) CALL PUTVAL( 32, TINDEX, 20-DEXTER )
	    GOTO 1000

C****** MONSTER IS ATTACKING ************************************

600	    METHOD = IRAN( 20 )
	    DO 700 J = 1, 5
		CALL GETVAL( 28, MINDEX, J+0, IVAL )
		IF( IVAL .GE. METHOD ) GOTO 800
		METHOD = METHOD - IVAL
700	    CONTINUE
800	    CALL PUTVAL( 6, BINDEX, 1, TINDEX )
	    CALL PUTVAL( 6, BINDEX, 2, 511+J )
	    CALL PUTVAL( 6, BINDEX, 3, IRAN( STRENG*J/5 ) )
	    IF( 33-DEXTER.GT.0 )CALL PUTVAL( 32, TINDEX, 33-DEXTER )
1000	CONTINUE
	RETURN
	END

	SUBROUTINE SYSWHO( IJOB )
	INTEGER UNAME(2)
	IF( JOB(IJOB) .EQ. 0 ) RETURN
	CALL STRING('Job ^E')
	CALL NUMBER( IJOB )
	CALL CHROUT(' ')
	UNAME(1) = IGTAB( IJOB, "31 )
	UNAME(2) = IGTAB( IJOB, "32 )
	CALL STRING( UNAME, 6, 12 )
	CALL STRING(' [^E')
	CALL NUMBER( ILEFT( IGTAB( IJOB, 2 ) ), 0, 8 )
	CALL CHROUT(',')
	CALL NUMBER( IRIGHT( IGTAB( IJOB, 2 ) ), 0, 8 )
	CALL STRING('] ^E')
	CALL STRING(' TTY^E')
	CALL NUMBER( ITTY( IJOB ), 0, 8 )
	CALL STRING(' at ^E')
	CALL NODLIN( ITTY(IJOB), IN, IL )
	CALL STRING( NODE( IN ), 6, 6 )
	CALL CHROUT('(')
	CALL NUMBER( IN, 0, 8 )
	CALL STRING(')^E')
	CALL STRING(' line ^E')
	CALL NUMBER( IL, 0, 8 )
C	CALL CHROUT(' ')
C	CALL STRING( JSTAT( IJOB ), 6, 2 )
	RETURN
	END

	SUBROUTINE FINWRD( WORD, IND )
	IMPLICIT INTEGER ( A - Z )
	LOGICAL STREQ

	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA
	DO 100 IND = 1, 100
	    CALL GETVAL( 10, IND+0, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 100
	    CALL GETVAL( 3, IND+0, NNAME )
	    IF( STREQ( NNAME, WORD ) ) RETURN
100	CONTINUE
	RETURN
	END

	SUBROUTINE FMAIN

	IMPLICIT INTEGER ( A - Z )

	LOGICAL ENEMY, INIFLG, LPRIVD, FAILED, PARRY, ERROR
	INTEGER COMARA( 80 ), PARARA( 40 ), BODY( 10 ), MONTH(12)
	INTEGER FILESP( 13 )
	LOGICAL CANSEE( 52 ), NEWSCR, STREQ

	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA

	DATA NEWSCR/.TRUE./, IMONEY/500/, NITEM/10/, ELEVEL/25/
	DATA MONTH/'JAN','FEB','MAR','APR','MAY','JUN','JUL',
     &'AUG','SEP','OCT','NOV','DEC'/

	ICLWHI = 1
	ICLDBL = 2
	ICLRED = 3
	ICLLBL = 4
	ICLPUR = 5
	ICLGRE = 6
	ICLYEL = 7
	ICLBLA = 8
	CALL PBACK( ICLBLA )
	CALL PCOLOR( ICLWHI )

	CALL SETTTY( COMARA, PARARA, ILEN, LPRIVD, FILESP )
	CALL ENABLE
	CALL CHECK( INIFLG )
	IF( INIFLG )  CALL INITDB( COMARA, PARARA, FILESP )
	CALL CLRSCR
	CALL FINWRD( ISXBIT('disintegrator'), DISIND )

	CALL COLCUR( 1, 24 )
	CALL STRING('Your name?^E')
100	CALL COLCUR( 12, 24 )
	CALL STRING('               ^E')
	CALL COLCUR( 12, 24 )
	CALL CURBUF
	CALL GETSTR( COMARA, 15, ILEN )
	IF( JOB(-1) .NE. 0 .AND. ILEN .GT. 6 ) ILEN = 6
	CALL COLCUR( 1, 10 )
	IF( ILEN .EQ. 0 ) GOTO 100
	CALL ALLCAP( COMARA, 1 )
	PLAYER = ICON(COMARA(1))-64
	IF( PLAYER.LT.1 .OR. PLAYER.GT.52 ) GOTO 100
	CALL CONVRT( COMARA, ILEN, 1, NAME, 6 )
	DO 300 I = 1, 100
	    CALL GETVAL( 3, I+0, IVAL )
	    IF( STREQ(IVAL,NAME) ) GOTO 100
300	CONTINUE
	CALL GETVAL( 10, PLAYER, IVAL )
	IF( IVAL .NE. 0 ) GOTO 100
	CALL PUTVAL( -10, 1 )
	CALL PUTVAL( 8, PLAYER, 7 )
	CALL LOCK
	DO 350 I = 1, 26
	    CALL PUTVAL( 23, PLAYER, I+0, 0 )
350	CONTINUE
	CALL PUTVAL( 7, PLAYER, 1, JOB(0) )
	CALL PUTVAL( 7, PLAYER, 2, 0 )
	CALL PUTVAL( 3, PLAYER, NAME )
	CALL PUTVAL( 12, PLAYER, PLAYER )
	INPLAY = PLAYER
	CALL PUTVAL( 4, PLAYER, 70 )
	CALL UNLOCK
	CALL COLCUR( 1, 23 )
	CALL STRING
     &('How many extra points do you wish to allocate to strength?^E')
500	CALL COLCUR( 60, 23 )
	CALL STRING('          ^E')
	CALL COLCUR( 60, 23 )
	CALL CURBUF
	CALL GETNUM( 10, DIFF, 10 )
	IF( DIFF .LT. 0 .OR. DIFF .GT. 8 ) GOTO 500
	USTREN = DIFF + 8
	STRENG = USTREN
	UDEX = 24 - USTREN
	DEXTER = UDEX
	CALL PUTVAL( 14, PLAYER, 6*STRENG + 70 )
600	DO 700 I = 1, 80
	    COMARA( I ) = 0
700	CONTINUE
	CALL PPN( I, IPN1 )
	DO 800 PPNIND = 1, 100
	    CALL GETVAL( 22, PPNIND+0, 1, IPN2 )
	    IF( IPN2 .EQ. IPN1 .OR. IPN2 .EQ. 0 ) GOTO 900
800	CONTINUE
900	CALL PUTVAL( -21, IPN1 )
	IF( IPN2 .EQ. 0 )  CALL PUTVAL( 22, PPNIND+0, 2, IMONEY )
1000	DO 1200 ITEMP = 1, 80
	    I = ITEMP
	    CALL GETVAL( 11, I, INDEX1 )
C	    IF( (INDEX1 .EQ. 0) .XOR. (COMARA( I ) .NE. 0) ) GOTO 1200
	    CALL COLCUR( ((I-1)/20)*20+1, 22-MOD((I-1),20) )
	    IF( INDEX1 .EQ. 0 ) GOTO 1100
C	    CALL GETVAL( 12, INDEX1, INDEX2 )
	    CALL NUMBER( I, 2 )
C	    CALL NUMBER( WEIGHT( INDEX1 ), 3 )
	    CALL STRING(' $^E')
	    CALL NUMBER( COST( INDEX1 ), 3 )
	    CALL CHROUT(' ')
	    CALL PNAME( INDEX1, -17 )
	    COMARA( I ) = 1
	    GOTO 1200

1100	    COMARA( I ) = 0
	    CALL STRING('                 ^E')

1200	CONTINUE
	CALL GETVAL( 22, PPNIND, 2, MONEY )
	IF( MONEY .EQ. 0 .OR. NITEM .EQ. 0 ) GOTO 1400
	CALL COLCUR( 1, 2 )
	CALL STRING('Enter number of item you want (-1 to stop):
     &            ^M^J$^E')
	CALL GETVAL( 22, PPNIND, 2, MONEY )
	CALL NUMBER( MONEY )
	CALL STRING(' left.  Can carry ^E')
	CALL NUMBER( CANHLD( PLAYER ) )
	CALL STRING(' Kilogram(s) in ^E')
	CALL NUMBER( NITEM )
	CALL STRING(' item(s).       ^E')
	CALL COLCUR( 45, 2 )
	CALL CURBUF
	CALL GETNUM( 10, ITEM, 10 )
	CALL COLCUR( 1, 10 )
	IF( ITEM .EQ. -1 ) GOTO 1400
	IF( ITEM .EQ. 0 ) GOTO 1000
	IF( ITEM .LT. 1 .OR. ITEM .GT. 80 ) GOTO 1300
	CALL GETVAL( 11, ITEM, INDEX1 )
	IF( INDEX1 .EQ. 0 ) GOTO 1300
	I = COST( INDEX1 )
	CALL GETVAL( 22, PPNIND, 2, MONEY )
	IF( MONEY .LT. I ) GOTO 1300
	CALL PHOLD( INDEX1, -PLAYER, FAILED )
	IF( FAILED ) GOTO 1300
	CALL UPDATE(0)
	MONEY = MONEY - I
	CALL UPDATE(0)
	CALL PUTVAL( 22, PPNIND, 2, MONEY )
	CALL UPDATE(0)
	CALL PUTVAL( 11, ITEM, 0 )
	CALL UPDATE(0)
	NITEM = NITEM - 1
	CALL UPDATE(0)
	GOTO 1000

1300	CALL CLRSCR
	CALL COLCUR( 45, 2 )
	CALL STRING('* Invalid *^E')
	GOTO 600

1400	CALL PUTVAL( 22, PPNIND, 2, MONEY )
	X = IRAN( 50 )
	Y = IRAN( 50 )
	Z = 4
	CALL GETVAL( 1, X, Y, Z, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 1400
	CALL PUTVAL( 13, PLAYER, MONEY )
	DIR = IRAN( 6 )
	CALL PUTVAL( 8, PLAYER, DIR )
	CALL DROP( FAILED, .TRUE., X, Y, Z, PLAYER )
	CALL USRSET( "2006, 1 )
	CALL USRSET( "2025, 0 )
	CALL USRSET( "2007, 1 )
	CALL USRSET( "2010, 1 )
	CALL USRSET( "2021, 0 )
	CALL USRSET( "1030, TTYSPD )
	GOTO 1600

C****************************************************************
C****** GAME LOOP ***********************************************
C****************************************************************

1500	CALL MESSAG(ICLLBL,'Ok.^E')

1600	IF(100*IGTAB("54,"11)/IGTAB("50,"11).LE.85.OR.LPRIVD) GOTO 1625
	CALL MESSAG(ICLPUR,
     &	    'It is over styxline.  The game must cease.^M^J^E')
	CALL CEASE( X, Y, Z, PLAYER )

1625	CALL GETVAL( 20, 75, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 1650
	CALL CLRSCR
	CALL COLCUR( 5, 10 )
	CALL COLSTR(ICLRED,'^G^GYou have failed. ^E')
	CALL PNAME( IVAL, -17 )
	CALL STRING(' Has left the cave with the disintegrator.^M^J^E')
	CALL CEASE( X, Y, Z, PLAYER )

1650	CALL USRSET( "2030, TTYSPD )
	CALL USRSET( "2031, TTYSPD )
	CALL USRSET( "2002, 1 )
	RUNING = 0
	CALL PUTVAL( 19, PLAYER, 1, X )
	CALL PUTVAL( 19, PLAYER, 2, Y )
	CALL PUTVAL( 19, PLAYER, 3, Z )
	CALL PUTVAL( 14, PLAYER, 6*STRENG + 70 )
	CALL GETVAL( 7, PLAYER, 2, IVAL )
	IF( IVAL .LT. ELEVEL ) GOTO 1675
	ELEVEL = 2*ELEVEL
	IVAL = IRAN(2) - 1
	STRENG = STRENG + IVAL
	USTREN = USTREN + IVAL
	UDEX = UDEX + 1 - IVAL
1675	IF( DIR .NE. 0 ) GOTO 1700
	RESTR = RESTR + 1
	IF( MOD( RESTR, 25 ) .EQ. 0 )  STRENG = STRENG + 1
	IF( STRENG .GT. USTREN )  STRENG = USTREN

C****** CHECK FOR ANY MESSAGES **********************************

1700	CALL GETVAL( 20, 1, ISOURC )
	IF( ISOURC .EQ. 0 ) GOTO 2101
	CALL GETVAL( 20, 4, IUSER )
	IF( IUSER .LT. NUSER(0) ) GOTO 1800
	CALL PUTVAL( 20, 1, 0 )
	GOTO 2101
1800	CALL ADDVAL( -20, 1 )
	IF( ISOURC .EQ. PLAYER ) GOTO 2101
	CALL GETVAL( 19, ISOURC, 3, NZ )
	IF( NZ .NE. Z ) GOTO 2101
	CALL GETVAL( 19, ISOURC, 1, NX )
	CALL GETVAL( 19, ISOURC, 2, NY )
	DFAC = SQRT( (X-NX+0.0)^2 + (Y-NY+0.0)^2 )
	CALL GETVAL( 20, 2, VOL )
	VOL = 20*(6^VOL) / (DFAC+1)
	IF( VOL .LT. 2 ) GOTO 2101
	VDIR = 0
	IF( DFAC .NE. 0 )  VDIR = FINDIR( X, Y, NX, NY )
	IF( VOL .GT. 10 ) GOTO 1900
	CALL MESSAG(ICLWHI,'You hear a voice^E')
	IF( VOL .LT. 5 )  CALL CHROUT('.')
	IF( VOL .LT. 5 ) GOTO 2101
	CALL STRING(' from direction ^E')
	CALL NUMBER( VDIR )
	CALL CHROUT('.')
	GOTO 2101
1900	IF( VOL .GE. 15 ) GOTO 2000
	CALL MESSAG(ICLWHI,'You hear ^E')
	CALL PNAME( ISOURC, -17 )
	CALL STRING(' from direction ^E')
	CALL NUMBER( VDIR )
	CALL CHROUT('.')
	GOTO 2101
2000	CALL MESSAG(ICLWHI,'^G^E')
	CALL PNAME( ISOURC, -17 )
	CALL CHROUT('(')
	CALL NUMBER( VDIR )
	CALL STRING('): ^E')
	CALL GETVAL( 20, 3, LENGTH )
	DO 2100 I = 1, LENGTH
	    CALL GETVAL( 20, I+4, IVAL )
	    CALL CHROUT( IVAL )
2100	CONTINUE
2101	CONTINUE

C******	HAS ANYONE TOUCHED THE DISI SINCE LAST CLICK *************

	CALL GETVAL( 33, 1, IVAL )
	IF( IVAL .EQ. OLNDST ) GOTO 2110
	CALL MESSAG(ICLRED,'^GThe disintegrator has been picked up.^E')
	OLNDST = IVAL

C****** WHAT DID THE OTHER GUY DO TO OUR ATTACK *****************

2110	CALL GETVAL( 21, PLAYER, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 2150
	CALL PUTVAL( -21, 0 )
	IF( IVAL .EQ. 1 ) CALL MESSAG(ICLRED,'You hit him on the head.^E')
	IF( IVAL .EQ. 2 ) CALL MESSAG(ICLLBL,'You hit him.^E')
	IF( IVAL .EQ. 3 ) CALL MESSAG(ICLWHI,'He parried.^E')
	IF( IVAL .EQ. 4 )
     &	    CALL MESSAG(ICLWHI,'His shield blocked the blow.^E')
	IF( IVAL .EQ. 5 )
     &	    CALL MESSAG(ICLLBL,'He parried but he lost his weapon.^E')

2150	CALL GETVAL( 6, PLAYER, 4, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 2200
	CALL PUTVAL( -6, 0 )
	IF( IVAL .LE. 26 )CALL MESSAG(ICLWHI,'^G^E')
	IF( IVAL .GT. 26 )CALL MESSAG(ICLLBL,'^GThe ^E')
	CALL PNAME( IVAL, -17 )
	CALL STRING(' is dead.^E')

C****** FIND OUT PLAYER'S CURRENT DEXTERITY *********************


2200	DEXTER = UDEX
	CALL GETVAL( 5, PLAYER, INDEX1 )
	IF( INDEX1 .EQ. 0 ) GOTO 2400
	CALL GETVAL( 2, INDEX1, 3, INDEX2 )
	IF( INDEX2 .NE. 0 )  DEXTER = DEXTER - 1
	CALL GETVAL( 2, INDEX1, 2, INDEX2 )
	IF( INDEX2 .EQ. 0 ) GOTO 2300
	CALL GETVAL( 12, INDEX2, INDEX3 )
	CALL GETVAL( 18, INDEX3, IMOD )
	DEXTER = DEXTER - IMOD
2300	CALL GETVAL( 2, INDEX1, 5, INDEX2 )
	IF( INDEX2 .EQ. 0 ) GOTO 2400
	CALL GETVAL( 12, INDEX2, INDEX3 )
	CALL GETVAL( 18, INDEX3, IMOD )
	DEXTER = DEXTER - IMOD/2

C****** UPDATE THE SCREEN ***************************************

2400	CALL UPDSCR( PLAYER, NEWSCR, STRENG, DEXTER, CANSEE, DISIND )
	IF( .NOT. CANSEE(INPLAY) )  INPLAY = PLAYER
	IF( INPLAY .EQ. OLPLAY .AND. .NOT. NEWSCR ) GOTO 2500
	CALL COLCUR( 62, 24 )
	CALL PNAME( INPLAY, 4 )
	OLPLAY = INPLAY
2500	CALL GETVAL( 5, INPLAY, INDEX1 )
	DO 2600 ITEMP = 1, 10
	    INDEX2 = ITEMP
	    IF( INDEX1 .EQ. 0 )  INDEX3 = 0
	    IF( INDEX1 .NE. 0 )CALL GETVAL( 2, INDEX1, INDEX2, INDEX3 )
	    IF( INDEX3 .EQ. BODY(INDEX2) .AND. .NOT. NEWSCR ) GOTO 2600
	    CALL COLCUR( 67, 24-INDEX2 )
	    CALL REPEAT(' ',13)
	    CALL CURSOR( 67, 24-INDEX2 )
	    BODY( INDEX2 ) = INDEX3
	    IF( INDEX3 .NE. 0 ) GOTO 2550
	    IF( INDEX2.LE.2 .OR. INDEX2.EQ.4 .OR. INDEX2.EQ.5 )
     &		CALL PCOLOR(ICLRED)
	    CALL STRING('Nothing^E')
	    CALL PCOLOR( ICLWHI )
	    GOTO 2600
2550	    IF( INDEX3 .EQ. 511 ) CALL COLSTR(ICLGRE,'Oddness^E')
	    IF( INDEX3 .EQ. 511 ) GOTO 2600
	    CALL GETVAL( 12, INDEX3, INDEX4 )
	    CALL GETVAL( 13, INDEX4, OCOST )
	    IF( OCOST .LE. 500 .AND. INDEX4 .NE. DISIND ) GOTO 2560
	    CALL PBACK( ICLYEL )
	    CALL PCOLOR( ICLDBL )
2560	    CALL PNAME( INDEX3, -17 )
	    CALL PBACK( ICLBLA )
	    CALL PCOLOR( ICLWHI )
2600	CONTINUE
	CALL PUTVAL( 32, PLAYER, RECOVR )
	CALL GETVAL( 32, INPLAY, TRECVR )
	IF( TRECVR .EQ. ORECVR ) GOTO 2700
	CALL COLCUR( 55, 10 )
	IF( TRECVR .EQ. 0 )  CALL STRING('             ^E')
	IF( TRECVR .GT. 0 )  CALL STRING('Recovery: ^E')
	IF( TRECVR .GT. 0 )  CALL NUMBER( TRECVR, 3 )
	ORECVR = TRECVR
2700	NEWSCR = .FALSE.

C****** CHECK TO SEE IF HE IS BEING ATTACKED ********************

	CALL GETVAL( 6, PLAYER, 1, ATACKR )
	IF( ATACKR .EQ. 0 ) GOTO 3500
	CALL PUTVAL( -6, 0 )
	IF( ATACKR .NE. 1023 ) GOTO 2710
	CALL MESSAG(ICLRED,
     &	    'You have been disintegrated.  You are dead.^E')
	CALL CEASE( X, Y, Z, PLAYER )
2710	CALL GETVAL( 6, PLAYER, 2, IWEAPN )
	IF( IWEAPN .GT. 511 ) GOTO 2760
	CALL MESSAG(ICLRED,'^E')
	CALL PNAME( ATACKR, -17 )
	IF( IWEAPN .EQ. 0 ) GOTO 2750
	CALL STRING(' attacks with ^E')
	CALL PNAME( IWEAPN, -17 )
	GOTO 2800

2750	CALL STRING(' hits you^E')
	GOTO 2800

2760	CALL MESSAG(ICLRED,'The ^E')
	CALL PNAME( ATACKR, -17 )
	IF( IWEAPN .EQ. 512 ) CALL STRING(' bites you^E')
	IF( IWEAPN .EQ. 513 ) CALL STRING(' claws you^E')
	IF( IWEAPN .EQ. 514 ) CALL STRING(' burns you^E')
	IF( IWEAPN .EQ. 515 ) CALL STRING(' hits you^E')
	IF( IWEAPN .EQ. 516 ) CALL STRING(' smothers you^E')

C****** CAN I PARRY IT? *****************************************

2800	CALL GETVAL( 6, PLAYER, 3, IFORCE )
	CALL GETVAL( 5, PLAYER, INDEX1 )
	IF( IWEAPN.EQ.0 .OR. .NOT. PARRY .OR. INDEX1.EQ.0 .OR.
     &	RECOVR .GT. 0 ) GOTO 3200
	CALL GETVAL( 19, ATACKR, 1, AX )
	CALL GETVAL( 19, ATACKR, 2, AY )
	ADIR = FINDIR( X, Y, AX, AY )
	IF( ADIR .NE. DIR .AND. ADIR .NE. NEWDIR( DIR, 1 )
     & .AND.ADIR .NE. NEWDIR( DIR, -1 ) )GOTO 3200
	CALL GETVAL( 2, INDEX1, 4, INDEX2 )
	IF( INDEX2 .EQ. 0 ) GOTO 3000
	RECOVR = MAX0( 18 - DEXTER, 0 )
	DICE1 = 0
	DO 2900 I = 1, 3
	    DICE1 = DICE1 + IRAN(6)
2900	CONTINUE
	IF( DICE1 .GT. DEXTER ) GOTO 3000
	CALL PUTVAL( 21, ATACKR, 3 )
	CALL GETVAL( 12, INDEX2, INDEX3 )
	CALL GETVAL( 17, INDEX3, IDAM )
	IDAM = IFORCE - (6*(IDAM/10) + MOD( IDAM,10 ) - 5)
	IF( IDAM .LT. 0 .OR. IDAM .GT. (IRAN(6)+IRAN(6)) ) GOTO 3400
	CALL PUTVAL( 21, ATACKR, 5 )
	IVAL = IRAN( 2 )
	IF( IVAL .EQ. 1 )  CALL STRING('.  Your weapon broke^E')
	IF( IVAL .EQ. 2 )  CALL STRING('.  You dropped your weapon^E')
	CALL TAKOUT( INDEX2, PLAYER, FAILED )
	CALL GETVAL( 4, INDEX2, GWEIGH )
	IF( IVAL .EQ. 1 )CALL PUTVAL( 10, INDEX2, 0 )
	GOTO 3400

C****** HOW MUCH DOES SHIELD DETRACT FROM BLOW? *****************

3000	CALL GETVAL( 2, INDEX1, 5, INDEX2 )
	IF( INDEX2 .EQ. 0 ) GOTO 3200
	CALL GETVAL( 12, INDEX2, INDEX3 )
	CALL GETVAL( 18, INDEX3, IMOD )
	DICE1 = 0
	DO 3100 I = 1, 4-IMOD
	    DICE1 = DICE1 + IRAN(6)
3100	CONTINUE
	IF( DICE1 .GT. DEXTER ) GOTO 3200
	IFORCE = IFORCE - IMOD
	IF( IFORCE .GT. 0 ) GOTO 3200
	CALL PUTVAL( 21, ATACKR, 4 )
	CALL STRING('.  Shield absorbs blow.^E')
	GOTO 3500

C****** NOW FIND OUT WHERE IT HIT HIM ***************************

3200	INDEX2 = IRAN( 4 )
	IF( INDEX2 .GT. 1 )  INDEX2 = 2
	IF(INDEX2.EQ.1)CALL STRING('.  Hit on the head with force ^E')
	IF(INDEX2.NE.1)CALL STRING('.  Hit with force ^E')

C****** WHAT EFFECT DOES ARMOR HAVE? ****************************

	IF( INDEX1 .EQ. 0 ) GOTO 3300
	CALL GETVAL( 2, INDEX1, INDEX2, INDEX3 )
	IF( INDEX3 .EQ. 0 ) GOTO 3300
	CALL GETVAL( 12, INDEX3, INDEX4 )
	IF( INDEX3 .EQ. 0 ) GOTO 3300
	IF( INDEX2 .EQ. 1 )  IMOD = 5
	IF( INDEX2 .NE. 1 )  CALL GETVAL( 18, INDEX4, IMOD )
	IFORCE = IFORCE - IMOD
	IF( IFORCE .LT. 0 )  IFORCE = 0
3300	CALL NUMBER( IFORCE )
	STRENG = STRENG - IFORCE
	CALL CHROUT('.')
	CALL PUTVAL( 21, ATACKR, INDEX2 )
	GOTO 3500

3400	CALL STRING('.^E')
	CALL COLSTR(ICLLBL,'  You parried.^E')

3500	IF( STRENG .GT. 0 ) GOTO 3600
	CALL PUTVAL( 6, ATACKR, 4, PLAYER )
	CALL STRING('  You are dead.^E')
	CALL CEASE( X, Y, Z, PLAYER )
C****** INTERPRET COMMAND ***************************************

3600	IF( RECOVR .GT. 0 )  RECOVR = RECOVR - 1
	IF( WRDPTR .GT. 0 ) GOTO 3700
	CALL CURBUF
	CALL COMAND( ICHAR, COMARA, INDEX )
	IF( ICHAR .EQ. -1 .OR. INDEX .EQ. 0 ) GOTO 1600
	CALL PARSE( COMARA, INDEX, PARARA, LENGTH, 40 )
	IF( LENGTH .EQ. 0 ) GOTO 1600
	WRDPTR = 0
3700	CALL WRDNUM( PARARA, WRDPTR, VERB, NAME1, NAME2, LENGTH )
	IF( VERB .EQ. 0 ) GOTO 1600
	IF( VERB .LE. 16 .OR. RECOVR .LE. 0 ) GOTO 3800
	CALL MESSAG(ICLYEL,'You must recover.^E')
	GOTO 1600

3800	GOTO( 3900, 4000, 4100, 4200, 4300, 4600, 4700, 4800, 5010,
     &		5025, 5030, 5035, 5040, 5045, 5060, 5070, 5100, 5300,
     &		5350, 5500, 5700, 5800, 6600, 7300, 7400, 7900, 9000,
     &		10000, 10600, 11300, 11400, 11600, 12100, 12500 ) VERB

C****** EXIT ****************************************************

3900	IF( NAME1 .NE. 0 .OR. NAME2 .NE. 0 ) GOTO 6400
	CALL CEASE( X, Y, Z, PLAYER )

C****** MAP *****************************************************

4000	IF( NAME1 .NE. 0 .OR. NAME2 .NE. 0 ) GOTO 6400
	IF( .NOT. LPRIVD ) GOTO 7200
	CALL MAP( FAILED )
	IF( .NOT. FAILED ) GOTO 1500
	CALL MESSAG(ICLYEL,'Cannot create map.  Sorry.^E')
	GOTO 1600

C****** CLEAR SCREEN ********************************************

4100	IF( NAME1 .NE. 0 .OR. NAME2 .NE. 0 ) GOTO 6400
	NEWSCR = .TRUE.
	GOTO 1600

C****** GAG *****************************************************

4200	IF( NAME1 .NE. 0 .OR. NAME2 .NE. 0 ) GOTO 6400
	CALL USRSET( "2013, 0 )
	GOTO 1500

C****** WHO *****************************************************

4300	IF( NAME1 .LT. 0 ) GOTO 6500
	IF( NAME2 .NE. 0 ) GOTO 8500
	IF( NAME1 .GT. 0 ) GOTO 4500
	CALL MESSAG(ICLWHI,'Players: ^E')
	DO 4400 ITEMP = 1, 26
	    INDEX1 = ITEMP
	    CALL GETVAL( 10, INDEX1, IVAL )
	    IF( IVAL .EQ. 0 ) GOTO 4400
	    CALL CHROUT(' ')
	    CALL PNAME( INDEX1, -17 )
	    CALL CHROUT(':')
	    CALL GETVAL( 7, INDEX1, 2, IVAL )
	    CALL NUMBER( IVAL )
4400	CONTINUE
	GOTO 1600

4500	IF( NAME1 .GT. 52 ) GOTO 7200
	IF( NAME1 .GT. 26 ) GOTO 4550
	CALL GETVAL( 7, NAME1, 1, IJOB )
	IF( IJOB .EQ. 0 ) GOTO 7200
	CALL MESSAG(ICLWHI,'Player ^E')
	CALL PNAME( NAME1, -17 )
	CALL STRING(' is ^E')
	CALL SYSWHO( IJOB )
	GOTO 1600

4550	CALL MESSAG(ICLWHI,'Monster ^E')
	CALL PNAME( NAME1, -17 )
	CALL CHROUT('.')
	GOTO 1600

C****** WHISPER ************************************************

4600	VOL = 0
	GOTO 4900

C****** SAY ****************************************************

4700	VOL = 1
	GOTO 4900

C****** SHOUT **************************************************

4800	VOL = 2
4900	IF( NAME1 .NE. 0 .OR. NAME2 .NE. 0 ) GOTO 6400
	WRDPTR = 0
	IQUOTE = ISERCH( COMARA, '"', INDEX )
	IF( IQUOTE .EQ. 0 )  IQUOTE = ISERCH( COMARA, ',', INDEX )
	IF( IQUOTE .EQ. 0 .OR. IQUOTE .EQ. INDEX ) GOTO 7200
	ILEN = INDEX - IQUOTE
	IF( ILEN .GT. 70 )  ILEN = 70
	CALL LOCK
	CALL PUTVAL( 20, 1, PLAYER )
	CALL PUTVAL( 20, 2, VOL )
	CALL PUTVAL( 20, 3, ILEN )
	CALL PUTVAL( 20, 4, 0 )
	COMARA( IQUOTE ) = ' '
	DO 5000 I = 1, ILEN
	    CALL PUTVAL( 20, I+4, ICON( COMARA( IQUOTE+I ) ) )
	    IF( COMARA( IQUOTE+I ) .EQ. '"' )  CALL PUTVAL( -20, 32 )
	    COMARA( IQUOTE+I ) = ' '
5000	CONTINUE
	CALL UNLOCK
	GOTO 1500

C****** LOOK ****************************************************

5010	IF( NAME1 .NE. 0 .OR. NAME2 .NE. 0 ) GOTO 6400
	CALL MESSAG(ICLWHI,'Hex contains:^E')
	CALL GETVAL( 1, X, Y, Z, INDEX1 )
	DO 5020 INDEX2 = 1, 10
	    CALL GETVAL( 2, INDEX1, INDEX2+0, INDEX3 )
	    IF( INDEX3 .EQ. 0 ) GOTO 5020
	    CALL STRING('  ^E')
	    CALL PNAME( INDEX3, -17 )
5020	CONTINUE
	IVAL = 0
	IF( Z .GT. 1 )  CALL GETVAL( 16, X, Y, Z-1, IVAL )
	IF( IVAL .NE. 0 )  CALL STRING('  down-stair^E')
	IVAL = 0
	CALL GETVAL( 16, X, Y, Z, IVAL )
	IF( IVAL .NE. 0 )  CALL STRING('  up-stair^E')
	GOTO 1600

C****** STATUS **************************************************

5025	IF( NAME2 .LT. 0 ) GOTO 6500
	IF( NAME2 .NE. 0 ) GOTO 8500
	IF( NAME1 .EQ. 0 )  INDEX1 = PLAYER
	IF( NAME1 .NE. 0 )  INDEX1 = HOLDS( PLAYER, NAME1 )
	IF( INDEX1 .EQ. 0 ) GOTO 6900
	CALL MESSAG(ICLWHI,'Status of ^E')
	CALL PNAME( INDEX1, -17 )
	CALL STRING(':  weight: ^E')
	CALL NUMBER( WEIGHT( INDEX1 ) )
	CALL STRING('  holds: ^E')
	CALL NUMBER( CANHLD( INDEX1 ) )
	CALL STRING('  value: $^E')
	CALL NUMBER( COST( INDEX1 ) )
	IF( NAME1 .NE. 0 ) GOTO 5027
	CALL STRING(' at (^E')
	CALL NUMBER( X )
	CALL CHROUT(',')
	CALL NUMBER( Y )
	CALL CHROUT(',')
	CALL NUMBER( Z )
	CALL STRING(') pointing ^E')
	CALL NUMBER( DIR )
5027	CALL CHROUT('.')
	GOTO 1600

C****** ALLIES **************************************************

5030	IF( NAME1 .NE. 0 ) GOTO 7200
	IF( NAME2 .LE. 0 .OR. NAME2 .GT. 26 ) GOTO 7200
	CALL PUTVAL( 23, PLAYER, NAME2, 1 )
	GOTO 1500

C****** ENEMIES *************************************************

5035	IF( NAME1 .NE. 0 ) GOTO 7200
	IF( NAME2 .LE. 0 .OR. NAME2 .GT. 26 ) GOTO 7200
	CALL PUTVAL( 23, PLAYER, NAME2, 0 )
	GOTO 1500

C****** TIME ****************************************************

5040	IF( NAME1 .NE. 0 .OR. NAME2 .NE. 0 ) GOTO 6400
	CALL MESSAG(ICLWHI,'Time:  ^E')
	CALL DATIME( IVAL, IVAL, IVAL, INDEX1, INDEX2, INDEX3, IVAL )
	CALL NUMBER( INDEX1, -2 )
	CALL CHROUT(':')
	CALL NUMBER( INDEX2, -2 )
	CALL CHROUT(':')
	CALL NUMBER( INDEX3, -2 )
	CALL STRING('    Cycles left:  ^E')
	CALL NUMBER( 25 - MOD( RESTR, 25 ) )
	CALL STRING('    LOGNUM/LOGMAX:  ^E')
	ILNUM = IGTAB( "54, "11 )
	CALL NUMBER( ILNUM )
	CALL CHROUT('/')
	ILMAX = IGTAB( "50, "11 )
	CALL NUMBER( ILMAX )
	CALL STRING(' = ^E')
	CALL NUMBER( 100*ILNUM/ILMAX )
	CALL CHROUT('%')
	GOTO 1600

C****** SWEAR ***************************************************

5045	NUMWRN = NUMWRN + 1
	IF( NUMWRN .GT. 1 ) GOTO 5050
	CALL MESSAG(ICLRED,
     & 'This is your first and last warning.  Do not swear.^G^E')
	GOTO 1600

5050	CALL CLRSCR
	CALL COLCUR( 30, 10 )
	CALL STRING('You were warned.^E')
	CALL CEASE( X, Y, Z, -PLAYER )

C****** PARRY ***************************************************

5060	IF( NAME1 .NE. 0 .OR. NAME2 .NE. 0 ) GOTO 6400
	PARRY = .TRUE.
	GOTO 1500

C****** NO PARRY ************************************************

5070	IF( NAME1 .NE. 0 .OR. NAME2 .NE. 0 ) GOTO 6400
	PARRY = .FALSE.
	GOTO 1500

C****** TURN ****************************************************

5100	IF( NAME1 .GE. 0 .OR. NAME2 .NE. 0 ) GOTO 5200
	IF( DIR .EQ. 0 ) GOTO 11500
	IF( DIR .EQ. -NAME1 ) GOTO 5500
	IF( NAME1 .GT. -7 )  DIR = -NAME1
	IF( NAME1 .EQ. -7 )  DIR = NEWDIR( DIR, -1 )
	IF( NAME1 .EQ. -8 )  DIR = NEWDIR( DIR, 1 )
	CALL PUTVAL( 8, PLAYER, DIR )
	GOTO 1500

5200	CALL MESSAG(ICLYEL,'Which way?^E')
	GOTO 1600

C****** RUN *****************************************************

5300	RUNING = 3
	GOTO 5400

C****** JOG *****************************************************

5350	RUNING = 2

5400	RUNING = RUNING - 1

C****** WALK ****************************************************

5500	IF( NAME1 .GT. 0 .OR. NAME2 .NE. 0 ) GOTO 5200
	IF( DIR .EQ. 0 ) GOTO 11500
	IF( NAME1 .EQ. 0 .OR. DIR .EQ. -NAME1 ) GOTO 5600
	RECOVR = RECOVR + MAX0(16-DEXTER,0)/4
	IF( DIR .EQ. 0 )  RECOVR = RECOVR + MAX0(16-DEXTER,0)
	IF( NAME1 .GT. -7 )  DIR = -NAME1
	IF( NAME1 .EQ. -7 )  DIR = NEWDIR( DIR, -1 )
	IF( NAME1 .EQ. -8 )  DIR = NEWDIR( DIR, 1 )
	CALL PUTVAL( 8, PLAYER, DIR )

5600	CALL NEWXY( X, Y, DIR, NX, NY )
	NZ = Z
	IF( NX .EQ. 0 ) GOTO 6100
	GOTO 5900

C****** DECEND **************************************************

5700	IF( NAME1 .NE. 0 .OR. NAME2 .NE. 0 ) GOTO 6400
	NX = X
	NY = Y
	NZ = Z - 1
	IF( NZ .LT. 1 ) GOTO 6100
	CALL GETVAL( 16, NX, NY, NZ, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 6100
	GOTO 5900

C****** ASCEND **************************************************

5800	IF( NAME1 .NE. 0 .OR. NAME2 .NE. 0 ) GOTO 6400
	NX = X
	NY = Y
	NZ = Z + 1
	CALL GETVAL( 16, NX, NY, NZ-1, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 6100
	IF( NZ .EQ. 5 ) GOTO 13000

5900	IF( CANHLD(PLAYER) .EQ. 0 ) GOTO 6000
	IF( DIR .EQ. 0 ) GOTO 11500
	RECOVR = RECOVR + 20/CANHLD(PLAYER)
	IF( ENEMY( X, Y, Z, PLAYER, DEXTER ) ) GOTO 6200
	IF( ENEMY( NX, NY, NZ, PLAYER, DEXTER ) ) GOTO 6300
	CALL GETVAL( 1, NX, NY, NZ, IVAL )
	IF( IVAL .EQ. 0 ) GOTO 6100
	CALL REMOVE( X, Y, Z, PLAYER, FAILED )
	IF( FAILED ) CALL BUGMSG('FMAIN: REMOVE#1^E',X,Y,Z,PLAYER)
	X = NX
	Y = NY
	IF( Z .NE. NZ )  RECOVR = RECOVR + MAX0(16-DEXTER,0)/2
	Z = NZ
	CALL DROP( FAILED, .TRUE., X, Y, Z, PLAYER )
	IF( RUNING .GT. 0 ) GOTO 5400
	GOTO 1500

6000	CALL MESSAG(ICLRED,'You are not strong enough to move.^E')
	GOTO 1600

6100	CALL MESSAG(ICLRED,'You have just bumped into a rock.^E')
	RUNING = 0
	RECOVR = MAX0( RECOVR + 20 - DEXTER, 0 )
	GOTO 1600

6200	CALL MESSAG(ICLRED,'You couldn''t escape.^E')
	GOTO 1600

6300	CALL MESSAG(ICLRED,'You are blocked.^E')
	GOTO 1600

6400	CALL MESSAG(ICLYEL,'Nouns do not apply here.^E')
	GOTO 1600

6500	CALL MESSAG(ICLYEL,'A direction does not apply here.^E')
	GOTO 1600

C****** GET *****************************************************

6600	IF( NAME1 .LT. 0 .OR. NAME2 .LT. 0 ) GOTO 6500
	IF( NAME1 .EQ. 0 ) GOTO 7200
	IF( DIR .EQ. 0 ) GOTO 11500
	IF( NAME2 .EQ. 0 ) GOTO 6800
	IF( NAME2 .LE. 52 ) GOTO 6850
	INDEX2 = HOLDS( PLAYER, NAME2 )
	IF( INDEX2 .EQ. 0 ) GOTO 7100
	INDEX1 = HOLDS( INDEX2, NAME1 )
	IF( INDEX1 .EQ. 0 ) GOTO 6900
	CALL TAKOUT( INDEX1, INDEX2, FAILED )
	IF( FAILED ) GOTO 6900
	IF( CANHLD(PLAYER) .LT. WEIGHT(INDEX2) ) GOTO 6700
	CALL PHOLD( INDEX1, PLAYER, FAILED )
	IF( .NOT. FAILED ) GOTO 1500

6700	CALL MESSAG(ICLYEL,'Carrying too much.  An item dropped.^E')
	CALL DROP( FAILED, .TRUE., X, Y, Z, INDEX1 )
	GOTO 1600

6800	INDEX1 = AT( X, Y, Z, NAME1 )
	IF( INDEX1 .EQ. 0 ) GOTO 7000
	IF( INDEX1 .LE. 52 ) GOTO 7800
	CALL REMOVE( X, Y, Z, INDEX1, FAILED )
	IF( FAILED ) CALL BUGMSG('FMAIN: REMOVE#2^E',X,Y,Z,INDEX1)
	IF( NAME1 .EQ. DISIND ) CALL ADDVAL( 33, 1, 1 )
	IF( CANHLD(PLAYER) .LT. WEIGHT(INDEX1) ) GOTO 6700
	CALL PHOLD( INDEX1, PLAYER, FAILED )
	IF( FAILED ) GOTO 6700
	GOTO 1500

6850	INDEX1 = AT( X, Y, Z, NAME2 )
	IF( INDEX1 .EQ. 0 ) GOTO 10300
	CALL GETVAL( 5, NAME2, INDEX1 )
	IF( INDEX1 .EQ. 0 .OR. INDEX1 .EQ. 511 ) GOTO 6861
	DO 6860 ITEMP = 1, 5
	    CALL GETVAL( 2, INDEX1, ITEMP+5, INDEX2 )
	    IF( INDEX2 .EQ. 0 ) GOTO 6860
	    CALL GETVAL( 12, INDEX2, INDEX3 )
	    IF( INDEX3 .EQ. NAME1 ) GOTO 6870
6860	CONTINUE
6861	CONTINUE
	CALL MESSAG(ICLYEL,'That is not in his belt.^E')
	GOTO 1600

6870	IF( 5*IRAN(6) .GT. DEXTER ) GOTO 6880
	CALL TAKOUT( INDEX2, NAME2, FAILED )
	CALL PHOLD( INDEX2, PLAYER, FAILED )
	IF( FAILED ) GOTO 6700
	RECOVR = MAX0( 40 - 2*DEXTER, 0 )
	GOTO 1600

6880	CALL MESSAG(ICLRED, 'You couldn''t grab it.^E' )
	RECOVR = MAX0( 40 - 2*DEXTER, 0 )
	GOTO 1600

6900	CALL MESSAG(ICLYEL,'You don''t have that.^E')
	GOTO 1600

7000	CALL MESSAG(ICLYEL,'You can''t see one here.^E')
	GOTO 1600

7100	CALL MESSAG(ICLYEL,'You aren''t carrying that container.^E')
	GOTO 1600

7200	CALL MESSAG(ICLYEL,'What?^E')
	GOTO 1600

7300	IF( NAME1 .LE. 0 ) GOTO 7200
	IF( NAME2 .NE. 0 ) GOTO 8500
	INDEX1 = HOLDS( PLAYER, NAME1 )
	IF( INDEX1 .EQ. 0 ) GOTO 6900
	CALL TAKOUT( INDEX1, PLAYER, FAILED )
	CALL PHOLD( INDEX1, PLAYER, FAILED )
	GOTO 1500

C****** PUT *****************************************************

7400	IF( NAME1 .LT. 0 .OR. NAME2 .LT. 0 ) GOTO 6500
	IF( NAME1 .EQ. 0 ) GOTO 7200
	IF( DIR .EQ. 0 ) GOTO 11500
	INDEX1 = HOLDS( PLAYER, NAME1 )
	IF( NAME1 .EQ. DISIND .AND. NAME2 .NE. 0 ) GOTO 7800
	IF( INDEX1 .EQ. 0 ) GOTO 6900
	CALL TAKOUT( INDEX1, PLAYER, FAILED )
	IF( FAILED ) GOTO 6900
	IF( NAME2 .EQ. 0 ) GOTO 7500
	INDEX2 = HOLDS( PLAYER, NAME2 )
	IF( INDEX1 .EQ. INDEX2 ) GOTO 7700
	IF( INDEX2 .EQ. 0 ) GOTO 7600
	CALL GETVAL( 5, INDEX2, INDEX3 )
	IF( INDEX3 .EQ. 511 ) GOTO 7700
	IF( CANHLD(INDEX2) .LT. WEIGHT(INDEX1) ) GOTO 6700
	CALL PUTIN( INDEX1, INDEX2, FAILED )
	IF( FAILED ) GOTO 6700
	GOTO 1500

7500	CALL DROP( FAILED, .TRUE., X, Y, Z, INDEX1 )
	GOTO 1500

7600	CALL PHOLD( INDEX1, PLAYER, FAILED )
	GOTO 7100

7700	CALL PHOLD( INDEX1, PLAYER, FAILED )
7800	CALL MESSAG(ICLYEL,'That would be *VERY* difficult.^E')
	GOTO 1600

C****** INVENT **************************************************

7900	IF( NAME1 .LT. 0 ) GOTO 6500
	IF( NAME2 .NE. 0 ) GOTO 8500
	IF( NAME1 .LT. 0 ) GOTO 6500
	IF( NAME1 .LE. 52 ) GOTO 8300
	INDEX1 = HOLDS( PLAYER, NAME1 )
	IF( INDEX1 .EQ. 0 ) GOTO 6900
8000	CALL GETVAL( 5, INDEX1, INDEX2 )
	IF( INDEX2 .EQ. 511 ) GOTO 7800
	CALL MESSAG(ICLWHI,'Inventory: ^E')
	IF( INDEX2 .EQ. 0 ) GOTO 8200
	DO 8100 INDEX3 = 1, 10
	    CALL GETVAL( 2, INDEX2, INDEX3+0, INDEX4 )
	    IF( INDEX4 .EQ. 0 ) GOTO 8100
	    CALL CHROUT(' ')
	    CALL PNAME( INDEX4, -17 )
8100	CONTINUE
	GOTO 1600

8200	CALL STRING('Nothing.^E')
	GOTO 1600

8300	IF( NAME1 .EQ. 0 )  NAME1 = PLAYER
	IF( .NOT. CANSEE(NAME1) ) GOTO 8400
	INPLAY = NAME1
	GOTO 1500

8400	CALL MESSAG(ICLYEL,'You can''t see him.^E')
	GOTO 1600

8500	CALL MESSAG(ICLYEL,'Second noun does not apply here.^E')
	GOTO 1600

C****** ATTACK **************************************************

9000	IF( DIR .EQ. 0 ) GOTO 11500
	IF( NAME1 .EQ. 0 )  NAME1 = OLDNM1
	IF( NAME2 .EQ. 0 )  NAME2 = OLDNM2
	IF( NAME1 .LE. 0 .OR. NAME1 .GT. 52 ) GOTO 7800
	IF( NAME2 .LE. 52 ) GOTO 7800
	OLDNM1 = NAME1
	OLDNM2 = NAME2
	CALL GETVAL( 24, NAME2, IVAL )
	IF( IVAL .GT. 1 ) GOTO 11900
	INDEX1 = HOLDS( PLAYER, NAME2 )
	IF( INDEX1 .EQ. 0 ) GOTO 6900
	CALL GETVAL( 5, PLAYER, INDEX2 )
	CALL GETVAL( 2, INDEX2, 4, INDEX3 )
	IF( INDEX3 .EQ. INDEX1 ) GOTO 9200
9100	CALL MESSAG(ICLYEL,'That is not in weapon arm.^E')
	GOTO 1600

9200	DO 9300 I = -1, 1
	    CALL NEWXY( X, Y, NEWDIR( DIR, I+0 ), NX, NY )
	    IF( NX .EQ. 0 ) GOTO 9300
	    INDEX2 = AT( NX, NY, Z, NAME1 )
	    IF( INDEX2 .NE. 0 ) GOTO 9400
9300	CONTINUE
	CALL MESSAG(ICLYEL,'He is not attackable.^E')
	GOTO 1600

9400	RECOVR = MAX0( 20-DEXTER, 0 )
	DICE1 = 0
	DO 9500 I = 1, 3
	    DICE1 = DICE1 + IRAN(6)
9500	CONTINUE
	IF( DICE1 .NE. 17 ) GOTO 9600
	CALL MESSAG(ICLRED,'You fool, you dropped your weapon.^E')
	CALL TAKOUT( INDEX1, PLAYER, FAILED )
	CALL DROP( FAILED, .TRUE., X, Y, Z, INDEX1 )
	GOTO 1600

9600	IF( DICE1 .NE. 18 ) GOTO 9700
	CALL MESSAG(ICLRED,'^GYou clod, you broke your weapon.^E')
	CALL TAKOUT( INDEX1, PLAYER, FAILED )
	CALL PUTVAL( 10, INDEX1, 0 )
	GOTO 1600

9700	CALL GETVAL( 12, INDEX1, INDEX2 )
	CALL GETVAL( 17, INDEX2, IDAM )
	CALL GETVAL( 18, INDEX2, ISTR )
	IMOD = USTREN - ISTR
	RECOVR = MAX0( 0, RECOVR-IMOD*2 )
	IF( IMOD .GT. 0 )  IMOD = 0
	CALL MESSAG(ICLLBL,'Effective dexterity: ^E')
	CALL NUMBER( DEXTER+IMOD )
	IF( DICE1 .GT. DEXTER+IMOD ) GOTO 9900
	INDICE = IDAM/10
	DICE2 = 0
	DO 9800 I = 1, INDICE
	    DICE2 = DICE2 + IRAN(6)
9800	CONTINUE
	DICE2 = DICE2 + MOD( IDAM, 10 ) - 5 + IMOD
	IF( DICE2 .LT. 0 )  DICE2 = 0
	IF( DICE1 .EQ. 3 )  DICE2 = DICE2 * 3
	IF( DICE1 .EQ. 4 )  DICE2 = DICE2 * 2
	IF( DICE1 .LE. 4 )
     &  CALL STRING('.  Critical hit.  Possible damage: ^E')
	IF( DICE1 .GE. 5 )
     &  CALL STRING('.  Attack accurate.  Possible damage: ^E')
	CALL NUMBER( DICE2 )
	CALL PUTVAL( 6, NAME1, 1, PLAYER )
	CALL PUTVAL( 6, NAME1, 2, INDEX1 )
	CALL PUTVAL( 6, NAME1, 3, DICE2 )
	IF( NAME1 .GT. 26 )CALL ADDVAL( 7, PLAYER, 2, DICE2 )
	CALL CHROUT('.')
	GOTO 1600

9900	CALL STRING('.  You missed.^E')
	GOTO 1600

C****** HIT *****************************************************

10000	IF( DIR .EQ. 0 ) GOTO 11500
	IF( NAME1 .EQ. 0 )  NAME1 = OLDNM1
	IF( NAME1 .LE. 0 .OR. NAME1 .GT. 52 ) GOTO 7800
	IF( NAME2 .NE. 0 ) GOTO 8500
	OLDNM1 = NAME1
	IF( AT( X, Y, Z, NAME1 ) .EQ. 0 ) GOTO 10300
	RECOVR = MAX0( 16 - DEXTER, 0 )
	DICE1 = 0
	DO 10100 I = 1, 3
	    DICE1 = DICE1 + IRAN(6)
10100	CONTINUE
	IF( DEXTER .LE. DICE1 ) GOTO 10200
	HIT = STRENG - 8
	IF( HIT .LT. 1 )  HIT = 1
	CALL PUTVAL( 6, NAME1, 1, PLAYER )
	CALL PUTVAL( 6, NAME1, 2, 0 )
	CALL PUTVAL( 6, NAME1, 3, HIT )
	IF( NAME1 .GT. 26 )CALL ADDVAL( 7, PLAYER, 2, 1 )
	GOTO 1600

10200	CALL MESSAG(ICLYEL,'Your blow missed.^E')
	GOTO 1600

10300	CALL MESSAG(ICLYEL,'He is not in this hex.^E')
	GOTO 1600

C****** THROW ***************************************************

10600	IF( NAME1 .LE. 52 ) GOTO 7800
	IF( NAME2 .EQ. 0 )  NAME2 = OLDNM1
	OLDNM1 = NAME2
	IF( NAME2 .LE. 0 .OR. NAME2 .GT. 52 ) GOTO 11200
	IF( DIR .EQ. 0 ) GOTO 11500
	IF( .NOT. CANSEE(NAME2) ) GOTO 11100
	INDEX1 = HOLDS( PLAYER, NAME1 )
	CALL GETVAL( 24, NAME1, IVAL )
	IF( IVAL .NE. 0 .AND. IVAL .NE. 2 ) GOTO 11900
	IF( INDEX1 .EQ. 0 ) GOTO 6900
	CALL GETVAL( 5, PLAYER, INDEX2 )
	CALL GETVAL( 2, INDEX2, 4, INDEX3 )
	IF( INDEX3 .NE. INDEX1 ) GOTO 9100
	CALL GETVAL( 4, INDEX1, GWEIGH )
	DGO = STRENG - GWEIGH
	CALL GETVAL( 19, NAME2, 1, AX )
	CALL GETVAL( 19, NAME2, 2, AY )
	IF( AX .EQ. X .AND. AY .EQ. Y ) GOTO 10750
	NX = X
	NY = Y
	DIST = 0
	RECOVR = MAX0( 18 - DEXTER, 0 )
	CALL TAKOUT( INDEX1, PLAYER, FAILED )
10700	IF( DGO .LT. DIST ) GOTO 11000
	DIST = DIST + 1
	ADIR = FINDIR( NX, NY, AX, AY )
	CALL NEWXY( NX, NY, ADIR, NX, NY )
	IF( NX .EQ. AX .AND. NY .EQ. AY ) GOTO 10800
	GOTO 10700

10750	CALL MESSAG(ICLYEL,'You can''t when he is in your hex.^E')
	GOTO 1600

10800	DICE1 = 0
	DO 10900 I = 1, 3
	    DICE1 = DICE1 + IRAN(6)
10900	CONTINUE
	IF( DICE1 .GT. DEXTER - DIST/3 ) GOTO 11000
	CALL DROP( FAILED, .TRUE., AX, AY, Z, INDEX1 )
	NAME1 = NAME2
	GOTO 9700

11000	CALL MESSAG(ICLYEL,'You missed.^E')
	CALL DROP( FAILED, .TRUE., NX, NY, Z, INDEX1 )
	GOTO 1600

11100	CALL MESSAG(ICLYEL,'You can''t see him here.^E')
	GOTO 1600

11200	CALL MESSAG(ICLYEL,'That is pure idiocy.^E')
	GOTO 1600

C****** REST ****************************************************

11300	IF( NAME1 .NE. 0 .OR. NAME2 .NE. 0 ) GOTO 6400
	DIR = 0
	CALL PUTVAL( 8, PLAYER, DIR )
	GOTO 1500

C****** WAKE ****************************************************

11400	IF( NAME1 .NE. 0 .OR. NAME2 .NE. 0 ) GOTO 6400
	DIR = IRAN( 6 )
	CALL PUTVAL( 8, PLAYER, DIR )
	RECOVR = MAX0( 20 - DEXTER, 0 )
	GOTO 1500

11500	CALL MESSAG(ICLYEL,'You can''t while you''re on the ground.^E')
	GOTO 1600

C****** FIRE ****************************************************

11600	IF( NAME1 .EQ. 0 )  NAME1 = OLDNM2
	IF( NAME2 .EQ. 0 )  NAME2 = OLDNM1
	OLDNM1 = NAME2
	OLDNM2 = NAME1
	IF( DIR .EQ. 0 ) GOTO 11500
	IF( NAME1 .LE. 52 ) GOTO 7800
	CALL GETVAL( 24, NAME1, IVAL )
	IF( IVAL .NE. 3 ) GOTO 11900
	IF( NAME2 .LE. 0 .OR. NAME2 .GT. 52 ) GOTO 7800
	IF( .NOT. CANSEE(NAME2) ) GOTO 8400
	INDEX1 = HOLDS( PLAYER, NAME1 )
	IF( INDEX1 .EQ. 0 ) GOTO 6900
	CALL GETVAL( 5, PLAYER, INDEX2 )
	CALL GETVAL( 2, INDEX2, 4, INDEX3 )
	IF( INDEX1 .NE. INDEX3 ) GOTO 9100
	IF( QUIVER .EQ. 0 )CALL FINWRD( ISXBIT('quiver'), QUIVER )
	INDEX2 = HOLDS( PLAYER, QUIVER )
	IF( INDEX2 .EQ. 0 ) GOTO 11800
	CALL GETVAL( 4, INDEX2, GWEIGH )
	CALL ADDVAL( -4, -1 )
	IF( GWEIGH .GT. 1 ) GOTO 11650
	CALL PUTVAL( -4, 10 )
	CALL TAKOUT( INDEX2, PLAYER, FAILED )
11625	I = IRAN( 80 )
	CALL GETVAL( 11, I, IVAL )
	IF( IVAL .NE. 0 ) GOTO 11625
	CALL PUTVAL( -11, INDEX2 )
11650	CALL GETVAL( 18, NAME1, ISTR )
	RECOVR = MAX0( 5*ISTR - 25 - DEXTER, 0 )
	NAME1 = NAME2
	CALL GETVAL( 19, NAME1, 1, AX )
	CALL GETVAL( 19, NAME1, 2, AY )
	IF( AX .EQ. X .AND. AY .EQ. Y ) GOTO 10750
	DICE1 = 0
	DO 11700 I = 1, 3
	    DICE1 = DICE1 + IRAN( 6 )
11700	CONTINUE
	GOTO 9700

11800	CALL MESSAG(ICLYEL,'You don''t have a quiver.^E')
	GOTO 1600

11900	CALL MESSAG(ICLYEL,'It would be very difficult to use the weapon
     & that way.^E')
	GOTO 1600

C****** DESTROY *************************************************

12100	IF( NAME1 .GE. 0 .OR. NAME2 .NE. 0 ) GOTO 5200
	INDEX1 = HOLDS( PLAYER, DISIND )
	IF( INDEX1 .EQ. 0 ) GOTO 12150
	CALL NEWXY( X, Y, -NAME1, NX, NY )
	IF( NX .LT. 2 .OR. NX .GT. 48 .OR. NY .LT. 2 .OR. NY .GT. 48 )
     & GOTO 5200
	CALL GETVAL( 4, INDEX1, GWEIGH )
	IF( GWEIGH .LE. 3 ) GOTO 12125
	CALL ADDVAL( -4, -1 )
	CALL GETVAL( 1, NX, NY, Z, IVAL )
	IF( IVAL .EQ. 0 ) CALL PUTVAL( -1, 511 )
	IF( GWEIGH .GT. 4 ) GOTO 1500
	CALL MESSAG(ICLRED,'The disintegrator is glowing red.^G^E')
	GOTO 1600

12125	DO 12135 DDIR = 1, 6
	    CALL NEWXY( X, Y, DDIR+0, NX, NY )
	    IF( NX.LT.2.OR.NX.GT.48.OR.NY.LT.2.OR.NY.GT.48 ) GOTO 12135
	    CALL GETVAL( 1, NX, NY, Z, IVAL )
	    IF( IVAL .EQ. 511 ) GOTO 12135
	    IF( IVAL .EQ. 0 ) CALL PUTVAL( -1, 511 )
	    IF( IVAL .EQ. 0 ) GOTO 12135
	    DO 12134 INDEX1 = 1, 10
		CALL GETVAL( 2, IVAL, INDEX1+0, INDEX2 )
		IF( INDEX2 .LT. 1 .OR. INDEX2 .GT. 52 ) GOTO 12134
		CALL PUTVAL( 6, INDEX2, 1, 1023 )
		CALL PUTVAL( 6, INDEX2, 3, 1023 )
12134	    CONTINUE
12135	CONTINUE
	CALL MESSAG(ICLRED,'The disintegrator has reached critical mass.
     &  You are dead.^G^E')
	CALL CEASE( X, Y, Z, PLAYER )
	GOTO 1600

12150	CALL MESSAG(ICLYEL,'You need the disintegrator.^E')
	GOTO 1600

C****** CAST ****************************************************

12500	IF( NAME1.LT.52 .OR. NAME2.LT.1 .OR. NAME2.GT.52 ) GOTO 7800
	CALL MESSAG(ICLLBL,'Casting spell ^E')
	CALL PNAME( NAME1, -17 )
	CALL STRING(' at ^E')
	CALL PNAME( NAME2, -17 )
	GOTO 1600

13000	CALL CLRSCR
	CALL COLCUR( 5, 10 )
	CALL STRING('You have left the dungeon with^E')
	IF( HOLDS( PLAYER, DISIND ) .NE. 0 ) GOTO 13100
	CALL STRING('out the disintegrator.  You have failed.^M^J^E')
	CALL CEASE( X, Y, Z, PLAYER )

13100	CALL STRING(' the disintegrator and $^E')
	IVAL = COST( PLAYER )
	CALL NUMBER( IVAL )
	CALL STRING(' to your credit.^G^G^E')
	CALL COLCUR( 32, 8 )
	CALL STRING('Congratulations.^M^J^B')
	CALL PUTVAL( 20, 75, PLAYER )
	CALL OFILE( 2, FILESP, 0 )
	IF( ERROR(0) ) GOTO 13200
	FILESP( 5 ) = ISXBIT('DAT')
	CALL RFILE( 2, FILESP )
	IF( ERROR(0) ) GOTO 13200
	CALL OFILE( 3, FILESP, 0 )
	IF( ERROR(0) ) GOTO 13200
	FILESP( 5 ) = ISXBIT('TMP')
	CALL WFILE( 3, FILESP )
	IF( ERROR(0) ) GOTO 13200
	CALL XFER( 2, 3 )
	CALL SELECT( 3 )
	CALL DATIME(INDEX1,INDEX2,INDEX3,INDEX4,INDEX5,INDEX6,IVAL)
	CALL NUMBER( INDEX1 )
	CALL CHROUT('-')
	CALL STRING( MONTH( INDEX2 ), 5, 3 )
	CALL CHROUT('-')
	CALL NUMBER( INDEX3 )
	CALL CHROUT(' ')
	CALL NUMBER( INDEX4, -2 )
	CALL CHROUT(':')
	CALL NUMBER( INDEX5, -2 )
	CALL CHROUT(':')
	CALL NUMBER( INDEX6, -2 )
	CALL STRING('  "^E')
	CALL PNAME( PLAYER, -17 )
	CALL STRING('"  Exp:^E')
	CALL GETVAL( 7, PLAYER, 2, IVAL )
	CALL NUMBER( IVAL )
	CALL STRING('   Str: ^E')
	CALL NUMBER( STRENG )
	CALL CHROUT('(')
	CALL NUMBER( USTREN )
	CALL STRING(')  Dex: ^E')
	CALL NUMBER( DEXTER )
	CALL CHROUT('(')
	CALL NUMBER( UDEX )
	CALL STRING(')  Val: $ ^E')
	CALL NUMBER( COST( PLAYER ) )
	CALL STRING('^M^J^I^E')
	CALL GETVAL( 7, PLAYER, 1, IVAL )
	CALL SYSWHO( IVAL )
	CALL STRING('^M^J^B')
	IVAL = FILESP( 4 )
	FILESP( 4 ) = 0
	CALL RNFILE( 2, FILESP )
	FILESP( 4 ) = IVAL
	FILESP( 5 ) = ISXBIT('DAT')
	CALL RNFILE( 3, FILESP )
	CALL SELECT( 0 )
13200	CALL CEASE( X, Y, Z, PLAYER )
	END

	SUBROUTINE COLCUR( IX, IY )
	CALL DEFCOL
	CALL CURSOR( IX, IY )
	RETURN
	END

    	SUBROUTINE COLSTR( ICOL, MSGARA )
	INTEGER MSGARA( 16 )
	CALL PCOLOR( ICOL )
	CALL STRING( MSGARA )
	RETURN
	END
