C	@HDR@	$Id$
C	@HDR@		Copyright 1982-2025 by
C	@HDR@		Christopher Caldwell/Brightsands
C	@HDR@		P.O. Box 401, Bailey Island, ME 04003
C	@HDR@		All Rights Reserved
C	@HDR@
C	@HDR@	This software comprises unpublished confidential information
C	@HDR@	of Brightsands and may not be used, copied or made available
C	@HDR@	to anyone, except in accordance with the license under which
C	@HDR@	it is furnished.
C	*** LIFE.FOR ***
	SUBROUTINE FMAIN

	IMPLICIT INTEGER ( A - Z )
	INTEGER CELLS( 80, 20, 2 ), XDIR(9), YDIR(9)
	INTEGER COMARA(60), PARARA(20), FILESP(13)
	INTEGER CELCHR( 26, 4 )
	INTEGER CMDS(17)
	LOGICAL NEWFLG, ERROR, EOF, CHANGE

	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA

	DATA SPE/79/, NAPTIM/1000/, MUT/79/
	DATA XDIR/-1,0,1,-1,0,1,-1,0,1/
	DATA YDIR/-1,-1,-1,0,0,0,1,1,1/
	DATA ((CELCHR( I, J ), I=1, 26 ), J=1,4)/26*2,26*3,26*3,26*3/

	CMDS( 1) = ISXBIT('CLEAR')
	CMDS( 2) = ISXBIT('INPUT')
	CMDS( 3) = ISXBIT('EXIT')
	CMDS( 4) = ISXBIT('KILL')
	CMDS( 5) = ISXBIT('READ')
	CMDS( 6) = ISXBIT('SAVE')
	CMDS( 7) = ISXBIT('DELETE')
	CMDS( 8) = ISXBIT('NEW')
	CMDS( 9) = ISXBIT('GENERATION')
	CMDS(10) = ISXBIT('GO')
	CMDS(11) = ISXBIT('CENTER')
	CMDS(12) = ISXBIT('SET')
	CMDS(13) = ISXBIT('EDIT')
	CMDS(14) = ISXBIT('TIME')
	CMDS(15) = ISXBIT('STATUS')
	CMDS(16) = ISXBIT('CROSSBREED')
	CMDS(17) = ISXBIT('HELP')

	ICLWHI = 1
	ICLDBL = 2
	ICLRED = 3
	ICLLBL = 4
	ICLPUR = 5
	ICLGRE = 6
	ICLYEL = 7
	ICLBLA = 8

	CALL SETTTY( COMARA, PARARA, ILEN, PRIVD, FILESP )
	CALL DEFCOL

100	CALL CLRSCR
	CALL CURSOR( 1, 4 )
	CALL COLSTR(ICLLBL,'Generation:    0^E')
	GEN = 0
	IAR = 1
	MINX = 80
	MAXX = 1
	MINY = 20
	MAXY = 1
	CALL ERASE( CELLS, IAR, MINX, MAXX, MINY, MAXY )

200	CALL CURSOR( 1, 2 )
	CALL COLSTR(ICLLBL,'Command:^E')
	CALL REPEAT(' ',52)
	CALL CURSOR( 10, 2 )
	CALL CURBUF
	CALL GETSTR( COMARA, 60, ILEN )
	IF( .NOT. NEWFLG ) GOTO 205
	CALL NEW( CELLS, IAR, MINX, MAXX, MINY, MAXY, GEN )
	NEWFLG = .FALSE.
	GOTO 208
205	CALL CURSOR( 1, 1 )
	CALL REPEAT(' ',79)
208	IF( ILEN .EQ. 0 ) GOTO 200
	CALL ALLCAP( COMARA, ILEN )
	PARARA( 2 ) = 0
	CALL PARSE( COMARA, ILEN, PARARA, IPMAX, 20 )
	IF( IPMAX .EQ. 0 ) GOTO 200
	ICOM1 = ISRSIX( CMDS, PARARA(1), 17 )

	IF( ICOM1 .LT. 0 .OR. ICOM1 .GT. 17 ) GOTO 209

	CALL CONVRT( PARARA(2), 1, 6, ICOM2, 0 )
	GOTO(100,300,400,500,600,700,800,900,1000,1100,1200,
     & 1300,1400,1500,1600,1690,220) ICOM1

209	CALL CURSOR( 1, 1 )
	CALL COLSTR(ICLYEL,'Illegal command.  Type help for help.^E')
	GOTO 200

220	CALL CLRSCR
	CALL STRING('Commands are:^M^J
     &CLEAR                                    Kill everything^M^J
     &INPUT <SPECIES> <X> <Y>                  Put species at X-Y^M^J
     &KILL <SPECIES>                           Kill all species^M^J
     &READ <FILESPEC>                          Read cells from file^M^J
     &SAVE <FILESPEC>                          Save cells on file^M^J
     &DELETE <FILESPEC>                        Delete file^M^J
     &NEW                                      Reprint screen^M^J
     &GENERATION                               Reset generation^M^J
     &GO <GEN>                                 Grow until GEN^M^J
     &CENTER                                   Center cell pattern^M^J
     &TIME <MILLISECONDS>                      Set interval time^M^J
     &CROSSBREED <SPECIES>                     Set cross breed^M^J
     &STATUS                                   Print out status^M^J
     &EDIT                                     Enter edit mode^M^J
     &                  A - Z                  Input cell^M^J
     &                 <SPACE>                 Kill cell^M^J
     &                    0                    Exit edit mode^M^J
     &                  1 - 9                  Move cursor^M^J
     &SET <SPECIES MNLIV MXLIV MNBRN MXBRN>    Set parameters:^M^J
     &                                         Minimum & maximum^M^J
     &                                         to live & be born^E')
	NEWFLG = .TRUE.
	GOTO 200

225	CALL CURSOR( 1, 1 )
	CALL COLSTR(ICLYEL,'Illegal argument for ^E')
	CALL NETSIX( PARARA(1) )
	GOTO 200

300	IF( ICOM2 .GE. 65 .AND. ICOM2 .LE. 91 ) SPE = ICOM2
	CALL GETNUM( COMARA, ILEN, X, 10, Y, 10 )
	IF(X.LT.1.OR.X.GT.80.OR.Y.LT.1.OR.Y.GT.20) GOTO 225
	IF( X .LT. MINX ) MINX = X
	IF( X .GT. MAXX ) MAXX = X
	IF( Y .LT. MINY ) MINY = Y
	IF( Y .GT. MAXY ) MAXY = Y
	CELLS( X, Y, IAR ) = SPE
	CALL CURSOR( X, Y+4 )
	CALL CHROUT( SPE )
	GOTO 200

400	CALL CURBUF
	CALL GRAFOF
	CALL TSTOP
	CALL GRAFON
	GOTO 900

500	CALL GETNUM( COMARA, ILEN, X, 10, Y, 10 )
	IF(X.LT.1.OR.X.GT.80.OR.Y.LT.1.OR.Y.GT.20) GOTO 510
	CALL CURSOR( X, Y+4 )
	CALL CHROUT( ' ' )
	CELLS( X, Y, IAR ) = 32
	GOTO 200

510	IF( ICOM2 .LT. 65 .OR. ICOM2 .GT. 91 ) GOTO 225
	IF( MAXX .LT. MINX ) GOTO 200
	DO 520 X = MINX, MAXX
	DO 520 Y = MINY, MAXY
	    IF( CELLS( X, Y, IAR ) .NE. ICOM2 )GOTO 520
	    CELLS( X, Y, IAR ) = 32
	    CALL CURSOR( X+0, Y+4 )
	    CALL CHROUT( ' ' )
520	CONTINUE
	GOTO 200

600	ISPAC = ISERCH( COMARA, ' ', ILEN )
	IF( ISPAC .EQ. 0 .OR. ISPAC .EQ. ILEN ) GOTO 225
	CALL SCAN( ISPAC, ILEN, COMARA, FILESP )
	IF( ERROR(0) ) GOTO 225
	CALL OFILE( 2, FILESP, 0 )
	IF( ERROR(0) ) GOTO 225
	CALL RFILE( 2, FILESP )
	IF( ERROR(0) ) GOTO 225
	CALL OUTSPL( PARARA(1), FILESP )
610	CALL GETSTR( COMARA, 60, ILEN, 2, EOF )
	IF( EOF ) GOTO 711
	IF( ILEN .EQ. 0 .OR. COMARA(1) .EQ. ';' ) GOTO 610
	TEMP = ICON( COMARA(1) )
	IF( TEMP .LT. 65 .OR. TEMP .GT. 91 ) GOTO 620
	CALL GETNUM( COMARA, ILEN, X, 10, Y, 10 )
	IF(X.LT.1.OR.X.GT.80.OR.Y.LT.1.OR.Y.GT.20) GOTO 630
	IF( X .LT. MINX ) MINX = X
	IF( X .GT. MAXX ) MAXX = X
	IF( Y .LT. MINY ) MINY = Y
	IF( Y .GT. MAXY ) MAXY = Y
	CELLS( X, Y, IAR ) = TEMP
	CALL CURSOR( X, Y+4 )
	CALL CHROUT( TEMP )
	GOTO 610

615	CALL CURSOR( 1, 1 )
	CALL COLSTR(ICLRED,'Cannot read ^E')
	CALL OUTSPC( FILESP )
	GOTO 200

620	CALL CURSOR( 1, 1 )
	CALL COLSTR(ICLYEL,'Unknown species: ^E')
	GOTO 640

630	CALL CURSOR( 1, 1 )
	CALL COLSTR(ICLYEL,'Bad coordinates: ^E')

640	CALL STRING( COMARA, 1, 43 )
	GOTO 711

700	ISPAC = ISERCH( COMARA, ' ', ILEN )
	IF( ISPAC .EQ. 0 .OR. ISPAC .EQ. ILEN ) GOTO 225
	CALL SCAN( ISPAC, ILEN, COMARA, FILESP )
	IF( ERROR(0) ) GOTO 225
	CALL OFILE( 2, FILESP, 0 )
	IF( ERROR(0) ) GOTO 750
	CALL WFILE( 2, FILESP )
	IF( ERROR(0) ) GOTO 750
	CALL OUTSPL( PARARA(1), FILESP )
	IF( MAXX .LT. MINX ) GOTO 200
	CALL SELECT( 2 )
	DO 710 X = MINX, MAXX
	DO 710 Y = MINY, MAXY
	    IF( CELLS( X, Y, IAR ) .LE. 32 ) GOTO 710
	    CALL CHROUT( CELLS( X, Y, IAR ) )
	    CALL STRING('  (^E')
	    CALL NUMBER( X+0, 2 )
	    CALL CHROUT(',')
	    CALL NUMBER( Y+0, 2 )
	    CALL STRING(')^M^J^E')
710	CONTINUE
711	CALL CLOSE( 2 )
	CALL SELECT( 0 )
	GOTO 200

750	CALL CURSOR( 1, 1 )
	CALL COLSTR(ICLRED,'Cannot write ^E')
	CALL OUTSPC( FILESP )
	GOTO 200

800	ISPAC = ISERCH( COMARA, ' ', ILEN )
	IF( ISPAC .EQ. 0 .OR. ISPAC .EQ. ILEN ) GOTO 225
	CALL SCAN( ISPAC, ILEN, COMARA, FILESP )
	IF( ERROR(0) ) GOTO 225
	CALL OFILE( 2, FILESP, 0 )
	IF( ERROR(0) ) GOTO 225
	CALL RFILE( 2, FILESP )
	IF( ERROR(0) ) GOTO 225
	CALL OUTSPL( PARARA(1), FILESP )
	FILESP( 4 ) = 0
	CALL RNFILE( 2, FILESP )
	GOTO 200

900	CALL NEW( CELLS, IAR, MINX, MAXX, MINY, MAXY, GEN )
	GOTO 200

1000	CALL GETNUM( COMARA, ILEN, GEN, 10 )
	IF( GEN .LT. 0 .OR. GEN .GT. 9999 ) GEN = 0
	CALL CURSOR( 1, 4 )
	CALL COLSTR(ICLLBL,'Generation: ^E')
	CALL NUMBER( GEN, 4 )
	GOTO 200

1100	CALL GETNUM( COMARA, ILEN, GENTO, 10 )
	IF( GENTO .LE. GEN .OR. GENTO .GT. 9999 ) GENTO = 9999
	CALL ERASE( CELLS, IAR, MINX, MAXX, MINY, MAXY )
1150	GEN = GEN + 1
	CALL CURSOR( 1, 4 )
	CALL COLSTR(ICLLBL,'Generation: ^E')
	CALL NUMBER( GEN, 4 )
	CALL CURBUF
	NEWAR = 3-IAR
	CHANGE = .FALSE.
	IF( MAXX .LT. MINX ) GOTO 1191
	MINXS = MAX0( MINX-1, 1 )
	MAXXS = MIN0( MAXX+1, 80 )
	MINYS = MAX0( MINY-1, 1 )
	MAXYS = MIN0( MAXY+1, 20 )
	DO 1190 X = MINXS, MAXXS
	DO 1190 Y = MINYS, MAXYS
	    CELLS( X, Y, NEWAR ) = 32
	    CELCNT = 0
	    IT =32 
	    DO 1165 LX = X-1, X+1
	    IF( LX .LT. MINXS .OR. LX .GT. MAXXS ) GOTO 1165
	    DO 1160 LY = Y-1, Y+1
		IF( LY .LT. MINYS .OR. LY .GT. MAXYS ) GOTO 1160
		IF( CELLS( LX, LY, IAR ) .LE. 32 ) GOTO 1160
		CELCNT = CELCNT + 1
		IF(IT.NE.32.AND.IT.NE.CELLS(LX,LY,IAR)) GOTO 1155
		IT = CELLS( LX, LY, IAR )
		GOTO 1160
1155		IT = MUT
1160	    CONTINUE
1165	    CONTINUE
	    TEMP = CELLS( X, Y, IAR )
	    IF( TEMP .LE. 32 ) GOTO 1170
	    IT = TEMP - 64
	    CELCNT = CELCNT - 1
	    IF(CELCNT.LT.CELCHR(IT,1).OR.CELCNT.GT.CELCHR(IT,2))
     &		GOTO 1180
	    CELLS( X, Y, NEWAR ) = CELLS( X, Y, IAR )
	    GOTO 1180
1170	    IF(CELCNT.LT.CELCHR(IT-64,3).OR.CELCNT.GT.CELCHR(IT-64,4))
     &		GOTO 1180
	    CELLS( X, Y, NEWAR ) = IT
	    IF( X .LT. MINX ) MINX = X
	    IF( X .GT. MAXX ) MAXX = X
	    IF( Y .LT. MINY ) MINY = Y
	    IF( Y .GT. MAXY ) MAXY = Y
1180	    IF( CELLS( X, Y, NEWAR ) .EQ. CELLS( X, Y, IAR ) )
     &		GOTO 1190
	    CHANGE = .TRUE.
	    CALL CURSOR( X+0, Y+4 )
	    IT = CELLS( X, Y, NEWAR )
	    CALL PCOLOR( MOD(IT,7)+1 )
	    CALL CHROUT( IT )
1190	CONTINUE
1191	IAR = NEWAR
	CALL CURBUF
	CALL NAP( NAPTIM, "14 )
	CALL CHRBUF( ICHAR )
	IF( ICHAR .EQ. -1 .AND. GEN .LT. GENTO .AND. CHANGE ) GOTO 1150
	IF( CHANGE ) GOTO 200
	CALL CURSOR( 1, 1 )
	CALL COLSTR(ICLLBL,'*** Culture has stabilized ***^E')
	GOTO 200

1200	NEWAR = 3-IAR
	IF( MAXX .LT. MINX ) GOTO 200
	CALL ERASE( CELLS, IAR, MINX, MAXX, MINY, MAXY )
	MINXS = MINX
	MINX = 80
	MAXXS = MAXX
	MAXX = 1
	MINYS = MINY
	MINY = 20
	MAXYS = MAXY
	MAXY = 1
	DO 1250 X = MINXS, MAXXS
	DO 1250 Y = MINYS, MAXYS
	    IF( CELLS( X, Y, IAR ) .EQ. 32 ) GOTO 1250
	    IF( X .LT. MINX ) MINX = X
	    IF( X .GT. MAXX ) MAXX = X
	    IF( Y .LT. MINY ) MINY = Y
	    IF( Y .GT. MAXY ) MAXY = Y
1250	CONTINUE
	IF( MAXX .LT. MINX ) GOTO 200
	XADD = 40 - (MAXX-MINX)/2 - MINX
	YADD = 10 - (MAXY-MINY)/2 - MINY
	IF( XADD .EQ. 0 .AND. YADD .EQ. 0 ) GOTO 200
	DO 1275 X = MINX, MAXX
	DO 1275 Y = MINY, MAXY
	    CELLS( X+XADD, Y+YADD, NEWAR ) = CELLS( X, Y, IAR )
	    CELLS( X, Y, IAR ) = 32
1275	CONTINUE
	IAR = NEWAR
	MINX = MINX + XADD
	MAXX = MAXX + XADD
	MINY = MINY + YADD
	MAXY = MAXY + YADD
	GOTO 900

1300	IF( ICOM2 .LT. 65 .OR. ICOM2 .GT. 91 ) GOTO 1350
	SPE = ICOM2
	TEMP = ICOM2 - 64
	CALL GETNUM( COMARA, ILEN, CELCHR(TEMP,1), 10,
     &CELCHR(TEMP,2), 10, CELCHR(TEMP,3), 10, CELCHR(TEMP,4), 10 )
	IF(CELCHR(TEMP,1).LT.1.OR.CELCHR(TEMP,1).GT.8)CELCHR(TEMP,1)=2
	IF(CELCHR(TEMP,2).LT.1.OR.CELCHR(TEMP,2).GT.8)CELCHR(TEMP,2)=3
	IF( CELCHR(TEMP,2) .LT. CELCHR(TEMP,1) )
     &		CELCHR(TEMP,2) = CELCHR(TEMP,1)
	IF(CELCHR(TEMP,3).LT.1.OR.CELCHR(TEMP,3).GT.8)CELCHR(TEMP,3)=3
	IF(CELCHR(TEMP,4).LT.1.OR.CELCHR(TEMP,4).GT.8)CELCHR(TEMP,4)=3
	IF( CELCHR(TEMP,4) .LT. CELCHR(TEMP,3) )
     &		CELCHR(TEMP,4) = CELCHR(TEMP,3)
	GOTO 200

1350	DO 1360 I = 1, 26
	    CELCHR( I, 1 ) = 2
	    CELCHR( I, 2 ) = 3
	    CELCHR( I, 3 ) = 3
	    CELCHR( I, 4 ) = 3
1360	CONTINUE
	CALL CURSOR( 1, 1 )
	CALL COLSTR(ICLLBL,'Cell characteristics reset.^E')
	GOTO 200

1400	IF( JOB(-1) .NE. 0 ) CALL USRSET( "2007, 1 )
	X = (MINX+MAXX)/2
	Y = (MINY+MAXY)/2
1450	CALL CURSOR( X, Y+4 )
	CALL PCOLOR( MOD( CELLS( X, Y, IAR ), 7 ) + 1 )
	CALL CHROUT( CELLS( X, Y, IAR ) )
	CALL CURSOR( X, Y+4 )
	CALL CURBUF
	CALL CHRWAT( ICHAR )
	IF( ICHAR .NE. 48 ) GOTO 1460
	IF( JOB(-1) .NE. 0 ) CALL USRSET( "2007, 0 )
	GOTO 200
1460	IF( ICHAR .NE. 53 ) GOTO 1470
	CELLS( X, Y, IAR ) = 32
	GOTO 1450
1470	IF( ICHAR .LT. 65 ) GOTO 1475
	IF( ICHAR .GT. 91 ) ICHAR = ICHAR - 32
	IF( ICHAR .LT. 65 .OR. ICHAR .GT. 91 ) GOTO 1480
	CELLS( X, Y, IAR ) = ICHAR
	SPE = ICHAR
	IF( X .LT. MINX ) MINX = X
	IF( X .GT. MAXX ) MAXX = X
	IF( Y .LT. MINY ) MINY = Y
	IF( Y .GT. MAXY ) MAXY = Y
	GOTO 1450
1475	ICHAR = ICHAR - 48
	IF( ICHAR .LT. 1 .OR. ICHAR .GT. 9 ) GOTO 1480
	X = X + XDIR( ICHAR )
	Y = Y + YDIR( ICHAR )
	IF( X .LT. 1 ) X = 1
	IF( X .GT. 80 ) X = 80
	IF( Y .LT. 1 ) Y = 1
	IF( Y .GT. 20 ) Y = 20
	GOTO 1450
1480	CALL CHROUT( 7 )
	GOTO 1450

1500	CALL GETNUM( COMARA, ILEN, NAPTIM, 10 )
	IF( NAPTIM .LE. 0 ) NAPTIM = 1
	GOTO 200

1600	IF( ICOM2 .LT. 65 .OR. ICOM2 .GT. 91 ) GOTO 1605
	CALL CURSOR( 1, 1 )
	CALL COLSTR(ICLLBL,'Status-^E')
	CALL CHROUT( ICOM2 )
	CALL STRING(':  MnLiv: ^E')
	CALL NUMBER( CELCHR( ICOM2-64, 1 ) )
	CALL STRING('   MxLiv: ^E')
	CALL NUMBER( CELCHR( ICOM2-64, 2 ) )
	CALL STRING('   MnBrn: ^E')
	CALL NUMBER( CELCHR( ICOM2-64, 3 ) )
	CALL STRING('   MxBrn: ^E')
	CALL NUMBER( CELCHR( ICOM2-64, 4 ) )
	GOTO 200

1605	NEWFLG = .TRUE.
	CALL CLRSCR
	CALL STRING('Cell characteristics:^M^J        A B C D E F G H
     & I J K L M N O P Q R S T U V W X Y Z^M^JMnLiv: ^E')
	DO 1610 I = 1, 26
	    CALL NUMBER( CELCHR( I, 1 ), 2 )
1610	CONTINUE
	CALL STRING('^M^JMxLiv: ^E')
	DO 1620 I = 1, 26
	    CALL NUMBER( CELCHR( I, 2 ), 2 )
1620	CONTINUE
	CALL STRING('^M^JMnBrn: ^E')
	DO 1630 I = 1, 26
	    CALL NUMBER( CELCHR( I, 3 ), 2 )
1630	CONTINUE
	CALL STRING('^M^JMxBrn: ^E')
	DO 1640 I = 1, 26
	    CALL NUMBER( CELCHR( I, 4 ), 2 )
1640	CONTINUE
	IF( MAXX .LT. MINX ) CALL COLSTR(ICLYEL,
     &	    '^M^J^JRanges undefined.^E')
	IF( MAXX .LT. MINX ) GOTO 1650
	CALL COLSTR(ICLLBL,'^M^J^JX-range: ^E')
	CALL NUMBER( MINX, 2 )
	CALL STRING(' - ^E')
	CALL NUMBER( MAXX, 2 )
	CALL STRING('   Y-range: ^E')
	CALL NUMBER( MINY, 2 )
	CALL STRING(' - ^E')
	CALL NUMBER( MAXY, 2 )
1650	CALL STRING('^M^JInterval: ^E')
	CALL NUMBER( NAPTIM )
	CALL STRING('^M^JCross breed: ^E')
	CALL CHROUT( MUT )
	CALL STRING('^M^JCurrent species: ^E')
	CALL CHROUT( SPE )
	GOTO 200

1690	IF( ICOM2 .LT. 65 .OR. ICOM2 .GT. 91 ) GOTO 225
	MUT = ICOM2
	GOTO 200

	END
	SUBROUTINE OUTSPL( IC, FILESP )
	IMPLICIT INTEGER ( A - Z )
	INTEGER FILESP(13)

	CALL CURSOR( 1, 1 )
	CALL NETSIX( IC )
	CALL CHROUT(' ')
	CALL OUTSPC( FILESP )
	CALL CURBUF
	RETURN
	END
	SUBROUTINE NETSIX( IWORD )
	IMPLICIT INTEGER ( A - Z )
	INTEGER WRDARA( 6 )

	CALL CONVRT( IWORD, 6, 6, WRDARA, 1 )
	ISPAC = ISERCH( WRDARA, ' ', 6 ) - 1
	IF( ISPAC .EQ. -1 ) ISPAC = 6
	IF( ISPAC .EQ. 0 ) RETURN
	CALL STRING( WRDARA, 1, ISPAC )
	RETURN
	END
	SUBROUTINE ERASE( CELLS, IAR, MINX, MAXX, MINY, MAXY )
	IMPLICIT INTEGER ( A - Z )

	INTEGER CELLS( 80, 20, 2 )

	NEWAR = 3-IAR
	DO 100 X = 1, 80
	DO 100 Y = 1, 20
	    CELLS( X, Y, NEWAR ) = 32
	    IF( X.LT.MINX.OR.X.GT.MAXX.OR.Y.LT.MINY.OR.Y.GT.MAXY )
     &		CELLS( X, Y, IAR ) = 32
100	CONTINUE
	RETURN
	END
	SUBROUTINE NEW( CELLS, IAR, MINX, MAXX, MINY, MAXY, GEN )
	IMPLICIT INTEGER ( A - Z )

	INTEGER CELLS( 80, 20, 2 )

	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA

	CALL CLRSCR
	IF( MAXX .LT. MINX ) GOTO 105
	DO 100 X = MINX, MAXX
	DO 100 Y = MINY, MAXY
	    IF( CELLS( X, Y, IAR ) .LE. 32 ) GOTO 100
	    CALL CURSOR( X+0, Y+4 )
	    CALL CHROUT( CELLS( X, Y, IAR ) )
100	CONTINUE
105	CALL CURSOR( 1, 4 )
	CALL COLSTR(ICLLBL,'Generation: ^E')
	CALL NUMBER( GEN, 4 )
	RETURN
	END

	SUBROUTINE COLCUR( IX, IY )
	CALL DEFCOL
	CALL CURSOR( IX, IY )
	RETURN
	END

    	SUBROUTINE COLSTR( ICOL, MSGARA )
	INTEGER MSGARA( 16 )
	CALL PCOLOR( ICOL )
	CALL STRING( MSGARA )
	RETURN
	END

    	SUBROUTINE DEFCOL

	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA

	CALL PBACK( ICLBLA )
	CALL PCOLOR( ICLWHI )
	RETURN
	END
