C	@HDR@	$Id$
C	@HDR@		Copyright 1982-2025 by
C	@HDR@		Christopher Caldwell/Brightsands
C	@HDR@		P.O. Box 401, Bailey Island, ME 04003
C	@HDR@		All Rights Reserved
C	@HDR@
C	@HDR@	This software comprises unpublished confidential information
C	@HDR@	of Brightsands and may not be used, copied or made available
C	@HDR@	to anyone, except in accordance with the license under which
C	@HDR@	it is furnished.
	SUBROUTINE FMAIN

	IMPLICIT INTEGER (A-Z)
	INTEGER COMARA( 80 ), PAR( 20 ), ILEN, FILSPC( 13 )
	INTEGER XPOS( 40 ), YPOS( 40 ), XDIR( 9 ), YDIR( 9 )
	INTEGER DDIR1( 9 ), DDIR2( 9 )
	LOGICAL PRIVD

	COMMON /COL/ICLWHI,ICLDBL,ICLRED,ICLLBL,
     &			ICLPUR,ICLGRE,ICLYEL,ICLBLA

	DATA XDIR/-1,0,1,-1,0,1,-1,0,1/, YDIR/-1,-1,-1,0,0,0,1,1,1/
	DATA DDIR1/4,1,2,7,0,3,8,9,6/
	DATA DDIR2/2,3,6,1,0,9,4,7,8/

	IF( ICLWHI .NE. 0 ) GOTO 3
	ICLWHI = 1
	ICLDBL = 2
	ICLRED = 3
	ICLLBL = 4
	ICLPUR = 5
	ICLGRE = 6
	ICLYEL = 7
	ICLBLA = 8

3	CALL SETTTY( COMARA, PAR, ILEN, PRIVD, FILSPC )
100	CALL PBACK( ICLBLA )
	CALL PCOLOR( ICLWHI )
	CALL STRING('Input snake size (1-40): ^B')
	CALL GETNUM( 10, ISIZE, 10 )
	IF( ISIZE .LE. 0 .OR. ISIZE .GT. 40 ) GOTO 100
	DO 150 I = 1, 40
	    XPOS(I) = 0
150	CONTINUE

	CALL CLRSCR
	CALL PBACK( ICLLBL )
	DO 200 I = 1, 23
	    CALL CURSOR( 1, I+1 )
	    CALL REPEAT('O',80)
200	CONTINUE
	CALL PBACK( ICLBLA )

	XPOS(1) = IRAN( 80 )
	YPOS(1) = IRAN( 23 ) + 1
300	IDIR = IRAN( 9 )
	IF( IDIR .EQ. 5 ) GOTO 300

400	CONTINUE
	CALL NAP( 100, 4 )
	CALL CURBUF
	CALL CHRBUF( ICHAR )
	IF( ICHAR .NE. -1 ) GOTO 1000
	IF( XPOS(ISIZE) .EQ. 0 ) GOTO 410
	IF( ISIZE .EQ. 1 ) GOTO 406
	DO 405 I = 1, ISIZE-1
	    IF(XPOS(I) .NE. XPOS(ISIZE)) GOTO 405
	    IF(YPOS(I) .EQ. YPOS(ISIZE)) GOTO 410
405	CONTINUE
406	CONTINUE
	CALL CURSOR( XPOS(ISIZE), YPOS(ISIZE) )
	CALL CHROUT(' ')
410	IF( ISIZE .EQ. 1 ) GOTO 451
	DO 450 I = ISIZE, 2, -1
	    XPOS(I) = XPOS(I-1)
	    YPOS(I) = YPOS(I-1)
450	CONTINUE
451	CONTINUE
	I = IRAN(3)
	IF( I .NE. 1 ) GOTO 500
475	NDIR = DDIR1( IDIR )
	IF( IRAN(10) .GT. 5 ) NDIR = DDIR2( IDIR )
	IDIR = NDIR

500	IF(XPOS(1)+XDIR(IDIR).LT.1.OR.XPOS(1)+XDIR(IDIR).GT.80)GOTO 475
	IF(YPOS(1)+YDIR(IDIR).LT.2.OR.YPOS(1)+YDIR(IDIR).GT.24)GOTO 475
	XPOS(1) = XPOS(1) + XDIR(IDIR)
	YPOS(1) = YPOS(1) + YDIR(IDIR)
	CALL CURSOR( XPOS(1), YPOS(1) )
	IF(IDIR.EQ.1) ICHAR = '+'
	IF(IDIR.EQ.2) ICHAR = '^'
	IF(IDIR.EQ.3) ICHAR = '+'
	IF(IDIR.EQ.4) ICHAR = '>'
	IF(IDIR.EQ.6) ICHAR = '<'
	IF(IDIR.EQ.7) ICHAR = '+'
	IF(IDIR.EQ.8) ICHAR = 'v'
	IF(IDIR.EQ.9) ICHAR = '+'
	CALL CHROUT( ICHAR )
	IF( XPOS(2) .EQ. 0 ) GOTO 400
	CALL CURSOR( XPOS(2), YPOS(2) )
	CALL CHROUT('*')
	GOTO 400

1000	CALL CLRSCR
	CALL CLOSE( 1 )
	CALL GRAFOF
	CALL PSTOP
	END
